package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ivot018p0 generated by hbm2java
 */
@Entity
@Table(name = "IVOT018P0")
public class Ivot018p0 implements java.io.Serializable {

	private Ivot018p0Id id;
	private Long asstCblcQty;
	private Long asstCblcAmt;
	private Long asstEvluAmt;
	private Long asstEvluPrftAmt;
	private Long asstEvluLossAmt;
	private Long asstAcmlRpchParAmt;
	private Long asstAcmlRpchQty;
	private Long debtCblcQty;
	private Long debtCblcAmt;
	private Long debtEvluAmt;
	private Long debtEvluPrftAmt;
	private Long debtEvluLossAmt;
	private Long debtAcmlRpchAmt;
	private Long debtAcmlRpchQty;
	private Long debtAcmlRpchRbuyAmt;
	private Long debtAcmlRpchRbuyQty;
	private Long lmtUseAmt;
	private Long asstAbks;
	private Long asstFee;
	private Long debtAbks;
	private Long debtFee;
	private BigDecimal asstAcbkUnpr;
	private BigDecimal asstEvluUnpr;
	private BigDecimal debtAcbkUnpr;
	private BigDecimal debtEvluUnpr;
	private Long asstBgtQty;
	private Long asstBgtAbks;
	private BigDecimal asstEvluBassUnpr;
	private BigDecimal asstAdjtCefc;
	private Long debtBgtQty;
	private Long debtBgtAbks;
	private BigDecimal debtEvluBassUnpr;
	private BigDecimal debtAdjtCefc;
	private String actgRfltYn;
	private Long swapPremAcmlRpchAmt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private Long debtAcmlSrdpAmt;
	private Long debtAcmlSrdpQty;
	private Long asstAcmlSrdpParAmt;
	private Long asstAcmlSrdpTrAmt;
	private Long asstAcmlSrdpQty;
	private Long swapPremAcmlSrdpAmt;
	private Long debtBgtSrdpQty;
	private Long asstBgtSrdpQty;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Ivot018p0() {
	}

	public Ivot018p0(Ivot018p0Id id) {
		this.id = id;
	}

	public Ivot018p0(Ivot018p0Id id, Long asstCblcQty, Long asstCblcAmt, Long asstEvluAmt, Long asstEvluPrftAmt,
			Long asstEvluLossAmt, Long asstAcmlRpchParAmt, Long asstAcmlRpchQty, Long debtCblcQty, Long debtCblcAmt,
			Long debtEvluAmt, Long debtEvluPrftAmt, Long debtEvluLossAmt, Long debtAcmlRpchAmt, Long debtAcmlRpchQty,
			Long debtAcmlRpchRbuyAmt, Long debtAcmlRpchRbuyQty, Long lmtUseAmt, Long asstAbks, Long asstFee,
			Long debtAbks, Long debtFee, BigDecimal asstAcbkUnpr, BigDecimal asstEvluUnpr, BigDecimal debtAcbkUnpr,
			BigDecimal debtEvluUnpr, Long asstBgtQty, Long asstBgtAbks, BigDecimal asstEvluBassUnpr,
			BigDecimal asstAdjtCefc, Long debtBgtQty, Long debtBgtAbks, BigDecimal debtEvluBassUnpr,
			BigDecimal debtAdjtCefc, String actgRfltYn, Long swapPremAcmlRpchAmt, String oprtStfno, String oprtTmno,
			String oprtDtlDtime, String oprtTrCd, Long debtAcmlSrdpAmt, Long debtAcmlSrdpQty, Long asstAcmlSrdpParAmt,
			Long asstAcmlSrdpTrAmt, Long asstAcmlSrdpQty, Long swapPremAcmlSrdpAmt, Long debtBgtSrdpQty,
			Long asstBgtSrdpQty, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.asstCblcQty = asstCblcQty;
		this.asstCblcAmt = asstCblcAmt;
		this.asstEvluAmt = asstEvluAmt;
		this.asstEvluPrftAmt = asstEvluPrftAmt;
		this.asstEvluLossAmt = asstEvluLossAmt;
		this.asstAcmlRpchParAmt = asstAcmlRpchParAmt;
		this.asstAcmlRpchQty = asstAcmlRpchQty;
		this.debtCblcQty = debtCblcQty;
		this.debtCblcAmt = debtCblcAmt;
		this.debtEvluAmt = debtEvluAmt;
		this.debtEvluPrftAmt = debtEvluPrftAmt;
		this.debtEvluLossAmt = debtEvluLossAmt;
		this.debtAcmlRpchAmt = debtAcmlRpchAmt;
		this.debtAcmlRpchQty = debtAcmlRpchQty;
		this.debtAcmlRpchRbuyAmt = debtAcmlRpchRbuyAmt;
		this.debtAcmlRpchRbuyQty = debtAcmlRpchRbuyQty;
		this.lmtUseAmt = lmtUseAmt;
		this.asstAbks = asstAbks;
		this.asstFee = asstFee;
		this.debtAbks = debtAbks;
		this.debtFee = debtFee;
		this.asstAcbkUnpr = asstAcbkUnpr;
		this.asstEvluUnpr = asstEvluUnpr;
		this.debtAcbkUnpr = debtAcbkUnpr;
		this.debtEvluUnpr = debtEvluUnpr;
		this.asstBgtQty = asstBgtQty;
		this.asstBgtAbks = asstBgtAbks;
		this.asstEvluBassUnpr = asstEvluBassUnpr;
		this.asstAdjtCefc = asstAdjtCefc;
		this.debtBgtQty = debtBgtQty;
		this.debtBgtAbks = debtBgtAbks;
		this.debtEvluBassUnpr = debtEvluBassUnpr;
		this.debtAdjtCefc = debtAdjtCefc;
		this.actgRfltYn = actgRfltYn;
		this.swapPremAcmlRpchAmt = swapPremAcmlRpchAmt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.debtAcmlSrdpAmt = debtAcmlSrdpAmt;
		this.debtAcmlSrdpQty = debtAcmlSrdpQty;
		this.asstAcmlSrdpParAmt = asstAcmlSrdpParAmt;
		this.asstAcmlSrdpTrAmt = asstAcmlSrdpTrAmt;
		this.asstAcmlSrdpQty = asstAcmlSrdpQty;
		this.swapPremAcmlSrdpAmt = swapPremAcmlSrdpAmt;
		this.debtBgtSrdpQty = debtBgtSrdpQty;
		this.asstBgtSrdpQty = asstBgtSrdpQty;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "evluBassDt", column = @Column(name = "EVLU_BASS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "trOppnNo", column = @Column(name = "TR_OPPN_NO", nullable = false, length = 12)),
			@AttributeOverride(name = "elsTrDtldTypeCd", column = @Column(name = "ELS_TR_DTLD_TYPE_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "issuTmod", column = @Column(name = "ISSU_TMOD", nullable = false, precision = 9, scale = 0)) })
	public Ivot018p0Id getId() {
		return this.id;
	}

	public void setId(Ivot018p0Id id) {
		this.id = id;
	}

	@Column(name = "ASST_CBLC_QTY", precision = 18, scale = 0)
	public Long getAsstCblcQty() {
		return this.asstCblcQty;
	}

	public void setAsstCblcQty(Long asstCblcQty) {
		this.asstCblcQty = asstCblcQty;
	}

	@Column(name = "ASST_CBLC_AMT", precision = 18, scale = 0)
	public Long getAsstCblcAmt() {
		return this.asstCblcAmt;
	}

	public void setAsstCblcAmt(Long asstCblcAmt) {
		this.asstCblcAmt = asstCblcAmt;
	}

	@Column(name = "ASST_EVLU_AMT", precision = 18, scale = 0)
	public Long getAsstEvluAmt() {
		return this.asstEvluAmt;
	}

	public void setAsstEvluAmt(Long asstEvluAmt) {
		this.asstEvluAmt = asstEvluAmt;
	}

	@Column(name = "ASST_EVLU_PRFT_AMT", precision = 18, scale = 0)
	public Long getAsstEvluPrftAmt() {
		return this.asstEvluPrftAmt;
	}

	public void setAsstEvluPrftAmt(Long asstEvluPrftAmt) {
		this.asstEvluPrftAmt = asstEvluPrftAmt;
	}

	@Column(name = "ASST_EVLU_LOSS_AMT", precision = 18, scale = 0)
	public Long getAsstEvluLossAmt() {
		return this.asstEvluLossAmt;
	}

	public void setAsstEvluLossAmt(Long asstEvluLossAmt) {
		this.asstEvluLossAmt = asstEvluLossAmt;
	}

	@Column(name = "ASST_ACML_RPCH_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlRpchParAmt() {
		return this.asstAcmlRpchParAmt;
	}

	public void setAsstAcmlRpchParAmt(Long asstAcmlRpchParAmt) {
		this.asstAcmlRpchParAmt = asstAcmlRpchParAmt;
	}

	@Column(name = "ASST_ACML_RPCH_QTY", precision = 18, scale = 0)
	public Long getAsstAcmlRpchQty() {
		return this.asstAcmlRpchQty;
	}

	public void setAsstAcmlRpchQty(Long asstAcmlRpchQty) {
		this.asstAcmlRpchQty = asstAcmlRpchQty;
	}

	@Column(name = "DEBT_CBLC_QTY", precision = 18, scale = 0)
	public Long getDebtCblcQty() {
		return this.debtCblcQty;
	}

	public void setDebtCblcQty(Long debtCblcQty) {
		this.debtCblcQty = debtCblcQty;
	}

	@Column(name = "DEBT_CBLC_AMT", precision = 18, scale = 0)
	public Long getDebtCblcAmt() {
		return this.debtCblcAmt;
	}

	public void setDebtCblcAmt(Long debtCblcAmt) {
		this.debtCblcAmt = debtCblcAmt;
	}

	@Column(name = "DEBT_EVLU_AMT", precision = 18, scale = 0)
	public Long getDebtEvluAmt() {
		return this.debtEvluAmt;
	}

	public void setDebtEvluAmt(Long debtEvluAmt) {
		this.debtEvluAmt = debtEvluAmt;
	}

	@Column(name = "DEBT_EVLU_PRFT_AMT", precision = 18, scale = 0)
	public Long getDebtEvluPrftAmt() {
		return this.debtEvluPrftAmt;
	}

	public void setDebtEvluPrftAmt(Long debtEvluPrftAmt) {
		this.debtEvluPrftAmt = debtEvluPrftAmt;
	}

	@Column(name = "DEBT_EVLU_LOSS_AMT", precision = 18, scale = 0)
	public Long getDebtEvluLossAmt() {
		return this.debtEvluLossAmt;
	}

	public void setDebtEvluLossAmt(Long debtEvluLossAmt) {
		this.debtEvluLossAmt = debtEvluLossAmt;
	}

	@Column(name = "DEBT_ACML_RPCH_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlRpchAmt() {
		return this.debtAcmlRpchAmt;
	}

	public void setDebtAcmlRpchAmt(Long debtAcmlRpchAmt) {
		this.debtAcmlRpchAmt = debtAcmlRpchAmt;
	}

	@Column(name = "DEBT_ACML_RPCH_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlRpchQty() {
		return this.debtAcmlRpchQty;
	}

	public void setDebtAcmlRpchQty(Long debtAcmlRpchQty) {
		this.debtAcmlRpchQty = debtAcmlRpchQty;
	}

	@Column(name = "DEBT_ACML_RPCH_RBUY_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlRpchRbuyAmt() {
		return this.debtAcmlRpchRbuyAmt;
	}

	public void setDebtAcmlRpchRbuyAmt(Long debtAcmlRpchRbuyAmt) {
		this.debtAcmlRpchRbuyAmt = debtAcmlRpchRbuyAmt;
	}

	@Column(name = "DEBT_ACML_RPCH_RBUY_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlRpchRbuyQty() {
		return this.debtAcmlRpchRbuyQty;
	}

	public void setDebtAcmlRpchRbuyQty(Long debtAcmlRpchRbuyQty) {
		this.debtAcmlRpchRbuyQty = debtAcmlRpchRbuyQty;
	}

	@Column(name = "LMT_USE_AMT", precision = 18, scale = 0)
	public Long getLmtUseAmt() {
		return this.lmtUseAmt;
	}

	public void setLmtUseAmt(Long lmtUseAmt) {
		this.lmtUseAmt = lmtUseAmt;
	}

	@Column(name = "ASST_ABKS", precision = 18, scale = 0)
	public Long getAsstAbks() {
		return this.asstAbks;
	}

	public void setAsstAbks(Long asstAbks) {
		this.asstAbks = asstAbks;
	}

	@Column(name = "ASST_FEE", precision = 18, scale = 0)
	public Long getAsstFee() {
		return this.asstFee;
	}

	public void setAsstFee(Long asstFee) {
		this.asstFee = asstFee;
	}

	@Column(name = "DEBT_ABKS", precision = 18, scale = 0)
	public Long getDebtAbks() {
		return this.debtAbks;
	}

	public void setDebtAbks(Long debtAbks) {
		this.debtAbks = debtAbks;
	}

	@Column(name = "DEBT_FEE", precision = 18, scale = 0)
	public Long getDebtFee() {
		return this.debtFee;
	}

	public void setDebtFee(Long debtFee) {
		this.debtFee = debtFee;
	}

	@Column(name = "ASST_ACBK_UNPR", precision = 21, scale = 8)
	public BigDecimal getAsstAcbkUnpr() {
		return this.asstAcbkUnpr;
	}

	public void setAsstAcbkUnpr(BigDecimal asstAcbkUnpr) {
		this.asstAcbkUnpr = asstAcbkUnpr;
	}

	@Column(name = "ASST_EVLU_UNPR", precision = 21, scale = 8)
	public BigDecimal getAsstEvluUnpr() {
		return this.asstEvluUnpr;
	}

	public void setAsstEvluUnpr(BigDecimal asstEvluUnpr) {
		this.asstEvluUnpr = asstEvluUnpr;
	}

	@Column(name = "DEBT_ACBK_UNPR", precision = 21, scale = 8)
	public BigDecimal getDebtAcbkUnpr() {
		return this.debtAcbkUnpr;
	}

	public void setDebtAcbkUnpr(BigDecimal debtAcbkUnpr) {
		this.debtAcbkUnpr = debtAcbkUnpr;
	}

	@Column(name = "DEBT_EVLU_UNPR", precision = 21, scale = 8)
	public BigDecimal getDebtEvluUnpr() {
		return this.debtEvluUnpr;
	}

	public void setDebtEvluUnpr(BigDecimal debtEvluUnpr) {
		this.debtEvluUnpr = debtEvluUnpr;
	}

	@Column(name = "ASST_BGT_QTY", precision = 18, scale = 0)
	public Long getAsstBgtQty() {
		return this.asstBgtQty;
	}

	public void setAsstBgtQty(Long asstBgtQty) {
		this.asstBgtQty = asstBgtQty;
	}

	@Column(name = "ASST_BGT_ABKS", precision = 18, scale = 0)
	public Long getAsstBgtAbks() {
		return this.asstBgtAbks;
	}

	public void setAsstBgtAbks(Long asstBgtAbks) {
		this.asstBgtAbks = asstBgtAbks;
	}

	@Column(name = "ASST_EVLU_BASS_UNPR", precision = 23, scale = 15)
	public BigDecimal getAsstEvluBassUnpr() {
		return this.asstEvluBassUnpr;
	}

	public void setAsstEvluBassUnpr(BigDecimal asstEvluBassUnpr) {
		this.asstEvluBassUnpr = asstEvluBassUnpr;
	}

	@Column(name = "ASST_ADJT_CEFC", precision = 23, scale = 15)
	public BigDecimal getAsstAdjtCefc() {
		return this.asstAdjtCefc;
	}

	public void setAsstAdjtCefc(BigDecimal asstAdjtCefc) {
		this.asstAdjtCefc = asstAdjtCefc;
	}

	@Column(name = "DEBT_BGT_QTY", precision = 18, scale = 0)
	public Long getDebtBgtQty() {
		return this.debtBgtQty;
	}

	public void setDebtBgtQty(Long debtBgtQty) {
		this.debtBgtQty = debtBgtQty;
	}

	@Column(name = "DEBT_BGT_ABKS", precision = 18, scale = 0)
	public Long getDebtBgtAbks() {
		return this.debtBgtAbks;
	}

	public void setDebtBgtAbks(Long debtBgtAbks) {
		this.debtBgtAbks = debtBgtAbks;
	}

	@Column(name = "DEBT_EVLU_BASS_UNPR", precision = 23, scale = 15)
	public BigDecimal getDebtEvluBassUnpr() {
		return this.debtEvluBassUnpr;
	}

	public void setDebtEvluBassUnpr(BigDecimal debtEvluBassUnpr) {
		this.debtEvluBassUnpr = debtEvluBassUnpr;
	}

	@Column(name = "DEBT_ADJT_CEFC", precision = 23, scale = 15)
	public BigDecimal getDebtAdjtCefc() {
		return this.debtAdjtCefc;
	}

	public void setDebtAdjtCefc(BigDecimal debtAdjtCefc) {
		this.debtAdjtCefc = debtAdjtCefc;
	}

	@Column(name = "ACTG_RFLT_YN", length = 1)
	public String getActgRfltYn() {
		return this.actgRfltYn;
	}

	public void setActgRfltYn(String actgRfltYn) {
		this.actgRfltYn = actgRfltYn;
	}

	@Column(name = "SWAP_PREM_ACML_RPCH_AMT", precision = 18, scale = 0)
	public Long getSwapPremAcmlRpchAmt() {
		return this.swapPremAcmlRpchAmt;
	}

	public void setSwapPremAcmlRpchAmt(Long swapPremAcmlRpchAmt) {
		this.swapPremAcmlRpchAmt = swapPremAcmlRpchAmt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "DEBT_ACML_SRDP_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlSrdpAmt() {
		return this.debtAcmlSrdpAmt;
	}

	public void setDebtAcmlSrdpAmt(Long debtAcmlSrdpAmt) {
		this.debtAcmlSrdpAmt = debtAcmlSrdpAmt;
	}

	@Column(name = "DEBT_ACML_SRDP_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlSrdpQty() {
		return this.debtAcmlSrdpQty;
	}

	public void setDebtAcmlSrdpQty(Long debtAcmlSrdpQty) {
		this.debtAcmlSrdpQty = debtAcmlSrdpQty;
	}

	@Column(name = "ASST_ACML_SRDP_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpParAmt() {
		return this.asstAcmlSrdpParAmt;
	}

	public void setAsstAcmlSrdpParAmt(Long asstAcmlSrdpParAmt) {
		this.asstAcmlSrdpParAmt = asstAcmlSrdpParAmt;
	}

	@Column(name = "ASST_ACML_SRDP_TR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpTrAmt() {
		return this.asstAcmlSrdpTrAmt;
	}

	public void setAsstAcmlSrdpTrAmt(Long asstAcmlSrdpTrAmt) {
		this.asstAcmlSrdpTrAmt = asstAcmlSrdpTrAmt;
	}

	@Column(name = "ASST_ACML_SRDP_QTY", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpQty() {
		return this.asstAcmlSrdpQty;
	}

	public void setAsstAcmlSrdpQty(Long asstAcmlSrdpQty) {
		this.asstAcmlSrdpQty = asstAcmlSrdpQty;
	}

	@Column(name = "SWAP_PREM_ACML_SRDP_AMT", precision = 18, scale = 0)
	public Long getSwapPremAcmlSrdpAmt() {
		return this.swapPremAcmlSrdpAmt;
	}

	public void setSwapPremAcmlSrdpAmt(Long swapPremAcmlSrdpAmt) {
		this.swapPremAcmlSrdpAmt = swapPremAcmlSrdpAmt;
	}

	@Column(name = "DEBT_BGT_SRDP_QTY", precision = 18, scale = 0)
	public Long getDebtBgtSrdpQty() {
		return this.debtBgtSrdpQty;
	}

	public void setDebtBgtSrdpQty(Long debtBgtSrdpQty) {
		this.debtBgtSrdpQty = debtBgtSrdpQty;
	}

	@Column(name = "ASST_BGT_SRDP_QTY", precision = 18, scale = 0)
	public Long getAsstBgtSrdpQty() {
		return this.asstBgtSrdpQty;
	}

	public void setAsstBgtSrdpQty(Long asstBgtSrdpQty) {
		this.asstBgtSrdpQty = asstBgtSrdpQty;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
