package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ivot073p0 generated by hbm2java
 */
@Entity
@Table(name = "IVOT073P0")
public class Ivot073p0 implements java.io.Serializable {

	private String aplyStrtDt;
	private String aplyEndDt;
	private String ivCrdtGradCd;
	private String mmrkBztpCd;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String bpmsPrdtClsfCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Ivot073p0() {
	}

	public Ivot073p0(String aplyStrtDt) {
		this.aplyStrtDt = aplyStrtDt;
	}

	public Ivot073p0(String aplyStrtDt, String aplyEndDt, String ivCrdtGradCd, String mmrkBztpCd, String oprtStfno,
			String oprtTmno, String oprtDtlDtime, String oprtTrCd, String bpmsPrdtClsfCd, String lastChngPgmName,
			Date lastChngDtime) {
		this.aplyStrtDt = aplyStrtDt;
		this.aplyEndDt = aplyEndDt;
		this.ivCrdtGradCd = ivCrdtGradCd;
		this.mmrkBztpCd = mmrkBztpCd;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.bpmsPrdtClsfCd = bpmsPrdtClsfCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@Id
	@Column(name = "APLY_STRT_DT", unique = true, nullable = false, length = 8)
	public String getAplyStrtDt() {
		return this.aplyStrtDt;
	}

	public void setAplyStrtDt(String aplyStrtDt) {
		this.aplyStrtDt = aplyStrtDt;
	}

	@Column(name = "APLY_END_DT", length = 8)
	public String getAplyEndDt() {
		return this.aplyEndDt;
	}

	public void setAplyEndDt(String aplyEndDt) {
		this.aplyEndDt = aplyEndDt;
	}

	@Column(name = "IV_CRDT_GRAD_CD", length = 4)
	public String getIvCrdtGradCd() {
		return this.ivCrdtGradCd;
	}

	public void setIvCrdtGradCd(String ivCrdtGradCd) {
		this.ivCrdtGradCd = ivCrdtGradCd;
	}

	@Column(name = "MMRK_BZTP_CD", length = 7)
	public String getMmrkBztpCd() {
		return this.mmrkBztpCd;
	}

	public void setMmrkBztpCd(String mmrkBztpCd) {
		this.mmrkBztpCd = mmrkBztpCd;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "BPMS_PRDT_CLSF_CD", length = 12)
	public String getBpmsPrdtClsfCd() {
		return this.bpmsPrdtClsfCd;
	}

	public void setBpmsPrdtClsfCd(String bpmsPrdtClsfCd) {
		this.bpmsPrdtClsfCd = bpmsPrdtClsfCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
