package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.eugenefe.enums.raw.EElsTrDetailType;

/**
 * Ivot015p0 generated by hbm2java
 */
@Entity
@Table(name = "IVOT015P0")
public class Ivot015p0 implements java.io.Serializable {

	private Ivot015p0Id id;
	private EElsTrDetailType elsTrDtldTypeCd;
	private Pdif004m0 elsMaster;
	private String erlmDt;
	private Long debtTrParQty;
	private Long debtTrParAmt;
	private Long debtTrPymtAmt;
	private Long debtTrPymtQty;
	private Long debtAcmlRpchAmt;
	private Long debtAcmlRpchQty;
	private Long debtAcmlRpchRbuyAmt;
	private Long debtAcmlRpchRbuyQty;
	private Long cblcAmt;
	private Long cblcQty;
	private Long asstTrParAmt;
	private Long elsPchsQty;
	private BigDecimal elsParAmt;
	private BigDecimal elsPchsUnpr;
	private BigDecimal dsgnPchsUnpr;
	private Long asstAcmlRpchParAmt;
	private Long asstAcmlRpchTrAmt;
	private Long asstAcmlRpchQty;
	private Long asstCblcParAmt;
	private Long asstCblcTrAmt;
	private Long asstCblcQty;
	private BigDecimal utlzFundPrcaAsrcRt;
	private BigDecimal dsctInrt;
	private Long bondAdmsAmt;
	private BigDecimal bondAdmsRt;
	private Long optAdmsAmt;
	private BigDecimal optAdmsRt;
	private BigDecimal optPtciRt;
	private String optPtciRtYn;
	private BigDecimal dsgnPcstRt;
	private Long dsgnPcstAmt;
	private BigDecimal dsgnFeeRt;
	private Long dsgnFeeAmt;
	private String swapPremDvsnCd;
	private BigDecimal swapPremRt;
	private Long swapPremAmt;
	private String swapPremPrcsDt;
	private String ivCrdtGradCd;
	private BigDecimal evluDsctIntr;
	private Long bondEvluAmt;
	private Long optEvluAmt;
	private Long optPchsAmt;
	private String optPchsDfrmDt;
	private Long bondOptEvluPchsAmt;
	private BigDecimal bondOptEvluPchsRt;
	private BigDecimal elsEvluRt;
	private Long elsEvluAmt;
	private BigDecimal elsPchsRt;
	private Long elsPchsAmt;
	private String pchsDfrmDt;
	private String intExchFrqcDvsnCd;
	private String dfrmSwapIntDvsnCd;
	private String rcivSwapIntDvsnCd;
	private String ofbdDrvSttlTypeCd;
	private String crcyCd;
	private String fxDecsDt;
	private BigDecimal lmtImpsRt;
	private Long trOppnLmtAmt;
	private Long lmtUseAmt;
	private String ctrtDt;
	private Long asstEvluAmt;
	private Long asstEvluPrftAmt;
	private Long asstEvluLossAmt;
	private Long debtEvluAmt;
	private Long debtEvluPrftAmt;
	private Long debtEvluLossAmt;
	private Long asstAbks;
	private Long asstFee;
	private Long debtAbks;
	private Long debtFee;
	private BigDecimal asstAcbkUnpr;
	private BigDecimal asstEvluUnpr;
	private BigDecimal debtAcbkUnpr;
	private BigDecimal debtEvluUnpr;
	private Long asstBgtQty;
	private Long asstBgtAbks;
	private BigDecimal asstEvluBassUnpr;
	private BigDecimal asstAdjtCefc;
	private Long debtBgtQty;
	private Long debtBgtAbks;
	private BigDecimal debtEvluBassUnpr;
	private BigDecimal debtAdjtCefc;
	private String ofbdDrvActpDvsnCd;
	private String rdptYn;
	private String actgRfltYn;
	private Long swapPremAcmlRpchAmt;
	private Long fee;
	private String utlzFundCd;
	private String elsPchsObjtTypeCd;
	private String intCalcDt;
	private BigDecimal dfrmIntRtEtcRt;
	private String dfrmIntRtEtcText;
	private BigDecimal rcivIntRtEtcRt;
	private String rcivIntRtEtcText;
	private String frstMrgnCrcyCd;
	private BigDecimal frstMrgnRt;
	private Long frstMrgnAmt;
	private String csaAplyYn;
	private String trOppnRefText;
	private String asstTrDt;
	private String asstExpdDt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String ofbdDrvEvluMthdCd;
	private String imncBondDscmNo;
	private BigDecimal imncBondBssEvluUnpr;
	private String swapIntCalcDcntDvsnCd;
	private String swapIntCalcDcntDtlCd;
	private String swapIntCalcMthdCd;
	private Long debtAcmlSrdpAmt;
	private Long debtAcmlSrdpQty;
	private Long asstAcmlSrdpParAmt;
	private Long asstAcmlSrdpTrAmt;
	private Long asstAcmlSrdpQty;
	private Long swapPremAcmlSrdpAmt;
	private String elsPchsPrdtDscmNo;
	private String elsPchsPrdtName;
	private String elsPchsSameItemYn;
	private String elsPchsSamePdno;
	private String elsPchsSamePrdtTypeCd;
	private String rcivIntExchFrqcDvsnCd;
	private String elsPcstlDfrmRcivDvsnCd;
	private String elsPcstlDt;
	private Long debtBgtSrdpQty;
	private Long asstBgtSrdpQty;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Ivot015p0() {
	}

	public Ivot015p0(Ivot015p0Id id) {
		this.id = id;
	}

	public Ivot015p0(Ivot015p0Id id, String erlmDt, Long debtTrParQty, Long debtTrParAmt, Long debtTrPymtAmt,
			Long debtTrPymtQty, Long debtAcmlRpchAmt, Long debtAcmlRpchQty, Long debtAcmlRpchRbuyAmt,
			Long debtAcmlRpchRbuyQty, Long cblcAmt, Long cblcQty, Long asstTrParAmt, Long elsPchsQty,
			BigDecimal elsParAmt, BigDecimal elsPchsUnpr, BigDecimal dsgnPchsUnpr, Long asstAcmlRpchParAmt,
			Long asstAcmlRpchTrAmt, Long asstAcmlRpchQty, Long asstCblcParAmt, Long asstCblcTrAmt, Long asstCblcQty,
			BigDecimal utlzFundPrcaAsrcRt, BigDecimal dsctInrt, Long bondAdmsAmt, BigDecimal bondAdmsRt,
			Long optAdmsAmt, BigDecimal optAdmsRt, BigDecimal optPtciRt, String optPtciRtYn, BigDecimal dsgnPcstRt,
			Long dsgnPcstAmt, BigDecimal dsgnFeeRt, Long dsgnFeeAmt, String swapPremDvsnCd, BigDecimal swapPremRt,
			Long swapPremAmt, String swapPremPrcsDt, String ivCrdtGradCd, BigDecimal evluDsctIntr, Long bondEvluAmt,
			Long optEvluAmt, Long optPchsAmt, String optPchsDfrmDt, Long bondOptEvluPchsAmt,
			BigDecimal bondOptEvluPchsRt, BigDecimal elsEvluRt, Long elsEvluAmt, BigDecimal elsPchsRt, Long elsPchsAmt,
			String pchsDfrmDt, String intExchFrqcDvsnCd, String dfrmSwapIntDvsnCd, String rcivSwapIntDvsnCd,
			String ofbdDrvSttlTypeCd, String crcyCd, String fxDecsDt, BigDecimal lmtImpsRt, Long trOppnLmtAmt,
			Long lmtUseAmt, String ctrtDt, Long asstEvluAmt, Long asstEvluPrftAmt, Long asstEvluLossAmt,
			Long debtEvluAmt, Long debtEvluPrftAmt, Long debtEvluLossAmt, Long asstAbks, Long asstFee, Long debtAbks,
			Long debtFee, BigDecimal asstAcbkUnpr, BigDecimal asstEvluUnpr, BigDecimal debtAcbkUnpr,
			BigDecimal debtEvluUnpr, Long asstBgtQty, Long asstBgtAbks, BigDecimal asstEvluBassUnpr,
			BigDecimal asstAdjtCefc, Long debtBgtQty, Long debtBgtAbks, BigDecimal debtEvluBassUnpr,
			BigDecimal debtAdjtCefc, String ofbdDrvActpDvsnCd, String rdptYn, String actgRfltYn,
			Long swapPremAcmlRpchAmt, Long fee, String utlzFundCd, String elsPchsObjtTypeCd, String intCalcDt,
			BigDecimal dfrmIntRtEtcRt, String dfrmIntRtEtcText, BigDecimal rcivIntRtEtcRt, String rcivIntRtEtcText,
			String frstMrgnCrcyCd, BigDecimal frstMrgnRt, Long frstMrgnAmt, String csaAplyYn, String trOppnRefText,
			String asstTrDt, String asstExpdDt, String oprtStfno, String oprtTmno, String oprtDtlDtime,
			String oprtTrCd, String ofbdDrvEvluMthdCd, String imncBondDscmNo, BigDecimal imncBondBssEvluUnpr,
			String swapIntCalcDcntDvsnCd, String swapIntCalcDcntDtlCd, String swapIntCalcMthdCd, Long debtAcmlSrdpAmt,
			Long debtAcmlSrdpQty, Long asstAcmlSrdpParAmt, Long asstAcmlSrdpTrAmt, Long asstAcmlSrdpQty,
			Long swapPremAcmlSrdpAmt, String elsPchsPrdtDscmNo, String elsPchsPrdtName, String elsPchsSameItemYn,
			String elsPchsSamePdno, String elsPchsSamePrdtTypeCd, String rcivIntExchFrqcDvsnCd,
			String elsPcstlDfrmRcivDvsnCd, String elsPcstlDt, Long debtBgtSrdpQty, Long asstBgtSrdpQty,
			String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.erlmDt = erlmDt;
		this.debtTrParQty = debtTrParQty;
		this.debtTrParAmt = debtTrParAmt;
		this.debtTrPymtAmt = debtTrPymtAmt;
		this.debtTrPymtQty = debtTrPymtQty;
		this.debtAcmlRpchAmt = debtAcmlRpchAmt;
		this.debtAcmlRpchQty = debtAcmlRpchQty;
		this.debtAcmlRpchRbuyAmt = debtAcmlRpchRbuyAmt;
		this.debtAcmlRpchRbuyQty = debtAcmlRpchRbuyQty;
		this.cblcAmt = cblcAmt;
		this.cblcQty = cblcQty;
		this.asstTrParAmt = asstTrParAmt;
		this.elsPchsQty = elsPchsQty;
		this.elsParAmt = elsParAmt;
		this.elsPchsUnpr = elsPchsUnpr;
		this.dsgnPchsUnpr = dsgnPchsUnpr;
		this.asstAcmlRpchParAmt = asstAcmlRpchParAmt;
		this.asstAcmlRpchTrAmt = asstAcmlRpchTrAmt;
		this.asstAcmlRpchQty = asstAcmlRpchQty;
		this.asstCblcParAmt = asstCblcParAmt;
		this.asstCblcTrAmt = asstCblcTrAmt;
		this.asstCblcQty = asstCblcQty;
		this.utlzFundPrcaAsrcRt = utlzFundPrcaAsrcRt;
		this.dsctInrt = dsctInrt;
		this.bondAdmsAmt = bondAdmsAmt;
		this.bondAdmsRt = bondAdmsRt;
		this.optAdmsAmt = optAdmsAmt;
		this.optAdmsRt = optAdmsRt;
		this.optPtciRt = optPtciRt;
		this.optPtciRtYn = optPtciRtYn;
		this.dsgnPcstRt = dsgnPcstRt;
		this.dsgnPcstAmt = dsgnPcstAmt;
		this.dsgnFeeRt = dsgnFeeRt;
		this.dsgnFeeAmt = dsgnFeeAmt;
		this.swapPremDvsnCd = swapPremDvsnCd;
		this.swapPremRt = swapPremRt;
		this.swapPremAmt = swapPremAmt;
		this.swapPremPrcsDt = swapPremPrcsDt;
		this.ivCrdtGradCd = ivCrdtGradCd;
		this.evluDsctIntr = evluDsctIntr;
		this.bondEvluAmt = bondEvluAmt;
		this.optEvluAmt = optEvluAmt;
		this.optPchsAmt = optPchsAmt;
		this.optPchsDfrmDt = optPchsDfrmDt;
		this.bondOptEvluPchsAmt = bondOptEvluPchsAmt;
		this.bondOptEvluPchsRt = bondOptEvluPchsRt;
		this.elsEvluRt = elsEvluRt;
		this.elsEvluAmt = elsEvluAmt;
		this.elsPchsRt = elsPchsRt;
		this.elsPchsAmt = elsPchsAmt;
		this.pchsDfrmDt = pchsDfrmDt;
		this.intExchFrqcDvsnCd = intExchFrqcDvsnCd;
		this.dfrmSwapIntDvsnCd = dfrmSwapIntDvsnCd;
		this.rcivSwapIntDvsnCd = rcivSwapIntDvsnCd;
		this.ofbdDrvSttlTypeCd = ofbdDrvSttlTypeCd;
		this.crcyCd = crcyCd;
		this.fxDecsDt = fxDecsDt;
		this.lmtImpsRt = lmtImpsRt;
		this.trOppnLmtAmt = trOppnLmtAmt;
		this.lmtUseAmt = lmtUseAmt;
		this.ctrtDt = ctrtDt;
		this.asstEvluAmt = asstEvluAmt;
		this.asstEvluPrftAmt = asstEvluPrftAmt;
		this.asstEvluLossAmt = asstEvluLossAmt;
		this.debtEvluAmt = debtEvluAmt;
		this.debtEvluPrftAmt = debtEvluPrftAmt;
		this.debtEvluLossAmt = debtEvluLossAmt;
		this.asstAbks = asstAbks;
		this.asstFee = asstFee;
		this.debtAbks = debtAbks;
		this.debtFee = debtFee;
		this.asstAcbkUnpr = asstAcbkUnpr;
		this.asstEvluUnpr = asstEvluUnpr;
		this.debtAcbkUnpr = debtAcbkUnpr;
		this.debtEvluUnpr = debtEvluUnpr;
		this.asstBgtQty = asstBgtQty;
		this.asstBgtAbks = asstBgtAbks;
		this.asstEvluBassUnpr = asstEvluBassUnpr;
		this.asstAdjtCefc = asstAdjtCefc;
		this.debtBgtQty = debtBgtQty;
		this.debtBgtAbks = debtBgtAbks;
		this.debtEvluBassUnpr = debtEvluBassUnpr;
		this.debtAdjtCefc = debtAdjtCefc;
		this.ofbdDrvActpDvsnCd = ofbdDrvActpDvsnCd;
		this.rdptYn = rdptYn;
		this.actgRfltYn = actgRfltYn;
		this.swapPremAcmlRpchAmt = swapPremAcmlRpchAmt;
		this.fee = fee;
		this.utlzFundCd = utlzFundCd;
		this.elsPchsObjtTypeCd = elsPchsObjtTypeCd;
		this.intCalcDt = intCalcDt;
		this.dfrmIntRtEtcRt = dfrmIntRtEtcRt;
		this.dfrmIntRtEtcText = dfrmIntRtEtcText;
		this.rcivIntRtEtcRt = rcivIntRtEtcRt;
		this.rcivIntRtEtcText = rcivIntRtEtcText;
		this.frstMrgnCrcyCd = frstMrgnCrcyCd;
		this.frstMrgnRt = frstMrgnRt;
		this.frstMrgnAmt = frstMrgnAmt;
		this.csaAplyYn = csaAplyYn;
		this.trOppnRefText = trOppnRefText;
		this.asstTrDt = asstTrDt;
		this.asstExpdDt = asstExpdDt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.ofbdDrvEvluMthdCd = ofbdDrvEvluMthdCd;
		this.imncBondDscmNo = imncBondDscmNo;
		this.imncBondBssEvluUnpr = imncBondBssEvluUnpr;
		this.swapIntCalcDcntDvsnCd = swapIntCalcDcntDvsnCd;
		this.swapIntCalcDcntDtlCd = swapIntCalcDcntDtlCd;
		this.swapIntCalcMthdCd = swapIntCalcMthdCd;
		this.debtAcmlSrdpAmt = debtAcmlSrdpAmt;
		this.debtAcmlSrdpQty = debtAcmlSrdpQty;
		this.asstAcmlSrdpParAmt = asstAcmlSrdpParAmt;
		this.asstAcmlSrdpTrAmt = asstAcmlSrdpTrAmt;
		this.asstAcmlSrdpQty = asstAcmlSrdpQty;
		this.swapPremAcmlSrdpAmt = swapPremAcmlSrdpAmt;
		this.elsPchsPrdtDscmNo = elsPchsPrdtDscmNo;
		this.elsPchsPrdtName = elsPchsPrdtName;
		this.elsPchsSameItemYn = elsPchsSameItemYn;
		this.elsPchsSamePdno = elsPchsSamePdno;
		this.elsPchsSamePrdtTypeCd = elsPchsSamePrdtTypeCd;
		this.rcivIntExchFrqcDvsnCd = rcivIntExchFrqcDvsnCd;
		this.elsPcstlDfrmRcivDvsnCd = elsPcstlDfrmRcivDvsnCd;
		this.elsPcstlDt = elsPcstlDt;
		this.debtBgtSrdpQty = debtBgtSrdpQty;
		this.asstBgtSrdpQty = asstBgtSrdpQty;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "trOppnNo", column = @Column(name = "TR_OPPN_NO", nullable = false, length = 12)),
			@AttributeOverride(name = "elsTrDtldTypeCd", column = @Column(name = "ELS_TR_DTLD_TYPE_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "issuTmod", column = @Column(name = "ISSU_TMOD", nullable = false, precision = 9, scale = 0)) })
	public Ivot015p0Id getId() {
		return this.id;
	}

	public void setId(Ivot015p0Id id) {
		this.id = id;
	}

	
	@ManyToOne
	@JoinColumn(name="PDNO", insertable=false, updatable=false)
	public Pdif004m0 getElsMaster() {
		return elsMaster;
	}

	public void setElsMaster(Pdif004m0 elsMaster) {
		this.elsMaster = elsMaster;
	}

	@Column(name = "ERLM_DT", length = 8)
	public String getErlmDt() {
		return this.erlmDt;
	}

	public void setErlmDt(String erlmDt) {
		this.erlmDt = erlmDt;
	}

	@Column(name = "DEBT_TR_PAR_QTY", precision = 18, scale = 0)
	public Long getDebtTrParQty() {
		return this.debtTrParQty;
	}

	public void setDebtTrParQty(Long debtTrParQty) {
		this.debtTrParQty = debtTrParQty;
	}

	@Column(name = "DEBT_TR_PAR_AMT", precision = 18, scale = 0)
	public Long getDebtTrParAmt() {
		return this.debtTrParAmt;
	}

	public void setDebtTrParAmt(Long debtTrParAmt) {
		this.debtTrParAmt = debtTrParAmt;
	}

	@Column(name = "DEBT_TR_PYMT_AMT", precision = 18, scale = 0)
	public Long getDebtTrPymtAmt() {
		return this.debtTrPymtAmt;
	}

	public void setDebtTrPymtAmt(Long debtTrPymtAmt) {
		this.debtTrPymtAmt = debtTrPymtAmt;
	}

	@Column(name = "DEBT_TR_PYMT_QTY", precision = 18, scale = 0)
	public Long getDebtTrPymtQty() {
		return this.debtTrPymtQty;
	}

	public void setDebtTrPymtQty(Long debtTrPymtQty) {
		this.debtTrPymtQty = debtTrPymtQty;
	}

	@Column(name = "DEBT_ACML_RPCH_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlRpchAmt() {
		return this.debtAcmlRpchAmt;
	}

	public void setDebtAcmlRpchAmt(Long debtAcmlRpchAmt) {
		this.debtAcmlRpchAmt = debtAcmlRpchAmt;
	}

	@Column(name = "DEBT_ACML_RPCH_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlRpchQty() {
		return this.debtAcmlRpchQty;
	}

	public void setDebtAcmlRpchQty(Long debtAcmlRpchQty) {
		this.debtAcmlRpchQty = debtAcmlRpchQty;
	}

	@Column(name = "DEBT_ACML_RPCH_RBUY_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlRpchRbuyAmt() {
		return this.debtAcmlRpchRbuyAmt;
	}

	public void setDebtAcmlRpchRbuyAmt(Long debtAcmlRpchRbuyAmt) {
		this.debtAcmlRpchRbuyAmt = debtAcmlRpchRbuyAmt;
	}

	@Column(name = "DEBT_ACML_RPCH_RBUY_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlRpchRbuyQty() {
		return this.debtAcmlRpchRbuyQty;
	}

	public void setDebtAcmlRpchRbuyQty(Long debtAcmlRpchRbuyQty) {
		this.debtAcmlRpchRbuyQty = debtAcmlRpchRbuyQty;
	}

	@Column(name = "CBLC_AMT", precision = 18, scale = 0)
	public Long getCblcAmt() {
		return this.cblcAmt;
	}

	public void setCblcAmt(Long cblcAmt) {
		this.cblcAmt = cblcAmt;
	}

	@Column(name = "CBLC_QTY", precision = 18, scale = 0)
	public Long getCblcQty() {
		return this.cblcQty;
	}

	public void setCblcQty(Long cblcQty) {
		this.cblcQty = cblcQty;
	}

	@Column(name = "ASST_TR_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstTrParAmt() {
		return this.asstTrParAmt;
	}

	public void setAsstTrParAmt(Long asstTrParAmt) {
		this.asstTrParAmt = asstTrParAmt;
	}

	@Column(name = "ELS_PCHS_QTY", precision = 18, scale = 0)
	public Long getElsPchsQty() {
		return this.elsPchsQty;
	}

	public void setElsPchsQty(Long elsPchsQty) {
		this.elsPchsQty = elsPchsQty;
	}

	@Column(name = "ELS_PAR_AMT", precision = 18, scale = 5)
	public BigDecimal getElsParAmt() {
		return this.elsParAmt;
	}

	public void setElsParAmt(BigDecimal elsParAmt) {
		this.elsParAmt = elsParAmt;
	}

	@Column(name = "ELS_PCHS_UNPR", precision = 21, scale = 8)
	public BigDecimal getElsPchsUnpr() {
		return this.elsPchsUnpr;
	}

	public void setElsPchsUnpr(BigDecimal elsPchsUnpr) {
		this.elsPchsUnpr = elsPchsUnpr;
	}

	@Column(name = "DSGN_PCHS_UNPR", precision = 21, scale = 8)
	public BigDecimal getDsgnPchsUnpr() {
		return this.dsgnPchsUnpr;
	}

	public void setDsgnPchsUnpr(BigDecimal dsgnPchsUnpr) {
		this.dsgnPchsUnpr = dsgnPchsUnpr;
	}

	@Column(name = "ASST_ACML_RPCH_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlRpchParAmt() {
		return this.asstAcmlRpchParAmt;
	}

	public void setAsstAcmlRpchParAmt(Long asstAcmlRpchParAmt) {
		this.asstAcmlRpchParAmt = asstAcmlRpchParAmt;
	}

	@Column(name = "ASST_ACML_RPCH_TR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlRpchTrAmt() {
		return this.asstAcmlRpchTrAmt;
	}

	public void setAsstAcmlRpchTrAmt(Long asstAcmlRpchTrAmt) {
		this.asstAcmlRpchTrAmt = asstAcmlRpchTrAmt;
	}

	@Column(name = "ASST_ACML_RPCH_QTY", precision = 18, scale = 0)
	public Long getAsstAcmlRpchQty() {
		return this.asstAcmlRpchQty;
	}

	public void setAsstAcmlRpchQty(Long asstAcmlRpchQty) {
		this.asstAcmlRpchQty = asstAcmlRpchQty;
	}

	@Column(name = "ASST_CBLC_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstCblcParAmt() {
		return this.asstCblcParAmt;
	}

	public void setAsstCblcParAmt(Long asstCblcParAmt) {
		this.asstCblcParAmt = asstCblcParAmt;
	}

	@Column(name = "ASST_CBLC_TR_AMT", precision = 18, scale = 0)
	public Long getAsstCblcTrAmt() {
		return this.asstCblcTrAmt;
	}

	public void setAsstCblcTrAmt(Long asstCblcTrAmt) {
		this.asstCblcTrAmt = asstCblcTrAmt;
	}

	@Column(name = "ASST_CBLC_QTY", precision = 18, scale = 0)
	public Long getAsstCblcQty() {
		return this.asstCblcQty;
	}

	public void setAsstCblcQty(Long asstCblcQty) {
		this.asstCblcQty = asstCblcQty;
	}

	@Column(name = "UTLZ_FUND_PRCA_ASRC_RT", precision = 18, scale = 10)
	public BigDecimal getUtlzFundPrcaAsrcRt() {
		return this.utlzFundPrcaAsrcRt;
	}

	public void setUtlzFundPrcaAsrcRt(BigDecimal utlzFundPrcaAsrcRt) {
		this.utlzFundPrcaAsrcRt = utlzFundPrcaAsrcRt;
	}

	@Column(name = "DSCT_INRT", precision = 18, scale = 10)
	public BigDecimal getDsctInrt() {
		return this.dsctInrt;
	}

	public void setDsctInrt(BigDecimal dsctInrt) {
		this.dsctInrt = dsctInrt;
	}

	@Column(name = "BOND_ADMS_AMT", precision = 18, scale = 0)
	public Long getBondAdmsAmt() {
		return this.bondAdmsAmt;
	}

	public void setBondAdmsAmt(Long bondAdmsAmt) {
		this.bondAdmsAmt = bondAdmsAmt;
	}

	@Column(name = "BOND_ADMS_RT", precision = 18, scale = 10)
	public BigDecimal getBondAdmsRt() {
		return this.bondAdmsRt;
	}

	public void setBondAdmsRt(BigDecimal bondAdmsRt) {
		this.bondAdmsRt = bondAdmsRt;
	}

	@Column(name = "OPT_ADMS_AMT", precision = 18, scale = 0)
	public Long getOptAdmsAmt() {
		return this.optAdmsAmt;
	}

	public void setOptAdmsAmt(Long optAdmsAmt) {
		this.optAdmsAmt = optAdmsAmt;
	}

	@Column(name = "OPT_ADMS_RT", precision = 18, scale = 10)
	public BigDecimal getOptAdmsRt() {
		return this.optAdmsRt;
	}

	public void setOptAdmsRt(BigDecimal optAdmsRt) {
		this.optAdmsRt = optAdmsRt;
	}

	@Column(name = "OPT_PTCI_RT", precision = 18, scale = 10)
	public BigDecimal getOptPtciRt() {
		return this.optPtciRt;
	}

	public void setOptPtciRt(BigDecimal optPtciRt) {
		this.optPtciRt = optPtciRt;
	}

	@Column(name = "OPT_PTCI_RT_YN", length = 1)
	public String getOptPtciRtYn() {
		return this.optPtciRtYn;
	}

	public void setOptPtciRtYn(String optPtciRtYn) {
		this.optPtciRtYn = optPtciRtYn;
	}

	@Column(name = "DSGN_PCST_RT", precision = 18, scale = 10)
	public BigDecimal getDsgnPcstRt() {
		return this.dsgnPcstRt;
	}

	public void setDsgnPcstRt(BigDecimal dsgnPcstRt) {
		this.dsgnPcstRt = dsgnPcstRt;
	}

	@Column(name = "DSGN_PCST_AMT", precision = 18, scale = 0)
	public Long getDsgnPcstAmt() {
		return this.dsgnPcstAmt;
	}

	public void setDsgnPcstAmt(Long dsgnPcstAmt) {
		this.dsgnPcstAmt = dsgnPcstAmt;
	}

	@Column(name = "DSGN_FEE_RT", precision = 18, scale = 10)
	public BigDecimal getDsgnFeeRt() {
		return this.dsgnFeeRt;
	}

	public void setDsgnFeeRt(BigDecimal dsgnFeeRt) {
		this.dsgnFeeRt = dsgnFeeRt;
	}

	@Column(name = "DSGN_FEE_AMT", precision = 18, scale = 0)
	public Long getDsgnFeeAmt() {
		return this.dsgnFeeAmt;
	}

	public void setDsgnFeeAmt(Long dsgnFeeAmt) {
		this.dsgnFeeAmt = dsgnFeeAmt;
	}

	@Column(name = "SWAP_PREM_DVSN_CD", length = 2)
	public String getSwapPremDvsnCd() {
		return this.swapPremDvsnCd;
	}

	public void setSwapPremDvsnCd(String swapPremDvsnCd) {
		this.swapPremDvsnCd = swapPremDvsnCd;
	}

	@Column(name = "SWAP_PREM_RT", precision = 18, scale = 10)
	public BigDecimal getSwapPremRt() {
		return this.swapPremRt;
	}

	public void setSwapPremRt(BigDecimal swapPremRt) {
		this.swapPremRt = swapPremRt;
	}

	@Column(name = "SWAP_PREM_AMT", precision = 18, scale = 0)
	public Long getSwapPremAmt() {
		return this.swapPremAmt;
	}

	public void setSwapPremAmt(Long swapPremAmt) {
		this.swapPremAmt = swapPremAmt;
	}

	@Column(name = "SWAP_PREM_PRCS_DT", length = 8)
	public String getSwapPremPrcsDt() {
		return this.swapPremPrcsDt;
	}

	public void setSwapPremPrcsDt(String swapPremPrcsDt) {
		this.swapPremPrcsDt = swapPremPrcsDt;
	}

	@Column(name = "IV_CRDT_GRAD_CD", length = 4)
	public String getIvCrdtGradCd() {
		return this.ivCrdtGradCd;
	}

	public void setIvCrdtGradCd(String ivCrdtGradCd) {
		this.ivCrdtGradCd = ivCrdtGradCd;
	}

	@Column(name = "EVLU_DSCT_INTR", precision = 21, scale = 8)
	public BigDecimal getEvluDsctIntr() {
		return this.evluDsctIntr;
	}

	public void setEvluDsctIntr(BigDecimal evluDsctIntr) {
		this.evluDsctIntr = evluDsctIntr;
	}

	@Column(name = "BOND_EVLU_AMT", precision = 18, scale = 0)
	public Long getBondEvluAmt() {
		return this.bondEvluAmt;
	}

	public void setBondEvluAmt(Long bondEvluAmt) {
		this.bondEvluAmt = bondEvluAmt;
	}

	@Column(name = "OPT_EVLU_AMT", precision = 18, scale = 0)
	public Long getOptEvluAmt() {
		return this.optEvluAmt;
	}

	public void setOptEvluAmt(Long optEvluAmt) {
		this.optEvluAmt = optEvluAmt;
	}

	@Column(name = "OPT_PCHS_AMT", precision = 18, scale = 0)
	public Long getOptPchsAmt() {
		return this.optPchsAmt;
	}

	public void setOptPchsAmt(Long optPchsAmt) {
		this.optPchsAmt = optPchsAmt;
	}

	@Column(name = "OPT_PCHS_DFRM_DT", length = 8)
	public String getOptPchsDfrmDt() {
		return this.optPchsDfrmDt;
	}

	public void setOptPchsDfrmDt(String optPchsDfrmDt) {
		this.optPchsDfrmDt = optPchsDfrmDt;
	}

	@Column(name = "BOND_OPT_EVLU_PCHS_AMT", precision = 18, scale = 0)
	public Long getBondOptEvluPchsAmt() {
		return this.bondOptEvluPchsAmt;
	}

	public void setBondOptEvluPchsAmt(Long bondOptEvluPchsAmt) {
		this.bondOptEvluPchsAmt = bondOptEvluPchsAmt;
	}

	@Column(name = "BOND_OPT_EVLU_PCHS_RT", precision = 18, scale = 10)
	public BigDecimal getBondOptEvluPchsRt() {
		return this.bondOptEvluPchsRt;
	}

	public void setBondOptEvluPchsRt(BigDecimal bondOptEvluPchsRt) {
		this.bondOptEvluPchsRt = bondOptEvluPchsRt;
	}

	@Column(name = "ELS_EVLU_RT", precision = 18, scale = 10)
	public BigDecimal getElsEvluRt() {
		return this.elsEvluRt;
	}

	public void setElsEvluRt(BigDecimal elsEvluRt) {
		this.elsEvluRt = elsEvluRt;
	}

	@Column(name = "ELS_EVLU_AMT", precision = 18, scale = 0)
	public Long getElsEvluAmt() {
		return this.elsEvluAmt;
	}

	public void setElsEvluAmt(Long elsEvluAmt) {
		this.elsEvluAmt = elsEvluAmt;
	}

	@Column(name = "ELS_PCHS_RT", precision = 18, scale = 10)
	public BigDecimal getElsPchsRt() {
		return this.elsPchsRt;
	}

	public void setElsPchsRt(BigDecimal elsPchsRt) {
		this.elsPchsRt = elsPchsRt;
	}

	@Column(name = "ELS_PCHS_AMT", precision = 18, scale = 0)
	public Long getElsPchsAmt() {
		return this.elsPchsAmt;
	}

	public void setElsPchsAmt(Long elsPchsAmt) {
		this.elsPchsAmt = elsPchsAmt;
	}

	@Column(name = "PCHS_DFRM_DT", length = 8)
	public String getPchsDfrmDt() {
		return this.pchsDfrmDt;
	}

	public void setPchsDfrmDt(String pchsDfrmDt) {
		this.pchsDfrmDt = pchsDfrmDt;
	}

	@Column(name = "INT_EXCH_FRQC_DVSN_CD", length = 2)
	public String getIntExchFrqcDvsnCd() {
		return this.intExchFrqcDvsnCd;
	}

	public void setIntExchFrqcDvsnCd(String intExchFrqcDvsnCd) {
		this.intExchFrqcDvsnCd = intExchFrqcDvsnCd;
	}

	@Column(name = "DFRM_SWAP_INT_DVSN_CD", length = 2)
	public String getDfrmSwapIntDvsnCd() {
		return this.dfrmSwapIntDvsnCd;
	}

	public void setDfrmSwapIntDvsnCd(String dfrmSwapIntDvsnCd) {
		this.dfrmSwapIntDvsnCd = dfrmSwapIntDvsnCd;
	}

	@Column(name = "RCIV_SWAP_INT_DVSN_CD", length = 2)
	public String getRcivSwapIntDvsnCd() {
		return this.rcivSwapIntDvsnCd;
	}

	public void setRcivSwapIntDvsnCd(String rcivSwapIntDvsnCd) {
		this.rcivSwapIntDvsnCd = rcivSwapIntDvsnCd;
	}

	@Column(name = "OFBD_DRV_STTL_TYPE_CD", length = 2)
	public String getOfbdDrvSttlTypeCd() {
		return this.ofbdDrvSttlTypeCd;
	}

	public void setOfbdDrvSttlTypeCd(String ofbdDrvSttlTypeCd) {
		this.ofbdDrvSttlTypeCd = ofbdDrvSttlTypeCd;
	}

	@Column(name = "CRCY_CD", length = 3)
	public String getCrcyCd() {
		return this.crcyCd;
	}

	public void setCrcyCd(String crcyCd) {
		this.crcyCd = crcyCd;
	}

	@Column(name = "FX_DECS_DT", length = 8)
	public String getFxDecsDt() {
		return this.fxDecsDt;
	}

	public void setFxDecsDt(String fxDecsDt) {
		this.fxDecsDt = fxDecsDt;
	}

	@Column(name = "LMT_IMPS_RT", precision = 18, scale = 10)
	public BigDecimal getLmtImpsRt() {
		return this.lmtImpsRt;
	}

	public void setLmtImpsRt(BigDecimal lmtImpsRt) {
		this.lmtImpsRt = lmtImpsRt;
	}

	@Column(name = "TR_OPPN_LMT_AMT", precision = 18, scale = 0)
	public Long getTrOppnLmtAmt() {
		return this.trOppnLmtAmt;
	}

	public void setTrOppnLmtAmt(Long trOppnLmtAmt) {
		this.trOppnLmtAmt = trOppnLmtAmt;
	}

	@Column(name = "LMT_USE_AMT", precision = 18, scale = 0)
	public Long getLmtUseAmt() {
		return this.lmtUseAmt;
	}

	public void setLmtUseAmt(Long lmtUseAmt) {
		this.lmtUseAmt = lmtUseAmt;
	}

	@Column(name = "CTRT_DT", length = 8)
	public String getCtrtDt() {
		return this.ctrtDt;
	}

	public void setCtrtDt(String ctrtDt) {
		this.ctrtDt = ctrtDt;
	}

	@Column(name = "ASST_EVLU_AMT", precision = 18, scale = 0)
	public Long getAsstEvluAmt() {
		return this.asstEvluAmt;
	}

	public void setAsstEvluAmt(Long asstEvluAmt) {
		this.asstEvluAmt = asstEvluAmt;
	}

	@Column(name = "ASST_EVLU_PRFT_AMT", precision = 18, scale = 0)
	public Long getAsstEvluPrftAmt() {
		return this.asstEvluPrftAmt;
	}

	public void setAsstEvluPrftAmt(Long asstEvluPrftAmt) {
		this.asstEvluPrftAmt = asstEvluPrftAmt;
	}

	@Column(name = "ASST_EVLU_LOSS_AMT", precision = 18, scale = 0)
	public Long getAsstEvluLossAmt() {
		return this.asstEvluLossAmt;
	}

	public void setAsstEvluLossAmt(Long asstEvluLossAmt) {
		this.asstEvluLossAmt = asstEvluLossAmt;
	}

	@Column(name = "DEBT_EVLU_AMT", precision = 18, scale = 0)
	public Long getDebtEvluAmt() {
		return this.debtEvluAmt;
	}

	public void setDebtEvluAmt(Long debtEvluAmt) {
		this.debtEvluAmt = debtEvluAmt;
	}

	@Column(name = "DEBT_EVLU_PRFT_AMT", precision = 18, scale = 0)
	public Long getDebtEvluPrftAmt() {
		return this.debtEvluPrftAmt;
	}

	public void setDebtEvluPrftAmt(Long debtEvluPrftAmt) {
		this.debtEvluPrftAmt = debtEvluPrftAmt;
	}

	@Column(name = "DEBT_EVLU_LOSS_AMT", precision = 18, scale = 0)
	public Long getDebtEvluLossAmt() {
		return this.debtEvluLossAmt;
	}

	public void setDebtEvluLossAmt(Long debtEvluLossAmt) {
		this.debtEvluLossAmt = debtEvluLossAmt;
	}

	@Column(name = "ASST_ABKS", precision = 18, scale = 0)
	public Long getAsstAbks() {
		return this.asstAbks;
	}

	public void setAsstAbks(Long asstAbks) {
		this.asstAbks = asstAbks;
	}

	@Column(name = "ASST_FEE", precision = 18, scale = 0)
	public Long getAsstFee() {
		return this.asstFee;
	}

	public void setAsstFee(Long asstFee) {
		this.asstFee = asstFee;
	}

	@Column(name = "DEBT_ABKS", precision = 18, scale = 0)
	public Long getDebtAbks() {
		return this.debtAbks;
	}

	public void setDebtAbks(Long debtAbks) {
		this.debtAbks = debtAbks;
	}

	@Column(name = "DEBT_FEE", precision = 18, scale = 0)
	public Long getDebtFee() {
		return this.debtFee;
	}

	public void setDebtFee(Long debtFee) {
		this.debtFee = debtFee;
	}

	@Column(name = "ASST_ACBK_UNPR", precision = 21, scale = 8)
	public BigDecimal getAsstAcbkUnpr() {
		return this.asstAcbkUnpr;
	}

	public void setAsstAcbkUnpr(BigDecimal asstAcbkUnpr) {
		this.asstAcbkUnpr = asstAcbkUnpr;
	}

	@Column(name = "ASST_EVLU_UNPR", precision = 21, scale = 8)
	public BigDecimal getAsstEvluUnpr() {
		return this.asstEvluUnpr;
	}

	public void setAsstEvluUnpr(BigDecimal asstEvluUnpr) {
		this.asstEvluUnpr = asstEvluUnpr;
	}

	@Column(name = "DEBT_ACBK_UNPR", precision = 21, scale = 8)
	public BigDecimal getDebtAcbkUnpr() {
		return this.debtAcbkUnpr;
	}

	public void setDebtAcbkUnpr(BigDecimal debtAcbkUnpr) {
		this.debtAcbkUnpr = debtAcbkUnpr;
	}

	@Column(name = "DEBT_EVLU_UNPR", precision = 21, scale = 8)
	public BigDecimal getDebtEvluUnpr() {
		return this.debtEvluUnpr;
	}

	public void setDebtEvluUnpr(BigDecimal debtEvluUnpr) {
		this.debtEvluUnpr = debtEvluUnpr;
	}

	@Column(name = "ASST_BGT_QTY", precision = 18, scale = 0)
	public Long getAsstBgtQty() {
		return this.asstBgtQty;
	}

	public void setAsstBgtQty(Long asstBgtQty) {
		this.asstBgtQty = asstBgtQty;
	}

	@Column(name = "ASST_BGT_ABKS", precision = 18, scale = 0)
	public Long getAsstBgtAbks() {
		return this.asstBgtAbks;
	}

	public void setAsstBgtAbks(Long asstBgtAbks) {
		this.asstBgtAbks = asstBgtAbks;
	}

	@Column(name = "ASST_EVLU_BASS_UNPR", precision = 23, scale = 15)
	public BigDecimal getAsstEvluBassUnpr() {
		return this.asstEvluBassUnpr;
	}

	public void setAsstEvluBassUnpr(BigDecimal asstEvluBassUnpr) {
		this.asstEvluBassUnpr = asstEvluBassUnpr;
	}

	@Column(name = "ASST_ADJT_CEFC", precision = 23, scale = 15)
	public BigDecimal getAsstAdjtCefc() {
		return this.asstAdjtCefc;
	}

	public void setAsstAdjtCefc(BigDecimal asstAdjtCefc) {
		this.asstAdjtCefc = asstAdjtCefc;
	}

	@Column(name = "DEBT_BGT_QTY", precision = 18, scale = 0)
	public Long getDebtBgtQty() {
		return this.debtBgtQty;
	}

	public void setDebtBgtQty(Long debtBgtQty) {
		this.debtBgtQty = debtBgtQty;
	}

	@Column(name = "DEBT_BGT_ABKS", precision = 18, scale = 0)
	public Long getDebtBgtAbks() {
		return this.debtBgtAbks;
	}

	public void setDebtBgtAbks(Long debtBgtAbks) {
		this.debtBgtAbks = debtBgtAbks;
	}

	@Column(name = "DEBT_EVLU_BASS_UNPR", precision = 23, scale = 15)
	public BigDecimal getDebtEvluBassUnpr() {
		return this.debtEvluBassUnpr;
	}

	public void setDebtEvluBassUnpr(BigDecimal debtEvluBassUnpr) {
		this.debtEvluBassUnpr = debtEvluBassUnpr;
	}

	@Column(name = "DEBT_ADJT_CEFC", precision = 23, scale = 15)
	public BigDecimal getDebtAdjtCefc() {
		return this.debtAdjtCefc;
	}

	public void setDebtAdjtCefc(BigDecimal debtAdjtCefc) {
		this.debtAdjtCefc = debtAdjtCefc;
	}

	@Column(name = "OFBD_DRV_ACTP_DVSN_CD", length = 2)
	public String getOfbdDrvActpDvsnCd() {
		return this.ofbdDrvActpDvsnCd;
	}

	public void setOfbdDrvActpDvsnCd(String ofbdDrvActpDvsnCd) {
		this.ofbdDrvActpDvsnCd = ofbdDrvActpDvsnCd;
	}

	@Column(name = "RDPT_YN", length = 1)
	public String getRdptYn() {
		return this.rdptYn;
	}

	public void setRdptYn(String rdptYn) {
		this.rdptYn = rdptYn;
	}

	@Column(name = "ACTG_RFLT_YN", length = 1)
	public String getActgRfltYn() {
		return this.actgRfltYn;
	}

	public void setActgRfltYn(String actgRfltYn) {
		this.actgRfltYn = actgRfltYn;
	}

	@Column(name = "SWAP_PREM_ACML_RPCH_AMT", precision = 18, scale = 0)
	public Long getSwapPremAcmlRpchAmt() {
		return this.swapPremAcmlRpchAmt;
	}

	public void setSwapPremAcmlRpchAmt(Long swapPremAcmlRpchAmt) {
		this.swapPremAcmlRpchAmt = swapPremAcmlRpchAmt;
	}

	@Column(name = "FEE", precision = 18, scale = 0)
	public Long getFee() {
		return this.fee;
	}

	public void setFee(Long fee) {
		this.fee = fee;
	}

	@Column(name = "UTLZ_FUND_CD", length = 8)
	public String getUtlzFundCd() {
		return this.utlzFundCd;
	}

	public void setUtlzFundCd(String utlzFundCd) {
		this.utlzFundCd = utlzFundCd;
	}

	@Column(name = "ELS_PCHS_OBJT_TYPE_CD", length = 2)
	public String getElsPchsObjtTypeCd() {
		return this.elsPchsObjtTypeCd;
	}

	public void setElsPchsObjtTypeCd(String elsPchsObjtTypeCd) {
		this.elsPchsObjtTypeCd = elsPchsObjtTypeCd;
	}

	@Column(name = "INT_CALC_DT", length = 8)
	public String getIntCalcDt() {
		return this.intCalcDt;
	}

	public void setIntCalcDt(String intCalcDt) {
		this.intCalcDt = intCalcDt;
	}

	@Column(name = "DFRM_INT_RT_ETC_RT", precision = 18, scale = 10)
	public BigDecimal getDfrmIntRtEtcRt() {
		return this.dfrmIntRtEtcRt;
	}

	public void setDfrmIntRtEtcRt(BigDecimal dfrmIntRtEtcRt) {
		this.dfrmIntRtEtcRt = dfrmIntRtEtcRt;
	}

	@Column(name = "DFRM_INT_RT_ETC_TEXT", length = 500)
	public String getDfrmIntRtEtcText() {
		return this.dfrmIntRtEtcText;
	}

	public void setDfrmIntRtEtcText(String dfrmIntRtEtcText) {
		this.dfrmIntRtEtcText = dfrmIntRtEtcText;
	}

	@Column(name = "RCIV_INT_RT_ETC_RT", precision = 18, scale = 10)
	public BigDecimal getRcivIntRtEtcRt() {
		return this.rcivIntRtEtcRt;
	}

	public void setRcivIntRtEtcRt(BigDecimal rcivIntRtEtcRt) {
		this.rcivIntRtEtcRt = rcivIntRtEtcRt;
	}

	@Column(name = "RCIV_INT_RT_ETC_TEXT", length = 500)
	public String getRcivIntRtEtcText() {
		return this.rcivIntRtEtcText;
	}

	public void setRcivIntRtEtcText(String rcivIntRtEtcText) {
		this.rcivIntRtEtcText = rcivIntRtEtcText;
	}

	@Column(name = "FRST_MRGN_CRCY_CD", length = 3)
	public String getFrstMrgnCrcyCd() {
		return this.frstMrgnCrcyCd;
	}

	public void setFrstMrgnCrcyCd(String frstMrgnCrcyCd) {
		this.frstMrgnCrcyCd = frstMrgnCrcyCd;
	}

	@Column(name = "FRST_MRGN_RT", precision = 18, scale = 10)
	public BigDecimal getFrstMrgnRt() {
		return this.frstMrgnRt;
	}

	public void setFrstMrgnRt(BigDecimal frstMrgnRt) {
		this.frstMrgnRt = frstMrgnRt;
	}

	@Column(name = "FRST_MRGN_AMT", precision = 18, scale = 0)
	public Long getFrstMrgnAmt() {
		return this.frstMrgnAmt;
	}

	public void setFrstMrgnAmt(Long frstMrgnAmt) {
		this.frstMrgnAmt = frstMrgnAmt;
	}

	@Column(name = "CSA_APLY_YN", length = 1)
	public String getCsaAplyYn() {
		return this.csaAplyYn;
	}

	public void setCsaAplyYn(String csaAplyYn) {
		this.csaAplyYn = csaAplyYn;
	}

	@Column(name = "TR_OPPN_REF_TEXT", length = 500)
	public String getTrOppnRefText() {
		return this.trOppnRefText;
	}

	public void setTrOppnRefText(String trOppnRefText) {
		this.trOppnRefText = trOppnRefText;
	}

	@Column(name = "ASST_TR_DT", length = 8)
	public String getAsstTrDt() {
		return this.asstTrDt;
	}

	public void setAsstTrDt(String asstTrDt) {
		this.asstTrDt = asstTrDt;
	}

	@Column(name = "ASST_EXPD_DT", length = 8)
	public String getAsstExpdDt() {
		return this.asstExpdDt;
	}

	public void setAsstExpdDt(String asstExpdDt) {
		this.asstExpdDt = asstExpdDt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "OFBD_DRV_EVLU_MTHD_CD", length = 2)
	public String getOfbdDrvEvluMthdCd() {
		return this.ofbdDrvEvluMthdCd;
	}

	public void setOfbdDrvEvluMthdCd(String ofbdDrvEvluMthdCd) {
		this.ofbdDrvEvluMthdCd = ofbdDrvEvluMthdCd;
	}

	@Column(name = "IMNC_BOND_DSCM_NO", length = 3)
	public String getImncBondDscmNo() {
		return this.imncBondDscmNo;
	}

	public void setImncBondDscmNo(String imncBondDscmNo) {
		this.imncBondDscmNo = imncBondDscmNo;
	}

	@Column(name = "IMNC_BOND_BSS_EVLU_UNPR", precision = 23, scale = 15)
	public BigDecimal getImncBondBssEvluUnpr() {
		return this.imncBondBssEvluUnpr;
	}

	public void setImncBondBssEvluUnpr(BigDecimal imncBondBssEvluUnpr) {
		this.imncBondBssEvluUnpr = imncBondBssEvluUnpr;
	}

	@Column(name = "SWAP_INT_CALC_DCNT_DVSN_CD", length = 2)
	public String getSwapIntCalcDcntDvsnCd() {
		return this.swapIntCalcDcntDvsnCd;
	}

	public void setSwapIntCalcDcntDvsnCd(String swapIntCalcDcntDvsnCd) {
		this.swapIntCalcDcntDvsnCd = swapIntCalcDcntDvsnCd;
	}

	@Column(name = "SWAP_INT_CALC_DCNT_DTL_CD", length = 2)
	public String getSwapIntCalcDcntDtlCd() {
		return this.swapIntCalcDcntDtlCd;
	}

	public void setSwapIntCalcDcntDtlCd(String swapIntCalcDcntDtlCd) {
		this.swapIntCalcDcntDtlCd = swapIntCalcDcntDtlCd;
	}

	@Column(name = "SWAP_INT_CALC_MTHD_CD", length = 2)
	public String getSwapIntCalcMthdCd() {
		return this.swapIntCalcMthdCd;
	}

	public void setSwapIntCalcMthdCd(String swapIntCalcMthdCd) {
		this.swapIntCalcMthdCd = swapIntCalcMthdCd;
	}

	@Column(name = "DEBT_ACML_SRDP_AMT", precision = 18, scale = 0)
	public Long getDebtAcmlSrdpAmt() {
		return this.debtAcmlSrdpAmt;
	}

	public void setDebtAcmlSrdpAmt(Long debtAcmlSrdpAmt) {
		this.debtAcmlSrdpAmt = debtAcmlSrdpAmt;
	}

	@Column(name = "DEBT_ACML_SRDP_QTY", precision = 18, scale = 0)
	public Long getDebtAcmlSrdpQty() {
		return this.debtAcmlSrdpQty;
	}

	public void setDebtAcmlSrdpQty(Long debtAcmlSrdpQty) {
		this.debtAcmlSrdpQty = debtAcmlSrdpQty;
	}

	@Column(name = "ASST_ACML_SRDP_PAR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpParAmt() {
		return this.asstAcmlSrdpParAmt;
	}

	public void setAsstAcmlSrdpParAmt(Long asstAcmlSrdpParAmt) {
		this.asstAcmlSrdpParAmt = asstAcmlSrdpParAmt;
	}

	@Column(name = "ASST_ACML_SRDP_TR_AMT", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpTrAmt() {
		return this.asstAcmlSrdpTrAmt;
	}

	public void setAsstAcmlSrdpTrAmt(Long asstAcmlSrdpTrAmt) {
		this.asstAcmlSrdpTrAmt = asstAcmlSrdpTrAmt;
	}

	@Column(name = "ASST_ACML_SRDP_QTY", precision = 18, scale = 0)
	public Long getAsstAcmlSrdpQty() {
		return this.asstAcmlSrdpQty;
	}

	public void setAsstAcmlSrdpQty(Long asstAcmlSrdpQty) {
		this.asstAcmlSrdpQty = asstAcmlSrdpQty;
	}

	@Column(name = "SWAP_PREM_ACML_SRDP_AMT", precision = 18, scale = 0)
	public Long getSwapPremAcmlSrdpAmt() {
		return this.swapPremAcmlSrdpAmt;
	}

	public void setSwapPremAcmlSrdpAmt(Long swapPremAcmlSrdpAmt) {
		this.swapPremAcmlSrdpAmt = swapPremAcmlSrdpAmt;
	}

	@Column(name = "ELS_PCHS_PRDT_DSCM_NO", length = 12)
	public String getElsPchsPrdtDscmNo() {
		return this.elsPchsPrdtDscmNo;
	}

	public void setElsPchsPrdtDscmNo(String elsPchsPrdtDscmNo) {
		this.elsPchsPrdtDscmNo = elsPchsPrdtDscmNo;
	}

	@Column(name = "ELS_PCHS_PRDT_NAME", length = 90)
	public String getElsPchsPrdtName() {
		return this.elsPchsPrdtName;
	}

	public void setElsPchsPrdtName(String elsPchsPrdtName) {
		this.elsPchsPrdtName = elsPchsPrdtName;
	}

	@Column(name = "ELS_PCHS_SAME_ITEM_YN", length = 1)
	public String getElsPchsSameItemYn() {
		return this.elsPchsSameItemYn;
	}

	public void setElsPchsSameItemYn(String elsPchsSameItemYn) {
		this.elsPchsSameItemYn = elsPchsSameItemYn;
	}

	@Column(name = "ELS_PCHS_SAME_PDNO", length = 12)
	public String getElsPchsSamePdno() {
		return this.elsPchsSamePdno;
	}

	public void setElsPchsSamePdno(String elsPchsSamePdno) {
		this.elsPchsSamePdno = elsPchsSamePdno;
	}

	@Column(name = "ELS_PCHS_SAME_PRDT_TYPE_CD", length = 3)
	public String getElsPchsSamePrdtTypeCd() {
		return this.elsPchsSamePrdtTypeCd;
	}

	public void setElsPchsSamePrdtTypeCd(String elsPchsSamePrdtTypeCd) {
		this.elsPchsSamePrdtTypeCd = elsPchsSamePrdtTypeCd;
	}

	@Column(name = "RCIV_INT_EXCH_FRQC_DVSN_CD", length = 2)
	public String getRcivIntExchFrqcDvsnCd() {
		return this.rcivIntExchFrqcDvsnCd;
	}

	public void setRcivIntExchFrqcDvsnCd(String rcivIntExchFrqcDvsnCd) {
		this.rcivIntExchFrqcDvsnCd = rcivIntExchFrqcDvsnCd;
	}

	@Column(name = "ELS_PCSTL_DFRM_RCIV_DVSN_CD", length = 2)
	public String getElsPcstlDfrmRcivDvsnCd() {
		return this.elsPcstlDfrmRcivDvsnCd;
	}

	public void setElsPcstlDfrmRcivDvsnCd(String elsPcstlDfrmRcivDvsnCd) {
		this.elsPcstlDfrmRcivDvsnCd = elsPcstlDfrmRcivDvsnCd;
	}

	@Column(name = "ELS_PCSTL_DT", length = 8)
	public String getElsPcstlDt() {
		return this.elsPcstlDt;
	}

	public void setElsPcstlDt(String elsPcstlDt) {
		this.elsPcstlDt = elsPcstlDt;
	}

	@Column(name = "DEBT_BGT_SRDP_QTY", precision = 18, scale = 0)
	public Long getDebtBgtSrdpQty() {
		return this.debtBgtSrdpQty;
	}

	public void setDebtBgtSrdpQty(Long debtBgtSrdpQty) {
		this.debtBgtSrdpQty = debtBgtSrdpQty;
	}

	@Column(name = "ASST_BGT_SRDP_QTY", precision = 18, scale = 0)
	public Long getAsstBgtSrdpQty() {
		return this.asstBgtSrdpQty;
	}

	public void setAsstBgtSrdpQty(Long asstBgtSrdpQty) {
		this.asstBgtSrdpQty = asstBgtSrdpQty;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

	@Transient
	public EElsTrDetailType getElsTrDtldTypeCd() {
		return EElsTrDetailType.getEnum(getId().getElsTrDtldTypeCd());
	}

	public void setElsTrDtldTypeCd(EElsTrDetailType elsTrDtldTypeCd) {
		this.elsTrDtldTypeCd = elsTrDtldTypeCd;
	}

	
}
