package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ivot074p0 generated by hbm2java
 */
@Entity
@Table(name = "IVOT074P0")
public class Ivot074p0 implements java.io.Serializable {

	private Ivot074p0Id id;
	private Long debtCblcAmt;
	private BigDecimal frstImncBondAcbkUnpr;
	private Long frstImncBondAbks;
	private BigDecimal imncBondBssEvluUnpr;
	private BigDecimal imncBondEvluUnpr;
	private Long imncBondEvluAmt;
	private Integer svvlDcnt;
	private String ivCrdtGradCd;
	private String mmrkBztpCd;
	private BigDecimal evluErngRt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private BigDecimal frstEvluDsctAcbkUnpr;
	private Long frstEvluDsctAbks;
	private Long imncBondAdjtEvluAmt;
	private String bpmsPrdtClsfCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Ivot074p0() {
	}

	public Ivot074p0(Ivot074p0Id id) {
		this.id = id;
	}

	public Ivot074p0(Ivot074p0Id id, Long debtCblcAmt, BigDecimal frstImncBondAcbkUnpr, Long frstImncBondAbks,
			BigDecimal imncBondBssEvluUnpr, BigDecimal imncBondEvluUnpr, Long imncBondEvluAmt, Integer svvlDcnt,
			String ivCrdtGradCd, String mmrkBztpCd, BigDecimal evluErngRt, String oprtStfno, String oprtTmno,
			String oprtDtlDtime, String oprtTrCd, BigDecimal frstEvluDsctAcbkUnpr, Long frstEvluDsctAbks,
			Long imncBondAdjtEvluAmt, String bpmsPrdtClsfCd, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.debtCblcAmt = debtCblcAmt;
		this.frstImncBondAcbkUnpr = frstImncBondAcbkUnpr;
		this.frstImncBondAbks = frstImncBondAbks;
		this.imncBondBssEvluUnpr = imncBondBssEvluUnpr;
		this.imncBondEvluUnpr = imncBondEvluUnpr;
		this.imncBondEvluAmt = imncBondEvluAmt;
		this.svvlDcnt = svvlDcnt;
		this.ivCrdtGradCd = ivCrdtGradCd;
		this.mmrkBztpCd = mmrkBztpCd;
		this.evluErngRt = evluErngRt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.frstEvluDsctAcbkUnpr = frstEvluDsctAcbkUnpr;
		this.frstEvluDsctAbks = frstEvluDsctAbks;
		this.imncBondAdjtEvluAmt = imncBondAdjtEvluAmt;
		this.bpmsPrdtClsfCd = bpmsPrdtClsfCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "evluDt", column = @Column(name = "EVLU_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "trOppnNo", column = @Column(name = "TR_OPPN_NO", nullable = false, length = 12)),
			@AttributeOverride(name = "elsTrDtldTypeCd", column = @Column(name = "ELS_TR_DTLD_TYPE_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "issuTmod", column = @Column(name = "ISSU_TMOD", nullable = false, precision = 9, scale = 0)) })
	public Ivot074p0Id getId() {
		return this.id;
	}

	public void setId(Ivot074p0Id id) {
		this.id = id;
	}

	@Column(name = "DEBT_CBLC_AMT", precision = 18, scale = 0)
	public Long getDebtCblcAmt() {
		return this.debtCblcAmt;
	}

	public void setDebtCblcAmt(Long debtCblcAmt) {
		this.debtCblcAmt = debtCblcAmt;
	}

	@Column(name = "FRST_IMNC_BOND_ACBK_UNPR", precision = 23, scale = 15)
	public BigDecimal getFrstImncBondAcbkUnpr() {
		return this.frstImncBondAcbkUnpr;
	}

	public void setFrstImncBondAcbkUnpr(BigDecimal frstImncBondAcbkUnpr) {
		this.frstImncBondAcbkUnpr = frstImncBondAcbkUnpr;
	}

	@Column(name = "FRST_IMNC_BOND_ABKS", precision = 18, scale = 0)
	public Long getFrstImncBondAbks() {
		return this.frstImncBondAbks;
	}

	public void setFrstImncBondAbks(Long frstImncBondAbks) {
		this.frstImncBondAbks = frstImncBondAbks;
	}

	@Column(name = "IMNC_BOND_BSS_EVLU_UNPR", precision = 23, scale = 15)
	public BigDecimal getImncBondBssEvluUnpr() {
		return this.imncBondBssEvluUnpr;
	}

	public void setImncBondBssEvluUnpr(BigDecimal imncBondBssEvluUnpr) {
		this.imncBondBssEvluUnpr = imncBondBssEvluUnpr;
	}

	@Column(name = "IMNC_BOND_EVLU_UNPR", precision = 23, scale = 15)
	public BigDecimal getImncBondEvluUnpr() {
		return this.imncBondEvluUnpr;
	}

	public void setImncBondEvluUnpr(BigDecimal imncBondEvluUnpr) {
		this.imncBondEvluUnpr = imncBondEvluUnpr;
	}

	@Column(name = "IMNC_BOND_EVLU_AMT", precision = 18, scale = 0)
	public Long getImncBondEvluAmt() {
		return this.imncBondEvluAmt;
	}

	public void setImncBondEvluAmt(Long imncBondEvluAmt) {
		this.imncBondEvluAmt = imncBondEvluAmt;
	}

	@Column(name = "SVVL_DCNT", precision = 9, scale = 0)
	public Integer getSvvlDcnt() {
		return this.svvlDcnt;
	}

	public void setSvvlDcnt(Integer svvlDcnt) {
		this.svvlDcnt = svvlDcnt;
	}

	@Column(name = "IV_CRDT_GRAD_CD", length = 4)
	public String getIvCrdtGradCd() {
		return this.ivCrdtGradCd;
	}

	public void setIvCrdtGradCd(String ivCrdtGradCd) {
		this.ivCrdtGradCd = ivCrdtGradCd;
	}

	@Column(name = "MMRK_BZTP_CD", length = 7)
	public String getMmrkBztpCd() {
		return this.mmrkBztpCd;
	}

	public void setMmrkBztpCd(String mmrkBztpCd) {
		this.mmrkBztpCd = mmrkBztpCd;
	}

	@Column(name = "EVLU_ERNG_RT", precision = 18, scale = 10)
	public BigDecimal getEvluErngRt() {
		return this.evluErngRt;
	}

	public void setEvluErngRt(BigDecimal evluErngRt) {
		this.evluErngRt = evluErngRt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "FRST_EVLU_DSCT_ACBK_UNPR", precision = 23, scale = 15)
	public BigDecimal getFrstEvluDsctAcbkUnpr() {
		return this.frstEvluDsctAcbkUnpr;
	}

	public void setFrstEvluDsctAcbkUnpr(BigDecimal frstEvluDsctAcbkUnpr) {
		this.frstEvluDsctAcbkUnpr = frstEvluDsctAcbkUnpr;
	}

	@Column(name = "FRST_EVLU_DSCT_ABKS", precision = 18, scale = 0)
	public Long getFrstEvluDsctAbks() {
		return this.frstEvluDsctAbks;
	}

	public void setFrstEvluDsctAbks(Long frstEvluDsctAbks) {
		this.frstEvluDsctAbks = frstEvluDsctAbks;
	}

	@Column(name = "IMNC_BOND_ADJT_EVLU_AMT", precision = 18, scale = 0)
	public Long getImncBondAdjtEvluAmt() {
		return this.imncBondAdjtEvluAmt;
	}

	public void setImncBondAdjtEvluAmt(Long imncBondAdjtEvluAmt) {
		this.imncBondAdjtEvluAmt = imncBondAdjtEvluAmt;
	}

	@Column(name = "BPMS_PRDT_CLSF_CD", length = 12)
	public String getBpmsPrdtClsfCd() {
		return this.bpmsPrdtClsfCd;
	}

	public void setBpmsPrdtClsfCd(String bpmsPrdtClsfCd) {
		this.bpmsPrdtClsfCd = bpmsPrdtClsfCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
