package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Pdif004m0Id generated by hbm2java
 */
@Embeddable
public class Pdif004m0Id implements java.io.Serializable {

	private String pdno;
	private String prdtTypeCd;

	public Pdif004m0Id() {
	}

	public Pdif004m0Id(String pdno, String prdtTypeCd) {
		this.pdno = pdno;
		this.prdtTypeCd = prdtTypeCd;
	}

	@Column(name = "PDNO", nullable = false, length = 12)
	public String getPdno() {
		return this.pdno;
	}

	public void setPdno(String pdno) {
		this.pdno = pdno;
	}

	@Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)
	public String getPrdtTypeCd() {
		return this.prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Pdif004m0Id))
			return false;
		Pdif004m0Id castOther = (Pdif004m0Id) other;

		return ((this.getPdno() == castOther.getPdno()) || (this.getPdno() != null && castOther.getPdno() != null && this
				.getPdno().equals(castOther.getPdno())))
				&& ((this.getPrdtTypeCd() == castOther.getPrdtTypeCd()) || (this.getPrdtTypeCd() != null
						&& castOther.getPrdtTypeCd() != null && this.getPrdtTypeCd().equals(castOther.getPrdtTypeCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPdno() == null ? 0 : this.getPdno().hashCode());
		result = 37 * result + (getPrdtTypeCd() == null ? 0 : this.getPrdtTypeCd().hashCode());
		return result;
	}

}
