package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pdif093p0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF093P0")
public class Pdif093p0 implements java.io.Serializable {

	private Pdif093p0Id id;
	private Pdif004m0 elsMaster;
	private Pdif001m0 prod;
	private String prdtTypeCd;
	private String elsBastPrdtTypeCd;
	private BigDecimal elsBastBspr;
	private Long elsBastPrdtSeq;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Pdif093p0() {
	}

	public Pdif093p0(Pdif093p0Id id) {
		this.id = id;
	}

	public Pdif093p0(Pdif093p0Id id, BigDecimal elsBastBspr, Long elsBastPrdtSeq, String oprtStfno, String oprtTmno,
			String oprtDtlDtime, String oprtTrCd, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.elsBastBspr = elsBastBspr;
		this.elsBastPrdtSeq = elsBastPrdtSeq;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "elsBastPdno", column = @Column(name = "ELS_BAST_PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "elsBastPrdtTypeCd", column = @Column(name = "ELS_BAST_PRDT_TYPE_CD", nullable = false, length = 3)) })
	public Pdif093p0Id getId() {
		return this.id;
	}

	public void setId(Pdif093p0Id id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name="PDNO", insertable=false, updatable=false)
	public Pdif004m0 getElsMaster() {
		return elsMaster;
	}

	public void setElsMaster(Pdif004m0 elsMaster) {
		this.elsMaster = elsMaster;
	}
	
	@ManyToOne
	@JoinColumn(name="ELS_BAST_PDNO", insertable=false, updatable=false)
	public Pdif001m0 getProd() {
		return prod;
	}

	public void setProd(Pdif001m0 prod) {
		this.prod = prod;
	}

	@Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)
	public String getPrdtTypeCd() {
		return this.prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}

	@Column(name = "ELS_BAST_PRDT_TYPE_CD", nullable = false, length = 3)
	public String getElsBastPrdtTypeCd() {
		return this.elsBastPrdtTypeCd;
	}

	public void setElsBastPrdtTypeCd(String elsBastPrdtTypeCd) {
		this.elsBastPrdtTypeCd = elsBastPrdtTypeCd;
	}
	@Column(name = "ELS_BAST_BSPR", precision = 21, scale = 8)
	public BigDecimal getElsBastBspr() {
		return this.elsBastBspr;
	}

	public void setElsBastBspr(BigDecimal elsBastBspr) {
		this.elsBastBspr = elsBastBspr;
	}

	@Column(name = "ELS_BAST_PRDT_SEQ", precision = 16, scale = 0)
	public Long getElsBastPrdtSeq() {
		return this.elsBastPrdtSeq;
	}

	public void setElsBastPrdtSeq(Long elsBastPrdtSeq) {
		this.elsBastPrdtSeq = elsBastPrdtSeq;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
