package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Pdif221p0Id generated by hbm2java
 */
@Embeddable
public class Pdif221p0Id implements java.io.Serializable {

	private String pdno;
	private String prdtTypeCd;
	private String elsEvntDvsnCd;
	private int aplyNodg;

	public Pdif221p0Id() {
	}

	public Pdif221p0Id(String pdno, String prdtTypeCd, String elsEvntDvsnCd, int aplyNodg) {
		this.pdno = pdno;
		this.prdtTypeCd = prdtTypeCd;
		this.elsEvntDvsnCd = elsEvntDvsnCd;
		this.aplyNodg = aplyNodg;
	}

	@Column(name = "PDNO", nullable = false, length = 12)
	public String getPdno() {
		return this.pdno;
	}

	public void setPdno(String pdno) {
		this.pdno = pdno;
	}

	@Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)
	public String getPrdtTypeCd() {
		return this.prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}

	@Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)
	public String getElsEvntDvsnCd() {
		return this.elsEvntDvsnCd;
	}

	public void setElsEvntDvsnCd(String elsEvntDvsnCd) {
		this.elsEvntDvsnCd = elsEvntDvsnCd;
	}

	@Column(name = "APLY_NODG", nullable = false, precision = 9, scale = 0)
	public int getAplyNodg() {
		return this.aplyNodg;
	}

	public void setAplyNodg(int aplyNodg) {
		this.aplyNodg = aplyNodg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Pdif221p0Id))
			return false;
		Pdif221p0Id castOther = (Pdif221p0Id) other;

		return ((this.getPdno() == castOther.getPdno()) || (this.getPdno() != null && castOther.getPdno() != null && this
				.getPdno().equals(castOther.getPdno())))
				&& ((this.getPrdtTypeCd() == castOther.getPrdtTypeCd()) || (this.getPrdtTypeCd() != null
						&& castOther.getPrdtTypeCd() != null && this.getPrdtTypeCd().equals(castOther.getPrdtTypeCd())))
				&& ((this.getElsEvntDvsnCd() == castOther.getElsEvntDvsnCd()) || (this.getElsEvntDvsnCd() != null
						&& castOther.getElsEvntDvsnCd() != null && this.getElsEvntDvsnCd().equals(
						castOther.getElsEvntDvsnCd()))) && (this.getAplyNodg() == castOther.getAplyNodg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPdno() == null ? 0 : this.getPdno().hashCode());
		result = 37 * result + (getPrdtTypeCd() == null ? 0 : this.getPrdtTypeCd().hashCode());
		result = 37 * result + (getElsEvntDvsnCd() == null ? 0 : this.getElsEvntDvsnCd().hashCode());
		result = 37 * result + this.getAplyNodg();
		return result;
	}

}
