package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Pdif221p0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF221P0")
public class Pdif221p0 implements java.io.Serializable {

	private Pdif221p0Id id;
	private String dfrmDt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Pdif221p0() {
	}

	public Pdif221p0(Pdif221p0Id id) {
		this.id = id;
	}

	public Pdif221p0(Pdif221p0Id id, String dfrmDt, String oprtStfno, String oprtTmno, String oprtDtlDtime,
			String oprtTrCd, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.dfrmDt = dfrmDt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "elsEvntDvsnCd", column = @Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "aplyNodg", column = @Column(name = "APLY_NODG", nullable = false, precision = 9, scale = 0)) })
	public Pdif221p0Id getId() {
		return this.id;
	}

	public void setId(Pdif221p0Id id) {
		this.id = id;
	}

	@Column(name = "DFRM_DT", length = 8)
	public String getDfrmDt() {
		return this.dfrmDt;
	}

	public void setDfrmDt(String dfrmDt) {
		this.dfrmDt = dfrmDt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}
	
	private Pdif094p0 elsEvent;

	@Transient
//	@ManyToOne
//	@JoinColumns({
//		 @JoinColumn(name = "ELS_EVNT_DVSN_CD", insertable=false, updatable=false)
//		,@JoinColumn(name = "APLY_NODG", insertable=false, updatable=false)
//		,@JoinColumn(name = "PDNO", insertable=false, updatable=false )
//		,@JoinColumn(name = "PRDT_TYPE_CD", insertable=false, updatable=false )
//	})
	public Pdif094p0 getElsEvent() {
		return elsEvent;
	}

	public void setElsEvent(Pdif094p0 elsEvent) {
		this.elsEvent = elsEvent;
	}
	
}
