package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Pdif216p0Id generated by hbm2java
 */
@Embeddable
public class Pdif216p0Id implements java.io.Serializable {

	private String pdno;
	private String prdtTypeCd;
	private String elsEvntDvsnCd;
	private long elsEvntSeq;
	private long rngeBarrierRtSeq;

	public Pdif216p0Id() {
	}

	public Pdif216p0Id(String pdno, String prdtTypeCd, String elsEvntDvsnCd, long elsEvntSeq, long rngeBarrierRtSeq) {
		this.pdno = pdno;
		this.prdtTypeCd = prdtTypeCd;
		this.elsEvntDvsnCd = elsEvntDvsnCd;
		this.elsEvntSeq = elsEvntSeq;
		this.rngeBarrierRtSeq = rngeBarrierRtSeq;
	}

	@Column(name = "PDNO", nullable = false, length = 12)
	public String getPdno() {
		return this.pdno;
	}

	public void setPdno(String pdno) {
		this.pdno = pdno;
	}

	@Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)
	public String getPrdtTypeCd() {
		return this.prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}

	@Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)
	public String getElsEvntDvsnCd() {
		return this.elsEvntDvsnCd;
	}

	public void setElsEvntDvsnCd(String elsEvntDvsnCd) {
		this.elsEvntDvsnCd = elsEvntDvsnCd;
	}

	@Column(name = "ELS_EVNT_SEQ", nullable = false, precision = 16, scale = 0)
	public long getElsEvntSeq() {
		return this.elsEvntSeq;
	}

	public void setElsEvntSeq(long elsEvntSeq) {
		this.elsEvntSeq = elsEvntSeq;
	}

	@Column(name = "RNGE_BARRIER_RT_SEQ", nullable = false, precision = 16, scale = 0)
	public long getRngeBarrierRtSeq() {
		return this.rngeBarrierRtSeq;
	}

	public void setRngeBarrierRtSeq(long rngeBarrierRtSeq) {
		this.rngeBarrierRtSeq = rngeBarrierRtSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Pdif216p0Id))
			return false;
		Pdif216p0Id castOther = (Pdif216p0Id) other;

		return ((this.getPdno() == castOther.getPdno()) || (this.getPdno() != null && castOther.getPdno() != null && this
				.getPdno().equals(castOther.getPdno())))
				&& ((this.getPrdtTypeCd() == castOther.getPrdtTypeCd()) || (this.getPrdtTypeCd() != null
						&& castOther.getPrdtTypeCd() != null && this.getPrdtTypeCd().equals(castOther.getPrdtTypeCd())))
				&& ((this.getElsEvntDvsnCd() == castOther.getElsEvntDvsnCd()) || (this.getElsEvntDvsnCd() != null
						&& castOther.getElsEvntDvsnCd() != null && this.getElsEvntDvsnCd().equals(
						castOther.getElsEvntDvsnCd())))
				&& (this.getElsEvntSeq() == castOther.getElsEvntSeq())
				&& (this.getRngeBarrierRtSeq() == castOther.getRngeBarrierRtSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPdno() == null ? 0 : this.getPdno().hashCode());
		result = 37 * result + (getPrdtTypeCd() == null ? 0 : this.getPrdtTypeCd().hashCode());
		result = 37 * result + (getElsEvntDvsnCd() == null ? 0 : this.getElsEvntDvsnCd().hashCode());
		result = 37 * result + (int) this.getElsEvntSeq();
		result = 37 * result + (int) this.getRngeBarrierRtSeq();
		return result;
	}

}
