package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.MapKeyJoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.JoinColumnOrFormula;
import org.hibernate.annotations.JoinColumnsOrFormulas;
import org.hibernate.annotations.JoinFormula;

/**
 * Pdif094p0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF094P0")
public class Pdif094p0 implements java.io.Serializable {

//	private Pdif094p0Id id;
	private ElsEventId id;
	private Pdif004m0 elsMaster;
	private Pdif212p0 redemEvent;
	private String elsEvntCndtTypeCd;
	private Integer aplyNodg;
	private String elsRchgTypeCd;
	private String elsObsvFrqcTypeCd;
	private String elsSmtnStsfTypeCd;
	private String evntOccrDt;
	private String evntPrcsDt;
	private String valdTermStrtDt;
	private String valdTermEndDt;
	private String cfrmYn;
	private String poutText;
	private String evntStsfYn;
	private BigDecimal rdptDfrmRt;
	private BigDecimal evluRt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String elsMidlErngTypeCd;
	private String elsSrdpTypeCd;
	private String elsEvntEvluBassDvsnCd;
	private String elsEvluMthdTypeCd;
	private String lastChngPgmName;
	private Date lastChngDtime;
//	private List<Pdif095p0> underEventList = new ArrayList<Pdif095p0>();
	public Pdif094p0() {
	}

//	public Pdif094p0(Pdif094p0Id id) {
//		this.id = id;
//	}

/*	public Pdif094p0(Pdif094p0Id id, String elsEvntCndtTypeCd, Integer aplyNodg, String elsRchgTypeCd,
			String elsObsvFrqcTypeCd, String elsSmtnStsfTypeCd, String evntOccrDt, String evntPrcsDt,
			String valdTermStrtDt, String valdTermEndDt, String cfrmYn, String poutText, String evntStsfYn,
			BigDecimal rdptDfrmRt, BigDecimal evluRt, String oprtStfno, String oprtTmno, String oprtDtlDtime,
			String oprtTrCd, String elsMidlErngTypeCd, String elsSrdpTypeCd, String elsEvntEvluBassDvsnCd,
			String elsEvluMthdTypeCd, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.elsEvntCndtTypeCd = elsEvntCndtTypeCd;
		this.aplyNodg = aplyNodg;
		this.elsRchgTypeCd = elsRchgTypeCd;
		this.elsObsvFrqcTypeCd = elsObsvFrqcTypeCd;
		this.elsSmtnStsfTypeCd = elsSmtnStsfTypeCd;
		this.evntOccrDt = evntOccrDt;
		this.evntPrcsDt = evntPrcsDt;
		this.valdTermStrtDt = valdTermStrtDt;
		this.valdTermEndDt = valdTermEndDt;
		this.cfrmYn = cfrmYn;
		this.poutText = poutText;
		this.evntStsfYn = evntStsfYn;
		this.rdptDfrmRt = rdptDfrmRt;
		this.evluRt = evluRt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.elsMidlErngTypeCd = elsMidlErngTypeCd;
		this.elsSrdpTypeCd = elsSrdpTypeCd;
		this.elsEvntEvluBassDvsnCd = elsEvntEvluBassDvsnCd;
		this.elsEvluMthdTypeCd = elsEvluMthdTypeCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}
*/
	@EmbeddedId
//	@AttributeOverrides({
//		@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
////		@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
//		@AttributeOverride(name = "elsEvntDvsnCd", column = @Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)),
//		@AttributeOverride(name = "elsEvntSeq", column = @Column(name = "ELS_EVNT_SEQ", nullable = false, precision = 16, scale = 0))
//		})
	public ElsEventId getId() {
		return this.id;
	}

	public void setId(ElsEventId id) {
		this.id = id;
	}
	@Transient
//	@ManyToOne
//	@JoinColumn(name="PDNO", insertable=false, updatable=false)
	public Pdif004m0 getElsMaster() {
		return elsMaster;
	}

//	@Transient
//	@OneToOne(mappedBy ="elsEvent")
	@OneToOne
	@PrimaryKeyJoinColumns({
		 @PrimaryKeyJoinColumn(name = "ELS_EVNT_DVSN_CD")
		,@PrimaryKeyJoinColumn(name = "ELS_EVNT_SEQ")
		,@PrimaryKeyJoinColumn(name = "PDNO")
	})
//	@OneToOne
//	@JoinColumns(value = {
//			@JoinColumn(name = "PDNO")
//			,@JoinColumn(name = "PRDT_TYPE_CD")
//			,@JoinColumn(name = "ELS_EVNT_DVSN_CD")
//			,@JoinColumn(name = "ELS_EVNT_SEQ")
//		})
	public Pdif212p0 getRedemEvent() {
		return redemEvent;
	}

	public void setRedemEvent(Pdif212p0 redemEvent) {
		this.redemEvent = redemEvent;
	}

	public void setElsMaster(Pdif004m0 elsMaster) {
		this.elsMaster = elsMaster;
	}

	@Column(name = "ELS_EVNT_CNDT_TYPE_CD", length = 2)
	public String getElsEvntCndtTypeCd() {
		return this.elsEvntCndtTypeCd;
	}

	public void setElsEvntCndtTypeCd(String elsEvntCndtTypeCd) {
		this.elsEvntCndtTypeCd = elsEvntCndtTypeCd;
	}

	@Column(name = "APLY_NODG", precision = 9, scale = 0)
	public Integer getAplyNodg() {
		return this.aplyNodg;
	}

	public void setAplyNodg(Integer aplyNodg) {
		this.aplyNodg = aplyNodg;
	}

	@Column(name = "ELS_RCHG_TYPE_CD", length = 2)
	public String getElsRchgTypeCd() {
		return this.elsRchgTypeCd;
	}

	public void setElsRchgTypeCd(String elsRchgTypeCd) {
		this.elsRchgTypeCd = elsRchgTypeCd;
	}

	@Column(name = "ELS_OBSV_FRQC_TYPE_CD", length = 2)
	public String getElsObsvFrqcTypeCd() {
		return this.elsObsvFrqcTypeCd;
	}

	public void setElsObsvFrqcTypeCd(String elsObsvFrqcTypeCd) {
		this.elsObsvFrqcTypeCd = elsObsvFrqcTypeCd;
	}

	@Column(name = "ELS_SMTN_STSF_TYPE_CD", length = 2)
	public String getElsSmtnStsfTypeCd() {
		return this.elsSmtnStsfTypeCd;
	}

	public void setElsSmtnStsfTypeCd(String elsSmtnStsfTypeCd) {
		this.elsSmtnStsfTypeCd = elsSmtnStsfTypeCd;
	}

	@Column(name = "EVNT_OCCR_DT", length = 8)
	public String getEvntOccrDt() {
		return this.evntOccrDt;
	}

	public void setEvntOccrDt(String evntOccrDt) {
		this.evntOccrDt = evntOccrDt;
	}

	@Column(name = "EVNT_PRCS_DT", length = 8)
	public String getEvntPrcsDt() {
		return this.evntPrcsDt;
	}

	public void setEvntPrcsDt(String evntPrcsDt) {
		this.evntPrcsDt = evntPrcsDt;
	}

	@Column(name = "VALD_TERM_STRT_DT", length = 8)
	public String getValdTermStrtDt() {
		return this.valdTermStrtDt;
	}

	public void setValdTermStrtDt(String valdTermStrtDt) {
		this.valdTermStrtDt = valdTermStrtDt;
	}

	@Column(name = "VALD_TERM_END_DT", length = 8)
	public String getValdTermEndDt() {
		return this.valdTermEndDt;
	}

	public void setValdTermEndDt(String valdTermEndDt) {
		this.valdTermEndDt = valdTermEndDt;
	}

	@Column(name = "CFRM_YN", length = 1)
	public String getCfrmYn() {
		return this.cfrmYn;
	}

	public void setCfrmYn(String cfrmYn) {
		this.cfrmYn = cfrmYn;
	}

	@Column(name = "POUT_TEXT", length = 500)
	public String getPoutText() {
		return this.poutText;
	}

	public void setPoutText(String poutText) {
		this.poutText = poutText;
	}

	@Column(name = "EVNT_STSF_YN", length = 1)
	public String getEvntStsfYn() {
		return this.evntStsfYn;
	}

	public void setEvntStsfYn(String evntStsfYn) {
		this.evntStsfYn = evntStsfYn;
	}

	@Column(name = "RDPT_DFRM_RT", precision = 21, scale = 12)
	public BigDecimal getRdptDfrmRt() {
		return this.rdptDfrmRt;
	}

	public void setRdptDfrmRt(BigDecimal rdptDfrmRt) {
		this.rdptDfrmRt = rdptDfrmRt;
	}

	@Column(name = "EVLU_RT", precision = 21, scale = 8)
	public BigDecimal getEvluRt() {
		return this.evluRt;
	}

	public void setEvluRt(BigDecimal evluRt) {
		this.evluRt = evluRt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "ELS_MIDL_ERNG_TYPE_CD", length = 2)
	public String getElsMidlErngTypeCd() {
		return this.elsMidlErngTypeCd;
	}

	public void setElsMidlErngTypeCd(String elsMidlErngTypeCd) {
		this.elsMidlErngTypeCd = elsMidlErngTypeCd;
	}

	@Column(name = "ELS_SRDP_TYPE_CD", length = 2)
	public String getElsSrdpTypeCd() {
		return this.elsSrdpTypeCd;
	}

	public void setElsSrdpTypeCd(String elsSrdpTypeCd) {
		this.elsSrdpTypeCd = elsSrdpTypeCd;
	}

	@Column(name = "ELS_EVNT_EVLU_BASS_DVSN_CD", length = 2)
	public String getElsEvntEvluBassDvsnCd() {
		return this.elsEvntEvluBassDvsnCd;
	}

	public void setElsEvntEvluBassDvsnCd(String elsEvntEvluBassDvsnCd) {
		this.elsEvntEvluBassDvsnCd = elsEvntEvluBassDvsnCd;
	}

	@Column(name = "ELS_EVLU_MTHD_TYPE_CD", length = 2)
	public String getElsEvluMthdTypeCd() {
		return this.elsEvluMthdTypeCd;
	}

	public void setElsEvluMthdTypeCd(String elsEvluMthdTypeCd) {
		this.elsEvluMthdTypeCd = elsEvluMthdTypeCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

//	@Transient
//	@OneToMany(mappedBy="elsEvent")
//	@OneToMany
//	@JoinColumns({
//		@JoinColumn(name = "PDNO" , insertable=false, updatable=false)
//		,@JoinColumn(name = "PRDT_TYPE_CD" , insertable=false, updatable=false)
//		,@JoinColumn(name = "ELS_EVNT_DVSN_CD", insertable=false, updatable=false)
//		,@JoinColumn(name = "ELS_EVNT_SEQ", insertable=false, updatable=false)
//	})
//	@Fetch(FetchMode.SUBSELECT)
//	public List<Pdif095p0> getUnderEventList() {
//		return underEventList;
//	}
//
//	public void setUnderEventList(List<Pdif095p0> underEventList) {
//		this.underEventList = underEventList;
//	}

	private Map<String, BigDecimal> underEventMap = new HashMap<String, BigDecimal>();
//	@Transient
	@ElementCollection
	@MapKeyColumn(name="ELS_BAST_PDNO")
	@JoinTable(name="PDIF095P0"
		, joinColumns ={
//			,@JoinColumn(name = "PRDT_TYPE_CD" )
			@JoinColumn(name = "ELS_EVNT_DVSN_CD" )
			,@JoinColumn(name = "ELS_EVNT_SEQ")
			,@JoinColumn(name = "PDNO" )
		}
	)
	@Column(name ="BSS_ASST_RT")
	@Fetch(FetchMode.SUBSELECT)
	public Map<String, BigDecimal> getUnderEventMap() {
		return underEventMap;
	}

	public void setUnderEventMap(Map<String, BigDecimal> underEventMap) {
		this.underEventMap = underEventMap;
	}
	
	private List<Pdif221p0> elsPaymentList = new ArrayList<Pdif221p0>();
//	@Transient
	//	@OneToMany(mappedBy="elsEvent")
	@OneToMany
	@JoinColumns({
		@JoinColumn(name = "ELS_EVNT_DVSN_CD")
		,@JoinColumn(name = "APLY_NODG")
		,@JoinColumn(name = "PDNO" )
	})
	@Fetch(FetchMode.SUBSELECT)
	
	public List<Pdif221p0> getElsPaymentList() {
		return elsPaymentList;
	}

	public void setElsPaymentList(List<Pdif221p0> elsPaymentList) {
		this.elsPaymentList = elsPaymentList;
	}
	
}
