package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pdif213p0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF213P0")
public class Pdif213p0 implements java.io.Serializable {

	private Pdif213p0Id id;
	private String midlErnaElsDfrmFrqcCd;
	private BigDecimal ernaLintRt;
	private BigDecimal ernaMaxErngRt;
	private BigDecimal ernaMinErngRt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String elsLintDfrmMthdCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Pdif213p0() {
	}

	public Pdif213p0(Pdif213p0Id id) {
		this.id = id;
	}

	public Pdif213p0(Pdif213p0Id id, String midlErnaElsDfrmFrqcCd, BigDecimal ernaLintRt, BigDecimal ernaMaxErngRt,
			BigDecimal ernaMinErngRt, String oprtStfno, String oprtTmno, String oprtDtlDtime, String oprtTrCd,
			String elsLintDfrmMthdCd, String lastChngPgmName, Date lastChngDtime) {
		this.id = id;
		this.midlErnaElsDfrmFrqcCd = midlErnaElsDfrmFrqcCd;
		this.ernaLintRt = ernaLintRt;
		this.ernaMaxErngRt = ernaMaxErngRt;
		this.ernaMinErngRt = ernaMinErngRt;
		this.oprtStfno = oprtStfno;
		this.oprtTmno = oprtTmno;
		this.oprtDtlDtime = oprtDtlDtime;
		this.oprtTrCd = oprtTrCd;
		this.elsLintDfrmMthdCd = elsLintDfrmMthdCd;
		this.lastChngPgmName = lastChngPgmName;
		this.lastChngDtime = lastChngDtime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "elsEvntDvsnCd", column = @Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "elsEvntSeq", column = @Column(name = "ELS_EVNT_SEQ", nullable = false, precision = 16, scale = 0)) })
	public Pdif213p0Id getId() {
		return this.id;
	}

	public void setId(Pdif213p0Id id) {
		this.id = id;
	}

	@Column(name = "MIDL_ERNA_ELS_DFRM_FRQC_CD", length = 2)
	public String getMidlErnaElsDfrmFrqcCd() {
		return this.midlErnaElsDfrmFrqcCd;
	}

	public void setMidlErnaElsDfrmFrqcCd(String midlErnaElsDfrmFrqcCd) {
		this.midlErnaElsDfrmFrqcCd = midlErnaElsDfrmFrqcCd;
	}

	@Column(name = "ERNA_LINT_RT", precision = 21, scale = 8)
	public BigDecimal getErnaLintRt() {
		return this.ernaLintRt;
	}

	public void setErnaLintRt(BigDecimal ernaLintRt) {
		this.ernaLintRt = ernaLintRt;
	}

	@Column(name = "ERNA_MAX_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getErnaMaxErngRt() {
		return this.ernaMaxErngRt;
	}

	public void setErnaMaxErngRt(BigDecimal ernaMaxErngRt) {
		this.ernaMaxErngRt = ernaMaxErngRt;
	}

	@Column(name = "ERNA_MIN_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getErnaMinErngRt() {
		return this.ernaMinErngRt;
	}

	public void setErnaMinErngRt(BigDecimal ernaMinErngRt) {
		this.ernaMinErngRt = ernaMinErngRt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "ELS_LINT_DFRM_MTHD_CD", length = 2)
	public String getElsLintDfrmMthdCd() {
		return this.elsLintDfrmMthdCd;
	}

	public void setElsLintDfrmMthdCd(String elsLintDfrmMthdCd) {
		this.elsLintDfrmMthdCd = elsLintDfrmMthdCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
