package com.eugenefe.entity.raws;

// Generated 2014. 4. 11 ¿ÀÀü 10:55:56 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pdif001m0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF001M0")
public class Pdif001m0 implements java.io.Serializable {

	private String pdno;
	private String prdtTypeCd;
	private String prdtName;
	private String prdtAbrvName;
	private String stdPdno;
	private String shtnPdno;
	private String prdtSaleStatCd;
	private String prdtRiskGradCd;
	private String prdtClsfCd;
	private String saleStrtDt;
	private String saleEndDt;
	private String prdtEngName;
	private String prdtEngAbrvName;
	private String wrapAsstTypeCd;
	private String ivstPrdtTypeCd;
	private String frstErlmDt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Pdif001m0() {
	}

	@Id
	@Column(name = "PDNO", nullable = false, length = 12)
	public String getPdno() {
		return pdno;
	}
	public void setPdno(String pdno) {
		this.pdno = pdno;
	}
	@Column(name = "PRDT_TYPE_CD", length = 3)
	public String getPrdtTypeCd() {
		return prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}

	@Column(name = "PRDT_NAME", length = 120)
	public String getPrdtName() {
		return this.prdtName;
	}

	public void setPrdtName(String prdtName) {
		this.prdtName = prdtName;
	}

	@Column(name = "PRDT_ABRV_NAME", length = 90)
	public String getPrdtAbrvName() {
		return this.prdtAbrvName;
	}

	public void setPrdtAbrvName(String prdtAbrvName) {
		this.prdtAbrvName = prdtAbrvName;
	}

	@Column(name = "STD_PDNO", length = 12)
	public String getStdPdno() {
		return this.stdPdno;
	}

	public void setStdPdno(String stdPdno) {
		this.stdPdno = stdPdno;
	}

	@Column(name = "SHTN_PDNO", length = 12)
	public String getShtnPdno() {
		return this.shtnPdno;
	}

	public void setShtnPdno(String shtnPdno) {
		this.shtnPdno = shtnPdno;
	}

	@Column(name = "PRDT_SALE_STAT_CD", length = 2)
	public String getPrdtSaleStatCd() {
		return this.prdtSaleStatCd;
	}

	public void setPrdtSaleStatCd(String prdtSaleStatCd) {
		this.prdtSaleStatCd = prdtSaleStatCd;
	}

	@Column(name = "PRDT_RISK_GRAD_CD", length = 2)
	public String getPrdtRiskGradCd() {
		return this.prdtRiskGradCd;
	}

	public void setPrdtRiskGradCd(String prdtRiskGradCd) {
		this.prdtRiskGradCd = prdtRiskGradCd;
	}

	@Column(name = "PRDT_CLSF_CD", length = 6)
	public String getPrdtClsfCd() {
		return this.prdtClsfCd;
	}

	public void setPrdtClsfCd(String prdtClsfCd) {
		this.prdtClsfCd = prdtClsfCd;
	}

	@Column(name = "SALE_STRT_DT", length = 8)
	public String getSaleStrtDt() {
		return this.saleStrtDt;
	}

	public void setSaleStrtDt(String saleStrtDt) {
		this.saleStrtDt = saleStrtDt;
	}

	@Column(name = "SALE_END_DT", length = 8)
	public String getSaleEndDt() {
		return this.saleEndDt;
	}

	public void setSaleEndDt(String saleEndDt) {
		this.saleEndDt = saleEndDt;
	}

	@Column(name = "PRDT_ENG_NAME", length = 120)
	public String getPrdtEngName() {
		return this.prdtEngName;
	}

	public void setPrdtEngName(String prdtEngName) {
		this.prdtEngName = prdtEngName;
	}

	@Column(name = "PRDT_ENG_ABRV_NAME", length = 90)
	public String getPrdtEngAbrvName() {
		return this.prdtEngAbrvName;
	}

	public void setPrdtEngAbrvName(String prdtEngAbrvName) {
		this.prdtEngAbrvName = prdtEngAbrvName;
	}

	@Column(name = "WRAP_ASST_TYPE_CD", length = 2)
	public String getWrapAsstTypeCd() {
		return this.wrapAsstTypeCd;
	}

	public void setWrapAsstTypeCd(String wrapAsstTypeCd) {
		this.wrapAsstTypeCd = wrapAsstTypeCd;
	}

	@Column(name = "IVST_PRDT_TYPE_CD", length = 4)
	public String getIvstPrdtTypeCd() {
		return this.ivstPrdtTypeCd;
	}

	public void setIvstPrdtTypeCd(String ivstPrdtTypeCd) {
		this.ivstPrdtTypeCd = ivstPrdtTypeCd;
	}

	@Column(name = "FRST_ERLM_DT", length = 8)
	public String getFrstErlmDt() {
		return this.frstErlmDt;
	}

	public void setFrstErlmDt(String frstErlmDt) {
		this.frstErlmDt = frstErlmDt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
