package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Pdif212p0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF212P0")
public class Pdif212p0 implements java.io.Serializable {

//	private Pdif212p0Id id;
//	private Pdif094p0Id id;
	private ElsEventId id;
	private Pdif004m0 elsMaster;
	private Pdif094p0 elsEvent;
	private String elsKikoDtlTypeCd;
	private String elsKoutOptDvsnCd;
	private String elsKoutDfrmTypeCd;
	private BigDecimal rbatRt;
	private BigDecimal ptciRt;
	private BigDecimal chguRt;
	private BigDecimal spikRt;
	private String elsAsrcObjtDvsnCd;
	private BigDecimal prcaAsrcRt;
	private BigDecimal asrcErngRt;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String lastChngPgmName;
	private Date lastChngDtime;

	public Pdif212p0() {
	}

//	public Pdif212p0(Pdif212p0Id id) {
//		this.id = id;
//	}
//	public Pdif212p0(Pdif212p0Id id, String elsKikoDtlTypeCd, String elsKoutOptDvsnCd, String elsKoutDfrmTypeCd,
//			BigDecimal rbatRt, BigDecimal ptciRt, BigDecimal chguRt, BigDecimal spikRt, String elsAsrcObjtDvsnCd,
//			BigDecimal prcaAsrcRt, BigDecimal asrcErngRt, String oprtStfno, String oprtTmno, String oprtDtlDtime,
//			String oprtTrCd, String lastChngPgmName, Date lastChngDtime) {
//		this.id = id;
//		this.elsKikoDtlTypeCd = elsKikoDtlTypeCd;
//		this.elsKoutOptDvsnCd = elsKoutOptDvsnCd;
//		this.elsKoutDfrmTypeCd = elsKoutDfrmTypeCd;
//		this.rbatRt = rbatRt;
//		this.ptciRt = ptciRt;
//		this.chguRt = chguRt;
//		this.spikRt = spikRt;
//		this.elsAsrcObjtDvsnCd = elsAsrcObjtDvsnCd;
//		this.prcaAsrcRt = prcaAsrcRt;
//		this.asrcErngRt = asrcErngRt;
//		this.oprtStfno = oprtStfno;
//		this.oprtTmno = oprtTmno;
//		this.oprtDtlDtime = oprtDtlDtime;
//		this.oprtTrCd = oprtTrCd;
//		this.lastChngPgmName = lastChngPgmName;
//		this.lastChngDtime = lastChngDtime;
//	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
//			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "elsEvntDvsnCd", column = @Column(name = "ELS_EVNT_DVSN_CD", nullable = false, length = 2)),
			@AttributeOverride(name = "elsEvntSeq", column = @Column(name = "ELS_EVNT_SEQ", nullable = false, precision = 16, scale = 0)) })
//	@GeneratedValue(generator="gen")
//	@GenericGenerator(name="gen" , strategy="foreign", parameters=@Parameter(name="property", value ="elsEvent"))
//	public Pdif212p0Id getId() {
//		return this.id;
//	}
//
//	public void setId(Pdif212p0Id id) {
//		this.id = id;
//	}
	public ElsEventId getId() {
		return id;
	}
	public void setId(ElsEventId id) {
		this.id = id;
	}

	@Transient
//	@ManyToOne
//	@JoinColumn(name="PDNO", insertable=false, updatable=false)
	public Pdif004m0 getElsMaster() {
		return elsMaster;
	}

	public void setElsMaster(Pdif004m0 elsMaster) {
		this.elsMaster = elsMaster;
	}

	@Transient
//	@OneToOne
//	@PrimaryKeyJoinColumns({
// 		 @PrimaryKeyJoinColumn(name = "PDNO")
//		,@PrimaryKeyJoinColumn(name = "PRDT_TYPE_CD")
//		,@PrimaryKeyJoinColumn(name = "ELS_EVNT_DVSN_CD")
//		,@PrimaryKeyJoinColumn(name = "ELS_EVNT_SEQ")
//	})
	public Pdif094p0 getElsEvent() {
		return elsEvent;
	}

	public void setElsEvent(Pdif094p0 elsEvent) {
		this.elsEvent = elsEvent;
	}

	@Column(name = "ELS_KIKO_DTL_TYPE_CD", length = 2)
	public String getElsKikoDtlTypeCd() {
		return this.elsKikoDtlTypeCd;
	}

	public void setElsKikoDtlTypeCd(String elsKikoDtlTypeCd) {
		this.elsKikoDtlTypeCd = elsKikoDtlTypeCd;
	}

	@Column(name = "ELS_KOUT_OPT_DVSN_CD", length = 2)
	public String getElsKoutOptDvsnCd() {
		return this.elsKoutOptDvsnCd;
	}

	public void setElsKoutOptDvsnCd(String elsKoutOptDvsnCd) {
		this.elsKoutOptDvsnCd = elsKoutOptDvsnCd;
	}

	@Column(name = "ELS_KOUT_DFRM_TYPE_CD", length = 2)
	public String getElsKoutDfrmTypeCd() {
		return this.elsKoutDfrmTypeCd;
	}

	public void setElsKoutDfrmTypeCd(String elsKoutDfrmTypeCd) {
		this.elsKoutDfrmTypeCd = elsKoutDfrmTypeCd;
	}

	@Column(name = "RBAT_RT", precision = 21, scale = 8)
	public BigDecimal getRbatRt() {
		return this.rbatRt;
	}

	public void setRbatRt(BigDecimal rbatRt) {
		this.rbatRt = rbatRt;
	}

	@Column(name = "PTCI_RT", precision = 21, scale = 8)
	public BigDecimal getPtciRt() {
		return this.ptciRt;
	}

	public void setPtciRt(BigDecimal ptciRt) {
		this.ptciRt = ptciRt;
	}

	@Column(name = "CHGU_RT", precision = 21, scale = 8)
	public BigDecimal getChguRt() {
		return this.chguRt;
	}

	public void setChguRt(BigDecimal chguRt) {
		this.chguRt = chguRt;
	}

	@Column(name = "SPIK_RT", precision = 21, scale = 8)
	public BigDecimal getSpikRt() {
		return this.spikRt;
	}

	public void setSpikRt(BigDecimal spikRt) {
		this.spikRt = spikRt;
	}

	@Column(name = "ELS_ASRC_OBJT_DVSN_CD", length = 2)
	public String getElsAsrcObjtDvsnCd() {
		return this.elsAsrcObjtDvsnCd;
	}

	public void setElsAsrcObjtDvsnCd(String elsAsrcObjtDvsnCd) {
		this.elsAsrcObjtDvsnCd = elsAsrcObjtDvsnCd;
	}

	@Column(name = "PRCA_ASRC_RT", precision = 21, scale = 8)
	public BigDecimal getPrcaAsrcRt() {
		return this.prcaAsrcRt;
	}

	public void setPrcaAsrcRt(BigDecimal prcaAsrcRt) {
		this.prcaAsrcRt = prcaAsrcRt;
	}

	@Column(name = "ASRC_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getAsrcErngRt() {
		return this.asrcErngRt;
	}

	public void setAsrcErngRt(BigDecimal asrcErngRt) {
		this.asrcErngRt = asrcErngRt;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

}
