package com.eugenefe.entity.raws;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Pdif004m0 generated by hbm2java
 */
@Entity
@Table(name = "PDIF004M0")
public class Pdif004m0 implements java.io.Serializable {

//	private Pdif004m0Id id;
	private String pdno;
	private String prdtTypeCd;
	private String issuDt;
	private String expdDt;
	private BigDecimal prcaAsrcRt;
	private BigDecimal mdwyCclcInrt;
	private String elsFrstBastPricDecsCd;
	private String elsMidlBastPricDecsCd;
	private String elsLastBastPricDecsCd;
	private String bassIdxTypeDvsnCd;
	private String elsIdxCd;
	private BigDecimal bassIdx;
	private String bassIdxDecsDt;
	private BigDecimal hgstBassIdx;
	private String hgstBassIdxDecsDt;
	private BigDecimal lastBassIdx;
	private String lastBassIdxDecsDt;
	private BigDecimal hgstErngRt;
	private BigDecimal lwstErngRt;
	private BigDecimal dfntErngRt;
	private String rpchPsblYn;
	private Long rpchMinAmt;
	private Long rpchMinUnitAmt;
	private String itemPclcText;
	private String elsSttlTypeCd;
	private String elsPrdtExpdDvsnCd;
	private String elsOptDvsnCd;
	private String elsRdptMthdCd;
	private String elsRdptFrqcCd;
	private BigDecimal rdptBassIdx;
	private String rdptBassIdxDecsDt;
	private String rpchRcitDayTypeCd;
	private String utlzFundRbuyYn;
	private String erngRtDfntYn;
	private String erngRtDfntDt;
	private String drwgPsblDt;
	private String rdptYn;
	private String sbscNo;
	private String ofbdDrvPrdtDvsnCd;
	private String lstgShapCd;
	private String sctsIssuMthdDvsnCd;
	private String elsPrcaAsrcDvsnCd;
	private String crcyCd;
	private String elsSaleTypeCd;
	private BigDecimal elsPapr;
	private BigDecimal elsIssuPric;
	private Long totStupLmtAmt;
	private Long totStupLmtQty;
	private Long salePayAmt;
	private BigDecimal salePayRt;
	private String prcaLossMginIdxRchgYn;
	private String prcaLossMginIdxRchgDt;
	private String elsSttlMthdCd;
	private String erlmDt;
	private String urlAddr;
	private String trdrName;
	private BigDecimal yr1ErngRt;
	private BigDecimal elsRbatRt;
	private BigDecimal elsBnusErngRt;
	private String elsBnfDvsnCd;
	private String offrCpltYn;
	private Long lastIssuParAmt;
	private Long lastIssuParQty;
	private Long lastIssuPymtAmt;
	private Long lastIssuPymtQty;
	private String thcoOtcoDvsnCd;
	private String elsOfrgMthdCd;
	private String sbscYn;
	private String intDvdnIncmDvsnCd;
	private String txtnYn;
	private String oprtStfno;
	private String oprtTmno;
	private String oprtDtlDtime;
	private String oprtTrCd;
	private String issuIsttCd;
	private String elsOtcoPrdtBrkgDvsnCd;
	private String elsBastDmfrDvsnCd;
	private String elsBastClsfCd;
	private String csaAplyYn;
	private String elsMrdpPricDcsdBassCd;
	private String elsMwrpRtdyBassCd;
	private String elsMrdpPydyBassCd;
	private String crdtHpngOccrDt;
	private String optnRdptEcisDt;
	private String elsFrstRdptFrqcCd;
	private String elsErdpBassCd;
	private String elsErdpRtTypeCd;
	private String lastEvluDt;
	private String hgstErngRtUrstYn;
	private String elsErngRtDecsBassCd;
	private String etcErngCndtText;
	private String elsErngTypeCd;
	private String elsRdptStckRcitYn;
	private String rcitStrtDt;
	private String rcitEndDt;
	private String elsRdptStckDfntYn;
	private String stckBuyPdno;
	private String stckBuyPrdtTypeCd;
	private BigDecimal stckBuyUnpr;
	private String stckStrgDt;
	private String lastChngPgmName;
	private Date lastChngDtime;

//	private Pdif001m0 prodMaster ;
	private List<Ivot015p0> elsAssetList = new ArrayList<Ivot015p0>();
	private List<Pdif093p0> elsUnderList = new ArrayList<Pdif093p0>();
	private Map<String,BigDecimal> elsUnderMap = new HashMap<String, BigDecimal>();
	private List<Pdif095p0> elsUnderEventList = new ArrayList<Pdif095p0>();
	private List<Pdif094p0> elsEventList = new ArrayList<Pdif094p0>();
	private List<Pdif212p0> elsRedemList = new ArrayList<Pdif212p0>();
	private Pdif001m0 prod;
	
	public Pdif004m0() {
	}


	@OneToOne
	@PrimaryKeyJoinColumn
	public Pdif001m0 getProd() {
		return prod;
	}

	public void setProd(Pdif001m0 prod) {
		this.prod = prod;
	}

	@Id
	@Column(name = "PDNO", nullable = false, length = 12)
	public String getPdno() {
		return this.pdno;
	}

	public void setPdno(String pdno) {
		this.pdno = pdno;
	}

	@Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)
	public String getPrdtTypeCd() {
		return this.prdtTypeCd;
	}

	public void setPrdtTypeCd(String prdtTypeCd) {
		this.prdtTypeCd = prdtTypeCd;
	}
	
//	@EmbeddedId
//	@AttributeOverrides({
//			@AttributeOverride(name = "pdno", column = @Column(name = "PDNO", nullable = false, length = 12)),
//			@AttributeOverride(name = "prdtTypeCd", column = @Column(name = "PRDT_TYPE_CD", nullable = false, length = 3)) })
//	public Pdif004m0Id getId() {
//		return this.id;
//	}
//
//	public void setId(Pdif004m0Id id) {
//		this.id = id;
//	}

	@Column(name = "ISSU_DT", length = 8)
	public String getIssuDt() {
		return this.issuDt;
	}

	public void setIssuDt(String issuDt) {
		this.issuDt = issuDt;
	}

	@Column(name = "EXPD_DT", length = 8)
	public String getExpdDt() {
		return this.expdDt;
	}

	public void setExpdDt(String expdDt) {
		this.expdDt = expdDt;
	}

	@Column(name = "PRCA_ASRC_RT", precision = 21, scale = 8)
	public BigDecimal getPrcaAsrcRt() {
		return this.prcaAsrcRt;
	}

	public void setPrcaAsrcRt(BigDecimal prcaAsrcRt) {
		this.prcaAsrcRt = prcaAsrcRt;
	}

	@Column(name = "MDWY_CCLC_INRT", precision = 21, scale = 8)
	public BigDecimal getMdwyCclcInrt() {
		return this.mdwyCclcInrt;
	}

	public void setMdwyCclcInrt(BigDecimal mdwyCclcInrt) {
		this.mdwyCclcInrt = mdwyCclcInrt;
	}

	@Column(name = "ELS_FRST_BAST_PRIC_DECS_CD", length = 2)
	public String getElsFrstBastPricDecsCd() {
		return this.elsFrstBastPricDecsCd;
	}

	public void setElsFrstBastPricDecsCd(String elsFrstBastPricDecsCd) {
		this.elsFrstBastPricDecsCd = elsFrstBastPricDecsCd;
	}

	@Column(name = "ELS_MIDL_BAST_PRIC_DECS_CD", length = 2)
	public String getElsMidlBastPricDecsCd() {
		return this.elsMidlBastPricDecsCd;
	}

	public void setElsMidlBastPricDecsCd(String elsMidlBastPricDecsCd) {
		this.elsMidlBastPricDecsCd = elsMidlBastPricDecsCd;
	}

	@Column(name = "ELS_LAST_BAST_PRIC_DECS_CD", length = 2)
	public String getElsLastBastPricDecsCd() {
		return this.elsLastBastPricDecsCd;
	}

	public void setElsLastBastPricDecsCd(String elsLastBastPricDecsCd) {
		this.elsLastBastPricDecsCd = elsLastBastPricDecsCd;
	}

	@Column(name = "BASS_IDX_TYPE_DVSN_CD", length = 2)
	public String getBassIdxTypeDvsnCd() {
		return this.bassIdxTypeDvsnCd;
	}

	public void setBassIdxTypeDvsnCd(String bassIdxTypeDvsnCd) {
		this.bassIdxTypeDvsnCd = bassIdxTypeDvsnCd;
	}

	@Column(name = "ELS_IDX_CD", length = 2)
	public String getElsIdxCd() {
		return this.elsIdxCd;
	}

	public void setElsIdxCd(String elsIdxCd) {
		this.elsIdxCd = elsIdxCd;
	}

	@Column(name = "BASS_IDX", precision = 21, scale = 8)
	public BigDecimal getBassIdx() {
		return this.bassIdx;
	}

	public void setBassIdx(BigDecimal bassIdx) {
		this.bassIdx = bassIdx;
	}

	@Column(name = "BASS_IDX_DECS_DT", length = 8)
	public String getBassIdxDecsDt() {
		return this.bassIdxDecsDt;
	}

	public void setBassIdxDecsDt(String bassIdxDecsDt) {
		this.bassIdxDecsDt = bassIdxDecsDt;
	}

	@Column(name = "HGST_BASS_IDX", precision = 21, scale = 8)
	public BigDecimal getHgstBassIdx() {
		return this.hgstBassIdx;
	}

	public void setHgstBassIdx(BigDecimal hgstBassIdx) {
		this.hgstBassIdx = hgstBassIdx;
	}

	@Column(name = "HGST_BASS_IDX_DECS_DT", length = 8)
	public String getHgstBassIdxDecsDt() {
		return this.hgstBassIdxDecsDt;
	}

	public void setHgstBassIdxDecsDt(String hgstBassIdxDecsDt) {
		this.hgstBassIdxDecsDt = hgstBassIdxDecsDt;
	}

	@Column(name = "LAST_BASS_IDX", precision = 21, scale = 8)
	public BigDecimal getLastBassIdx() {
		return this.lastBassIdx;
	}

	public void setLastBassIdx(BigDecimal lastBassIdx) {
		this.lastBassIdx = lastBassIdx;
	}

	@Column(name = "LAST_BASS_IDX_DECS_DT", length = 8)
	public String getLastBassIdxDecsDt() {
		return this.lastBassIdxDecsDt;
	}

	public void setLastBassIdxDecsDt(String lastBassIdxDecsDt) {
		this.lastBassIdxDecsDt = lastBassIdxDecsDt;
	}

	@Column(name = "HGST_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getHgstErngRt() {
		return this.hgstErngRt;
	}

	public void setHgstErngRt(BigDecimal hgstErngRt) {
		this.hgstErngRt = hgstErngRt;
	}

	@Column(name = "LWST_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getLwstErngRt() {
		return this.lwstErngRt;
	}

	public void setLwstErngRt(BigDecimal lwstErngRt) {
		this.lwstErngRt = lwstErngRt;
	}

	@Column(name = "DFNT_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getDfntErngRt() {
		return this.dfntErngRt;
	}

	public void setDfntErngRt(BigDecimal dfntErngRt) {
		this.dfntErngRt = dfntErngRt;
	}

	@Column(name = "RPCH_PSBL_YN", length = 1)
	public String getRpchPsblYn() {
		return this.rpchPsblYn;
	}

	public void setRpchPsblYn(String rpchPsblYn) {
		this.rpchPsblYn = rpchPsblYn;
	}

	@Column(name = "RPCH_MIN_AMT", precision = 18, scale = 0)
	public Long getRpchMinAmt() {
		return this.rpchMinAmt;
	}

	public void setRpchMinAmt(Long rpchMinAmt) {
		this.rpchMinAmt = rpchMinAmt;
	}

	@Column(name = "RPCH_MIN_UNIT_AMT", precision = 18, scale = 0)
	public Long getRpchMinUnitAmt() {
		return this.rpchMinUnitAmt;
	}

	public void setRpchMinUnitAmt(Long rpchMinUnitAmt) {
		this.rpchMinUnitAmt = rpchMinUnitAmt;
	}

	@Column(name = "ITEM_PCLC_TEXT", length = 800)
	public String getItemPclcText() {
		return this.itemPclcText;
	}

	public void setItemPclcText(String itemPclcText) {
		this.itemPclcText = itemPclcText;
	}

	@Column(name = "ELS_STTL_TYPE_CD", length = 2)
	public String getElsSttlTypeCd() {
		return this.elsSttlTypeCd;
	}

	public void setElsSttlTypeCd(String elsSttlTypeCd) {
		this.elsSttlTypeCd = elsSttlTypeCd;
	}

	@Column(name = "ELS_PRDT_EXPD_DVSN_CD", length = 2)
	public String getElsPrdtExpdDvsnCd() {
		return this.elsPrdtExpdDvsnCd;
	}

	public void setElsPrdtExpdDvsnCd(String elsPrdtExpdDvsnCd) {
		this.elsPrdtExpdDvsnCd = elsPrdtExpdDvsnCd;
	}

	@Column(name = "ELS_OPT_DVSN_CD", length = 2)
	public String getElsOptDvsnCd() {
		return this.elsOptDvsnCd;
	}

	public void setElsOptDvsnCd(String elsOptDvsnCd) {
		this.elsOptDvsnCd = elsOptDvsnCd;
	}

	@Column(name = "ELS_RDPT_MTHD_CD", length = 2)
	public String getElsRdptMthdCd() {
		return this.elsRdptMthdCd;
	}

	public void setElsRdptMthdCd(String elsRdptMthdCd) {
		this.elsRdptMthdCd = elsRdptMthdCd;
	}

	@Column(name = "ELS_RDPT_FRQC_CD", length = 2)
	public String getElsRdptFrqcCd() {
		return this.elsRdptFrqcCd;
	}

	public void setElsRdptFrqcCd(String elsRdptFrqcCd) {
		this.elsRdptFrqcCd = elsRdptFrqcCd;
	}

	@Column(name = "RDPT_BASS_IDX", precision = 21, scale = 8)
	public BigDecimal getRdptBassIdx() {
		return this.rdptBassIdx;
	}

	public void setRdptBassIdx(BigDecimal rdptBassIdx) {
		this.rdptBassIdx = rdptBassIdx;
	}

	@Column(name = "RDPT_BASS_IDX_DECS_DT", length = 8)
	public String getRdptBassIdxDecsDt() {
		return this.rdptBassIdxDecsDt;
	}

	public void setRdptBassIdxDecsDt(String rdptBassIdxDecsDt) {
		this.rdptBassIdxDecsDt = rdptBassIdxDecsDt;
	}

	@Column(name = "RPCH_RCIT_DAY_TYPE_CD", length = 2)
	public String getRpchRcitDayTypeCd() {
		return this.rpchRcitDayTypeCd;
	}

	public void setRpchRcitDayTypeCd(String rpchRcitDayTypeCd) {
		this.rpchRcitDayTypeCd = rpchRcitDayTypeCd;
	}

	@Column(name = "UTLZ_FUND_RBUY_YN", length = 1)
	public String getUtlzFundRbuyYn() {
		return this.utlzFundRbuyYn;
	}

	public void setUtlzFundRbuyYn(String utlzFundRbuyYn) {
		this.utlzFundRbuyYn = utlzFundRbuyYn;
	}

	@Column(name = "ERNG_RT_DFNT_YN", length = 1)
	public String getErngRtDfntYn() {
		return this.erngRtDfntYn;
	}

	public void setErngRtDfntYn(String erngRtDfntYn) {
		this.erngRtDfntYn = erngRtDfntYn;
	}

	@Column(name = "ERNG_RT_DFNT_DT", length = 8)
	public String getErngRtDfntDt() {
		return this.erngRtDfntDt;
	}

	public void setErngRtDfntDt(String erngRtDfntDt) {
		this.erngRtDfntDt = erngRtDfntDt;
	}

	@Column(name = "DRWG_PSBL_DT", length = 8)
	public String getDrwgPsblDt() {
		return this.drwgPsblDt;
	}

	public void setDrwgPsblDt(String drwgPsblDt) {
		this.drwgPsblDt = drwgPsblDt;
	}

	@Column(name = "RDPT_YN", length = 1)
	public String getRdptYn() {
		return this.rdptYn;
	}

	public void setRdptYn(String rdptYn) {
		this.rdptYn = rdptYn;
	}

	@Column(name = "SBSC_NO", length = 12)
	public String getSbscNo() {
		return this.sbscNo;
	}

	public void setSbscNo(String sbscNo) {
		this.sbscNo = sbscNo;
	}

	@Column(name = "OFBD_DRV_PRDT_DVSN_CD", length = 2)
	public String getOfbdDrvPrdtDvsnCd() {
		return this.ofbdDrvPrdtDvsnCd;
	}

	public void setOfbdDrvPrdtDvsnCd(String ofbdDrvPrdtDvsnCd) {
		this.ofbdDrvPrdtDvsnCd = ofbdDrvPrdtDvsnCd;
	}

	@Column(name = "LSTG_SHAP_CD", length = 2)
	public String getLstgShapCd() {
		return this.lstgShapCd;
	}

	public void setLstgShapCd(String lstgShapCd) {
		this.lstgShapCd = lstgShapCd;
	}

	@Column(name = "SCTS_ISSU_MTHD_DVSN_CD", length = 3)
	public String getSctsIssuMthdDvsnCd() {
		return this.sctsIssuMthdDvsnCd;
	}

	public void setSctsIssuMthdDvsnCd(String sctsIssuMthdDvsnCd) {
		this.sctsIssuMthdDvsnCd = sctsIssuMthdDvsnCd;
	}

	@Column(name = "ELS_PRCA_ASRC_DVSN_CD", length = 2)
	public String getElsPrcaAsrcDvsnCd() {
		return this.elsPrcaAsrcDvsnCd;
	}

	public void setElsPrcaAsrcDvsnCd(String elsPrcaAsrcDvsnCd) {
		this.elsPrcaAsrcDvsnCd = elsPrcaAsrcDvsnCd;
	}

	@Column(name = "CRCY_CD", length = 3)
	public String getCrcyCd() {
		return this.crcyCd;
	}

	public void setCrcyCd(String crcyCd) {
		this.crcyCd = crcyCd;
	}

	@Column(name = "ELS_SALE_TYPE_CD", length = 2)
	public String getElsSaleTypeCd() {
		return this.elsSaleTypeCd;
	}

	public void setElsSaleTypeCd(String elsSaleTypeCd) {
		this.elsSaleTypeCd = elsSaleTypeCd;
	}

	@Column(name = "ELS_PAPR", precision = 18, scale = 5)
	public BigDecimal getElsPapr() {
		return this.elsPapr;
	}

	public void setElsPapr(BigDecimal elsPapr) {
		this.elsPapr = elsPapr;
	}

	@Column(name = "ELS_ISSU_PRIC", precision = 21, scale = 8)
	public BigDecimal getElsIssuPric() {
		return this.elsIssuPric;
	}

	public void setElsIssuPric(BigDecimal elsIssuPric) {
		this.elsIssuPric = elsIssuPric;
	}

	@Column(name = "TOT_STUP_LMT_AMT", precision = 18, scale = 0)
	public Long getTotStupLmtAmt() {
		return this.totStupLmtAmt;
	}

	public void setTotStupLmtAmt(Long totStupLmtAmt) {
		this.totStupLmtAmt = totStupLmtAmt;
	}

	@Column(name = "TOT_STUP_LMT_QTY", precision = 18, scale = 0)
	public Long getTotStupLmtQty() {
		return this.totStupLmtQty;
	}

	public void setTotStupLmtQty(Long totStupLmtQty) {
		this.totStupLmtQty = totStupLmtQty;
	}

	@Column(name = "SALE_PAY_AMT", precision = 18, scale = 0)
	public Long getSalePayAmt() {
		return this.salePayAmt;
	}

	public void setSalePayAmt(Long salePayAmt) {
		this.salePayAmt = salePayAmt;
	}

	@Column(name = "SALE_PAY_RT", precision = 21, scale = 8)
	public BigDecimal getSalePayRt() {
		return this.salePayRt;
	}

	public void setSalePayRt(BigDecimal salePayRt) {
		this.salePayRt = salePayRt;
	}

	@Column(name = "PRCA_LOSS_MGIN_IDX_RCHG_YN", length = 1)
	public String getPrcaLossMginIdxRchgYn() {
		return this.prcaLossMginIdxRchgYn;
	}

	public void setPrcaLossMginIdxRchgYn(String prcaLossMginIdxRchgYn) {
		this.prcaLossMginIdxRchgYn = prcaLossMginIdxRchgYn;
	}

	@Column(name = "PRCA_LOSS_MGIN_IDX_RCHG_DT", length = 8)
	public String getPrcaLossMginIdxRchgDt() {
		return this.prcaLossMginIdxRchgDt;
	}

	public void setPrcaLossMginIdxRchgDt(String prcaLossMginIdxRchgDt) {
		this.prcaLossMginIdxRchgDt = prcaLossMginIdxRchgDt;
	}

	@Column(name = "ELS_STTL_MTHD_CD", length = 2)
	public String getElsSttlMthdCd() {
		return this.elsSttlMthdCd;
	}

	public void setElsSttlMthdCd(String elsSttlMthdCd) {
		this.elsSttlMthdCd = elsSttlMthdCd;
	}

	@Column(name = "ERLM_DT", length = 8)
	public String getErlmDt() {
		return this.erlmDt;
	}

	public void setErlmDt(String erlmDt) {
		this.erlmDt = erlmDt;
	}

	@Column(name = "URL_ADDR", length = 200)
	public String getUrlAddr() {
		return this.urlAddr;
	}

	public void setUrlAddr(String urlAddr) {
		this.urlAddr = urlAddr;
	}

	@Column(name = "TRDR_NAME", length = 90)
	public String getTrdrName() {
		return this.trdrName;
	}

	public void setTrdrName(String trdrName) {
		this.trdrName = trdrName;
	}

	@Column(name = "YR1_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getYr1ErngRt() {
		return this.yr1ErngRt;
	}

	public void setYr1ErngRt(BigDecimal yr1ErngRt) {
		this.yr1ErngRt = yr1ErngRt;
	}

	@Column(name = "ELS_RBAT_RT", precision = 21, scale = 8)
	public BigDecimal getElsRbatRt() {
		return this.elsRbatRt;
	}

	public void setElsRbatRt(BigDecimal elsRbatRt) {
		this.elsRbatRt = elsRbatRt;
	}

	@Column(name = "ELS_BNUS_ERNG_RT", precision = 21, scale = 8)
	public BigDecimal getElsBnusErngRt() {
		return this.elsBnusErngRt;
	}

	public void setElsBnusErngRt(BigDecimal elsBnusErngRt) {
		this.elsBnusErngRt = elsBnusErngRt;
	}

	@Column(name = "ELS_BNF_DVSN_CD", length = 2)
	public String getElsBnfDvsnCd() {
		return this.elsBnfDvsnCd;
	}

	public void setElsBnfDvsnCd(String elsBnfDvsnCd) {
		this.elsBnfDvsnCd = elsBnfDvsnCd;
	}

	@Column(name = "OFFR_CPLT_YN", length = 1)
	public String getOffrCpltYn() {
		return this.offrCpltYn;
	}

	public void setOffrCpltYn(String offrCpltYn) {
		this.offrCpltYn = offrCpltYn;
	}

	@Column(name = "LAST_ISSU_PAR_AMT", precision = 18, scale = 0)
	public Long getLastIssuParAmt() {
		return this.lastIssuParAmt;
	}

	public void setLastIssuParAmt(Long lastIssuParAmt) {
		this.lastIssuParAmt = lastIssuParAmt;
	}

	@Column(name = "LAST_ISSU_PAR_QTY", precision = 18, scale = 0)
	public Long getLastIssuParQty() {
		return this.lastIssuParQty;
	}

	public void setLastIssuParQty(Long lastIssuParQty) {
		this.lastIssuParQty = lastIssuParQty;
	}

	@Column(name = "LAST_ISSU_PYMT_AMT", precision = 18, scale = 0)
	public Long getLastIssuPymtAmt() {
		return this.lastIssuPymtAmt;
	}

	public void setLastIssuPymtAmt(Long lastIssuPymtAmt) {
		this.lastIssuPymtAmt = lastIssuPymtAmt;
	}

	@Column(name = "LAST_ISSU_PYMT_QTY", precision = 18, scale = 0)
	public Long getLastIssuPymtQty() {
		return this.lastIssuPymtQty;
	}

	public void setLastIssuPymtQty(Long lastIssuPymtQty) {
		this.lastIssuPymtQty = lastIssuPymtQty;
	}

	@Column(name = "THCO_OTCO_DVSN_CD", length = 2)
	public String getThcoOtcoDvsnCd() {
		return this.thcoOtcoDvsnCd;
	}

	public void setThcoOtcoDvsnCd(String thcoOtcoDvsnCd) {
		this.thcoOtcoDvsnCd = thcoOtcoDvsnCd;
	}

	@Column(name = "ELS_OFRG_MTHD_CD", length = 2)
	public String getElsOfrgMthdCd() {
		return this.elsOfrgMthdCd;
	}

	public void setElsOfrgMthdCd(String elsOfrgMthdCd) {
		this.elsOfrgMthdCd = elsOfrgMthdCd;
	}

	@Column(name = "SBSC_YN", length = 1)
	public String getSbscYn() {
		return this.sbscYn;
	}

	public void setSbscYn(String sbscYn) {
		this.sbscYn = sbscYn;
	}

	@Column(name = "INT_DVDN_INCM_DVSN_CD", length = 2)
	public String getIntDvdnIncmDvsnCd() {
		return this.intDvdnIncmDvsnCd;
	}

	public void setIntDvdnIncmDvsnCd(String intDvdnIncmDvsnCd) {
		this.intDvdnIncmDvsnCd = intDvdnIncmDvsnCd;
	}

	@Column(name = "TXTN_YN", length = 1)
	public String getTxtnYn() {
		return this.txtnYn;
	}

	public void setTxtnYn(String txtnYn) {
		this.txtnYn = txtnYn;
	}

	@Column(name = "OPRT_STFNO", length = 6)
	public String getOprtStfno() {
		return this.oprtStfno;
	}

	public void setOprtStfno(String oprtStfno) {
		this.oprtStfno = oprtStfno;
	}

	@Column(name = "OPRT_TMNO", length = 16)
	public String getOprtTmno() {
		return this.oprtTmno;
	}

	public void setOprtTmno(String oprtTmno) {
		this.oprtTmno = oprtTmno;
	}

	@Column(name = "OPRT_DTL_DTIME", length = 17)
	public String getOprtDtlDtime() {
		return this.oprtDtlDtime;
	}

	public void setOprtDtlDtime(String oprtDtlDtime) {
		this.oprtDtlDtime = oprtDtlDtime;
	}

	@Column(name = "OPRT_TR_CD", length = 12)
	public String getOprtTrCd() {
		return this.oprtTrCd;
	}

	public void setOprtTrCd(String oprtTrCd) {
		this.oprtTrCd = oprtTrCd;
	}

	@Column(name = "ISSU_ISTT_CD", length = 5)
	public String getIssuIsttCd() {
		return this.issuIsttCd;
	}

	public void setIssuIsttCd(String issuIsttCd) {
		this.issuIsttCd = issuIsttCd;
	}

	@Column(name = "ELS_OTCO_PRDT_BRKG_DVSN_CD", length = 2)
	public String getElsOtcoPrdtBrkgDvsnCd() {
		return this.elsOtcoPrdtBrkgDvsnCd;
	}

	public void setElsOtcoPrdtBrkgDvsnCd(String elsOtcoPrdtBrkgDvsnCd) {
		this.elsOtcoPrdtBrkgDvsnCd = elsOtcoPrdtBrkgDvsnCd;
	}

	@Column(name = "ELS_BAST_DMFR_DVSN_CD", length = 2)
	public String getElsBastDmfrDvsnCd() {
		return this.elsBastDmfrDvsnCd;
	}

	public void setElsBastDmfrDvsnCd(String elsBastDmfrDvsnCd) {
		this.elsBastDmfrDvsnCd = elsBastDmfrDvsnCd;
	}

	@Column(name = "ELS_BAST_CLSF_CD", length = 2)
	public String getElsBastClsfCd() {
		return this.elsBastClsfCd;
	}

	public void setElsBastClsfCd(String elsBastClsfCd) {
		this.elsBastClsfCd = elsBastClsfCd;
	}

	@Column(name = "CSA_APLY_YN", length = 1)
	public String getCsaAplyYn() {
		return this.csaAplyYn;
	}

	public void setCsaAplyYn(String csaAplyYn) {
		this.csaAplyYn = csaAplyYn;
	}

	@Column(name = "ELS_MRDP_PRIC_DCSD_BASS_CD", length = 2)
	public String getElsMrdpPricDcsdBassCd() {
		return this.elsMrdpPricDcsdBassCd;
	}

	public void setElsMrdpPricDcsdBassCd(String elsMrdpPricDcsdBassCd) {
		this.elsMrdpPricDcsdBassCd = elsMrdpPricDcsdBassCd;
	}

	@Column(name = "ELS_MWRP_RTDY_BASS_CD", length = 2)
	public String getElsMwrpRtdyBassCd() {
		return this.elsMwrpRtdyBassCd;
	}

	public void setElsMwrpRtdyBassCd(String elsMwrpRtdyBassCd) {
		this.elsMwrpRtdyBassCd = elsMwrpRtdyBassCd;
	}

	@Column(name = "ELS_MRDP_PYDY_BASS_CD", length = 2)
	public String getElsMrdpPydyBassCd() {
		return this.elsMrdpPydyBassCd;
	}

	public void setElsMrdpPydyBassCd(String elsMrdpPydyBassCd) {
		this.elsMrdpPydyBassCd = elsMrdpPydyBassCd;
	}

	@Column(name = "CRDT_HPNG_OCCR_DT", length = 8)
	public String getCrdtHpngOccrDt() {
		return this.crdtHpngOccrDt;
	}

	public void setCrdtHpngOccrDt(String crdtHpngOccrDt) {
		this.crdtHpngOccrDt = crdtHpngOccrDt;
	}

	@Column(name = "OPTN_RDPT_ECIS_DT", length = 8)
	public String getOptnRdptEcisDt() {
		return this.optnRdptEcisDt;
	}

	public void setOptnRdptEcisDt(String optnRdptEcisDt) {
		this.optnRdptEcisDt = optnRdptEcisDt;
	}

	@Column(name = "ELS_FRST_RDPT_FRQC_CD", length = 2)
	public String getElsFrstRdptFrqcCd() {
		return this.elsFrstRdptFrqcCd;
	}

	public void setElsFrstRdptFrqcCd(String elsFrstRdptFrqcCd) {
		this.elsFrstRdptFrqcCd = elsFrstRdptFrqcCd;
	}

	@Column(name = "ELS_ERDP_BASS_CD", length = 2)
	public String getElsErdpBassCd() {
		return this.elsErdpBassCd;
	}

	public void setElsErdpBassCd(String elsErdpBassCd) {
		this.elsErdpBassCd = elsErdpBassCd;
	}

	@Column(name = "ELS_ERDP_RT_TYPE_CD", length = 2)
	public String getElsErdpRtTypeCd() {
		return this.elsErdpRtTypeCd;
	}

	public void setElsErdpRtTypeCd(String elsErdpRtTypeCd) {
		this.elsErdpRtTypeCd = elsErdpRtTypeCd;
	}

	@Column(name = "LAST_EVLU_DT", length = 8)
	public String getLastEvluDt() {
		return this.lastEvluDt;
	}

	public void setLastEvluDt(String lastEvluDt) {
		this.lastEvluDt = lastEvluDt;
	}

	@Column(name = "HGST_ERNG_RT_URST_YN", length = 1)
	public String getHgstErngRtUrstYn() {
		return this.hgstErngRtUrstYn;
	}

	public void setHgstErngRtUrstYn(String hgstErngRtUrstYn) {
		this.hgstErngRtUrstYn = hgstErngRtUrstYn;
	}

	@Column(name = "ELS_ERNG_RT_DECS_BASS_CD", length = 2)
	public String getElsErngRtDecsBassCd() {
		return this.elsErngRtDecsBassCd;
	}

	public void setElsErngRtDecsBassCd(String elsErngRtDecsBassCd) {
		this.elsErngRtDecsBassCd = elsErngRtDecsBassCd;
	}

	@Column(name = "ETC_ERNG_CNDT_TEXT", length = 500)
	public String getEtcErngCndtText() {
		return this.etcErngCndtText;
	}

	public void setEtcErngCndtText(String etcErngCndtText) {
		this.etcErngCndtText = etcErngCndtText;
	}

	@Column(name = "ELS_ERNG_TYPE_CD", length = 2)
	public String getElsErngTypeCd() {
		return this.elsErngTypeCd;
	}

	public void setElsErngTypeCd(String elsErngTypeCd) {
		this.elsErngTypeCd = elsErngTypeCd;
	}

	@Column(name = "ELS_RDPT_STCK_RCIT_YN", length = 1)
	public String getElsRdptStckRcitYn() {
		return this.elsRdptStckRcitYn;
	}

	public void setElsRdptStckRcitYn(String elsRdptStckRcitYn) {
		this.elsRdptStckRcitYn = elsRdptStckRcitYn;
	}

	@Column(name = "RCIT_STRT_DT", length = 8)
	public String getRcitStrtDt() {
		return this.rcitStrtDt;
	}

	public void setRcitStrtDt(String rcitStrtDt) {
		this.rcitStrtDt = rcitStrtDt;
	}

	@Column(name = "RCIT_END_DT", length = 8)
	public String getRcitEndDt() {
		return this.rcitEndDt;
	}

	public void setRcitEndDt(String rcitEndDt) {
		this.rcitEndDt = rcitEndDt;
	}

	@Column(name = "ELS_RDPT_STCK_DFNT_YN", length = 1)
	public String getElsRdptStckDfntYn() {
		return this.elsRdptStckDfntYn;
	}

	public void setElsRdptStckDfntYn(String elsRdptStckDfntYn) {
		this.elsRdptStckDfntYn = elsRdptStckDfntYn;
	}

	@Column(name = "STCK_BUY_PDNO", length = 12)
	public String getStckBuyPdno() {
		return this.stckBuyPdno;
	}

	public void setStckBuyPdno(String stckBuyPdno) {
		this.stckBuyPdno = stckBuyPdno;
	}

	@Column(name = "STCK_BUY_PRDT_TYPE_CD", length = 3)
	public String getStckBuyPrdtTypeCd() {
		return this.stckBuyPrdtTypeCd;
	}

	public void setStckBuyPrdtTypeCd(String stckBuyPrdtTypeCd) {
		this.stckBuyPrdtTypeCd = stckBuyPrdtTypeCd;
	}

	@Column(name = "STCK_BUY_UNPR", precision = 21, scale = 8)
	public BigDecimal getStckBuyUnpr() {
		return this.stckBuyUnpr;
	}

	public void setStckBuyUnpr(BigDecimal stckBuyUnpr) {
		this.stckBuyUnpr = stckBuyUnpr;
	}

	@Column(name = "STCK_STRG_DT", length = 8)
	public String getStckStrgDt() {
		return this.stckStrgDt;
	}

	public void setStckStrgDt(String stckStrgDt) {
		this.stckStrgDt = stckStrgDt;
	}

	@Column(name = "LAST_CHNG_PGM_NAME", length = 50)
	public String getLastChngPgmName() {
		return this.lastChngPgmName;
	}

	public void setLastChngPgmName(String lastChngPgmName) {
		this.lastChngPgmName = lastChngPgmName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_CHNG_DTIME", length = 7)
	public Date getLastChngDtime() {
		return this.lastChngDtime;
	}

	public void setLastChngDtime(Date lastChngDtime) {
		this.lastChngDtime = lastChngDtime;
	}

//	@Transient
//	@ManyToOne
//	@JoinColumn(name="PDNO", nullable = true)
//	public Pdif001m0 getProdMaster() {
//		return prodMaster;
//	}
//
//	public void setProdMaster(Pdif001m0 prodMaster) {
//		this.prodMaster = prodMaster;
//	}

	
	@OneToMany(mappedBy="elsMaster")
	public List<Ivot015p0> getElsAssetList() {
		return elsAssetList;
	}

	public void setElsAssetList(List<Ivot015p0> elsAssetList) {
		this.elsAssetList = elsAssetList;
	}
	@Transient
//	@OneToMany(mappedBy="elsMaster")
//	@Fetch(FetchMode.SUBSELECT)
	public List<Pdif093p0> getElsUnderList() {
		return elsUnderList;
	}

	@ElementCollection
	@MapKeyColumn(name="ELS_BAST_PDNO")
	@JoinTable(name="PDIF093P0"
		, joinColumns=@JoinColumn(name ="PDNO")
	)
	@Column(name="ELS_BAST_BSPR")
	@Fetch(FetchMode.SUBSELECT)
	public Map<String, BigDecimal> getElsUnderMap() {
		return elsUnderMap;
	}

	public void setElsUnderMap(Map<String, BigDecimal> elsUnderMap) {
		this.elsUnderMap = elsUnderMap;
	}

	public void setElsUnderList(List<Pdif093p0> elsUnderList) {
		this.elsUnderList = elsUnderList;
	}
	@Transient
//	@OneToMany(mappedBy="elsMaster")
	public List<Pdif095p0> getElsUnderEventList() {
		return elsUnderEventList;
	}

	public void setElsUnderEventList(List<Pdif095p0> elsUnderEventList) {
		this.elsUnderEventList = elsUnderEventList;
	}
//	@OneToMany(mappedBy="elsMaster")
	@OneToMany
//	@JoinColumn(name="PDNO", insertable=false, updatable=false)
	@JoinColumn(name="PDNO")
	@Fetch(FetchMode.SUBSELECT)
	public List<Pdif094p0> getElsEventList() {
		return elsEventList;
	}

	public void setElsEventList(List<Pdif094p0> elsEventList) {
		this.elsEventList = elsEventList;
	}

	@Transient
//	@OneToMany(mappedBy="elsMaster")
	public List<Pdif212p0> getElsRedemList() {
		return elsRedemList;
	}

	public void setElsRedemList(List<Pdif212p0> elsRedemList) {
		this.elsRedemList = elsRedemList;
	}
	

}
