package com.eugenefe.entity;

// Generated Apr 16, 2013 7:33:55 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * Basedate generated by hbm2java
 */
@Entity
@Table(name = "BASEDATE")
@AnnoNavigationFilter
public class Basedate implements java.io.Serializable {

	private String bssd;
	private Boolean isBizday;
	private String prevBizday;
	private String nextBizday;
	private String eomBizday;
	private String eoqBizday;
	private String eosBizday;
	private String eoyBizday;
	private String fiscalBizday;

	public Basedate() {
	}

	public Basedate(String bssd) {
		this.bssd = bssd;
	}

//	public Basedate(String bssd, Character isBizday, String prevBizday, String nextBizday, String eomBizday,
//			String eoqBizday, String eosBizday, String eoyBizday, String fiscalBizday) {
//		this.bssd = bssd;
//		this.isBizday = isBizday;
//		this.prevBizday = prevBizday;
//		this.nextBizday = nextBizday;
//		this.eomBizday = eomBizday;
//		this.eoqBizday = eoqBizday;
//		this.eosBizday = eosBizday;
//		this.eoyBizday = eoyBizday;
//		this.fiscalBizday = fiscalBizday;
//	}

	@Id
	@Column(name = "BSSD", nullable = false, length = 8)
	@AnnoMethodTree(order=10, init=true)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

//	@Column(name = "IS_BIZDAY", length = 1)
//	public Character getIsBizday() {
//		return this.isBizday;
//	}
//
//	public void setIsBizday(Character isBizday) {
//		this.isBizday = isBizday;
//	}
	@Column(name = "IS_BIZDAY" )
	@Type(type="yes_no")
	@AnnoMethodTree(order=20, init=true)
	public Boolean isBizday() {
		return isBizday;
	}
	public void setBizday(Boolean isBizday) {
		this.isBizday = isBizday;
	}
	
	@Column(name = "PREV_BIZDAY", length = 8)
	@AnnoMethodTree(order=30, init=true)
	public String getPrevBizday() {
		return this.prevBizday;
	}

	

	public void setPrevBizday(String prevBizday) {
		this.prevBizday = prevBizday;
	}

	@Column(name = "NEXT_BIZDAY", length = 8)
	@AnnoMethodTree(order=40, init=true)
	public String getNextBizday() {
		return this.nextBizday;
	}

	public void setNextBizday(String nextBizday) {
		this.nextBizday = nextBizday;
	}

	@Column(name = "EOM_BIZDAY", length = 8)
	public String getEomBizday() {
		return this.eomBizday;
	}

	public void setEomBizday(String eomBizday) {
		this.eomBizday = eomBizday;
	}

	@Column(name = "EOQ_BIZDAY", length = 8)
	public String getEoqBizday() {
		return this.eoqBizday;
	}

	public void setEoqBizday(String eoqBizday) {
		this.eoqBizday = eoqBizday;
	}

	@Column(name = "EOS_BIZDAY", length = 8)
	public String getEosBizday() {
		return this.eosBizday;
	}

	public void setEosBizday(String eosBizday) {
		this.eosBizday = eosBizday;
	}

	@Column(name = "EOY_BIZDAY", length = 8)
	public String getEoyBizday() {
		return this.eoyBizday;
	}

	public void setEoyBizday(String eoyBizday) {
		this.eoyBizday = eoyBizday;
	}

	@Column(name = "FISCAL_BIZDAY", length = 8)
	public String getFiscalBizday() {
		return this.fiscalBizday;
	}

	public void setFiscalBizday(String fiscalBizday) {
		this.fiscalBizday = fiscalBizday;
	}

}
