package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * BondHisId generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class BondHisId implements java.io.Serializable {

	private String bssd;
	private String bondId;

	public BondHisId() {
	}

	public BondHisId(String bssd, String bondId) {
		this.bssd = bssd;
		this.bondId = bondId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	@AnnoMethodTree(order=10, init=true)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "BOND_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	@AnnoMethodTree(order=20, init=true)
	public String getBondId() {
		return this.bondId;
	}

	public void setBondId(String bondId) {
		this.bondId = bondId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BondHisId))
			return false;
		BondHisId castOther = (BondHisId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getBondId() == castOther.getBondId()) || (this.getBondId() != null
						&& castOther.getBondId() != null && this.getBondId().equals(castOther.getBondId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getBondId() == null ? 0 : this.getBondId().hashCode());
		return result;
	}

}
