package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

/**
 * Futures generated by hbm2java
 */
@Entity
@Table(name = "FUTURES")
@PrimaryKeyJoinColumn(name="FUTURES_ID")
@AnnoNavigationFilter
public class Futures extends MarketVariableJoin implements java.io.Serializable {

//	private String futuresId;
//	private MarketVariable marketVariableByMvId;
	private MarketVariable underlying;
	private String issueDate;
	private String maturityDate;
	private BigDecimal notionalAmt;
	private BigDecimal strikePrice;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;
	private List<FuturesHis> futuresHises = new ArrayList<FuturesHis>();

	public Futures() {
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "marketVariableByMvId"))
//	@Id
//	@GeneratedValue(generator = "generator")
//	@Column(name = "FUTURES_ID", unique = true, nullable = false, length = 20)
//	@Size(max = 20)
//	@AnnoMethodTree(order=10, init=true)
//	public String getFuturesId() {
//		return this.futuresId;
//	}
//
//	public void setFuturesId(String futuresId) {
//		this.futuresId = futuresId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNDERLYING_ID")
	@AnnoMethodTree(order=20, init=false)
	public MarketVariable getUnderlying() {
		return this.underlying;
	}

	public void setUnderlying(MarketVariable underlying) {
		this.underlying = underlying;
	}

//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	@NotNull
//	@Size(max = 20)
//	@AnnoMethodTree(order=21, init=false)
//	@Transient
//	public MarketVariable getMarketVariableByMvId() {
//		return this.marketVariableByMvId;
//	}
//	public void setMarketVariableByMvId(MarketVariable marketVariableByMvId) {
//		this.marketVariableByMvId = marketVariableByMvId;
//	}

	@Column(name = "ISSUE_DATE", length = 8)
	@Size(max = 8)
	@AnnoMethodTree(order=30, init=true)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "MATURITY_DATE", length = 8)
	@Size(max = 8)
	@AnnoMethodTree(order=31, init=true)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;
	}

	@Column(name = "NOTIONAL_AMT", scale = 0)
	@AnnoMethodTree(order=35, init=true, align="right")
	public BigDecimal getNotionalAmt() {
		return this.notionalAmt;
	}

	public void setNotionalAmt(BigDecimal notionalAmt) {
		this.notionalAmt = notionalAmt;
	}

	@Column(name = "STRIKE_PRICE", precision = 10, scale = 4)
	@AnnoMethodTree(order=40, init=true, align="right")
	public BigDecimal getStrikePrice() {
		return this.strikePrice;
	}

	public void setStrikePrice(BigDecimal strikePrice) {
		this.strikePrice = strikePrice;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	@Size(max = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	@Size(max = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	@Size(max = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "futures")
	@AnnoMethodTree(order=50, init=false, type=EColumnType.List)
	public List<FuturesHis> getFuturesHises() {
		return this.futuresHises;
	}

	public void setFuturesHises(List<FuturesHis> futuresHises) {
		this.futuresHises = futuresHises;
	}

}
