package com.eugenefe.entity;

// Generated 2014. 2. 10 ¿ÀÈÄ 5:51:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * Hierarchy generated by hbm2java
 */
@Entity
@Table(name = "HIERARCHY")
@AnnoNavigationFilter
public class Hierarchy implements java.io.Serializable {

	private String hierarchyId;
	private String hierarchyName;
	private String useYn;

	public Hierarchy() {
	}

	public Hierarchy(String hierarchyId) {
		this.hierarchyId = hierarchyId;
	}

	public Hierarchy(String hierarchyId, String hierarchyName, String useYn) {
		this.hierarchyId = hierarchyId;
		this.hierarchyName = hierarchyName;
		this.useYn = useYn;
	}

	@Id
	@Column(name = "HIERARCHY_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order =10, init=true)
	public String getHierarchyId() {
		return this.hierarchyId;
	}

	public void setHierarchyId(String hierarchyId) {
		this.hierarchyId = hierarchyId;
	}

	@Column(name = "HIERARCHY_NAME", length = 50)
	@AnnoMethodTree(order =20, init=true)
	public String getHierarchyName() {
		return this.hierarchyName;
	}

	public void setHierarchyName(String hierarchyName) {
		this.hierarchyName = hierarchyName;
	}

	@Column(name = "USE_YN", length = 1)
	@AnnoMethodTree(order =30, init=true)
	public String getUseYn() {
		return this.useYn;
	}

	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

}
