package com.eugenefe.entity;

// Generated 2014. 2. 10 ¿ÀÈÄ 5:51:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * HierNode generated by hbm2java
 */
@Entity
@Table(name = "HIER_PROPERTY")
@AnnoNavigationFilter
public class HierarchyProperty implements java.io.Serializable {

	private String propId;
	private String propName;
	private String tableId;
	private String tableName;
	private String columnId;
	private String columnName;

	public HierarchyProperty() {
	}


	@Id
	@Column(name = "PROP_ID", unique = true, nullable = false, length = 50)
	@AnnoMethodTree(order =10, init=true)
	public String getPropId() {
		return propId;
	}
	public void setPropId(String propId) {
		this.propId = propId;
	}


	@Column(name = "PROP_NAME", length = 50)
	@AnnoMethodTree(order =20, init=true)
	public String getPropName() {
		return propName;
	}
	public void setPropName(String propName) {
		this.propName = propName;
	}

	@Column(name = "TABLE_ID", length = 50)
	@AnnoMethodTree(order =40, init=true)
	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	@Column(name = "TABLE_NAME", length = 50)
	@AnnoMethodTree(order =41, init=true)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "COLUMN_ID", length = 50)
	@AnnoMethodTree(order =50, init=true)
	public String getColumnId() {
		return this.columnId;
	}

	public void setColumnId(String columnId) {
		this.columnId = columnId;
	}

	@Column(name = "COLUMN_NAME", length = 50)
	@AnnoMethodTree(order =51, init=true)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}


	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return super.hashCode();
	}


	@Override
	public boolean equals(Object obj) {
		if(obj instanceof HierarchyProperty){
			HierarchyProperty castObj = (HierarchyProperty)obj;
			return this.propId.equals(castObj.propId);
		}else{
			return false;
		}
	}
	
}
