package com.eugenefe.entity;

// Generated 2014. 2. 10 ¿ÀÈÄ 5:51:10 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * HierarchyDetail generated by hbm2java
 */
@Entity
@Table(name = "HIERARCHY_DETAIL")
@AnnoNavigationFilter
public class HierarchyDetail implements java.io.Serializable {

	private HierarchyDetailId id;
	private HierarchyNode parentNode;

	public HierarchyDetail() {
	}

	public HierarchyDetail(HierarchyDetailId id) {
		this.id = id;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "hierarchyId", column = @Column(name = "HIERARCHY_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "nodeId", column = @Column(name = "NODE_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order =10, init=true)
	public HierarchyDetailId getId() {
		return this.id;
	}

	public void setId(HierarchyDetailId id) {
		this.id = id;
	}

	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "PARENT_NODE_ID", nullable=true)
	@AnnoMethodTree(order =20, init=true)
	public HierarchyNode getParentNode() {
		return parentNode;
	}

	public void setParentNode(HierarchyNode parentNode) {
		this.parentNode = parentNode;
	}

}
