package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;

import com.eugenefe.enums.raw.EElsObserveFrequencyType;
import com.eugenefe.enums.raw.EElsSmtnSatisfactionType;
import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.FnCalendar;

/**
 * HifiveStrike generated by hbm2java
 */
@Entity
@Table(name = "HIFIVE_MONTH_COUPON")
@AnnoNavigationFilter
public class HifiveMonthCoupon implements java.io.Serializable, Cloneable, Comparable<HifiveMonthCoupon> {

	private HifiveMonthCoupoId id;
	private Hifive hifive;
	private String couponEvalDate;
	private BigDecimal barrierRate;
	private EElsObserveFrequencyType observeType;
	private EElsSmtnSatisfactionType smtmType;
	private BigDecimal couponRate;

	public HifiveMonthCoupon() {
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)),
		@AttributeOverride(name = "prodCondId", column = @Column(name = "COUPON_PAY_DATE", nullable = false)) })
	@AnnoMethodTree(order=10, init=true)
	public HifiveMonthCoupoId getId() {
		return this.id;
	}

	public void setId(HifiveMonthCoupoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=20, init=true)
	public Hifive getHifive() {
		return this.hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}

	@Column(name = "COUPON_EVAL_DATE")
	@AnnoMethodTree(order=21, init=true)
	public String getCouponEvalDate() {
		return couponEvalDate;
	}


	public void setCouponEvalDate(String couponEvalDate) {
		this.couponEvalDate = couponEvalDate;
	}

	@Column(name = "BARRIER_RATE")
	@AnnoMethodTree(order=31, init=true)
	public BigDecimal getBarrierRate() {
		return barrierRate;
	}


	public void setBarrierRate(BigDecimal barrierRate) {
		this.barrierRate = barrierRate;
	}

	@Column(name = "OBSERVE_TYPE")
	@AnnoMethodTree(order=32, init=true)
	@Enumerated(EnumType.STRING)
	public EElsObserveFrequencyType getObserveType() {
		return observeType;
	}
	public void setObserveType(EElsObserveFrequencyType observeType) {
		this.observeType = observeType;
	}
//	public String getObserveType() {
//		return observeType;
//	}
//	public void setObserveType(String observeType) {
//		this.observeType = observeType;
//	}

	@Column(name = "HITTING_TYPE")
	@AnnoMethodTree(order=33, init=true)
	@Enumerated(EnumType.STRING)
	public EElsSmtnSatisfactionType getSmtmType() {
		return smtmType;
	}


	public void setSmtmType(EElsSmtnSatisfactionType smtmType) {
		this.smtmType = smtmType;
	}
//	public String getSmtmType() {
//		return smtmType;
//	}
//	public void setSmtmType(String smtmType) {
//		this.smtmType = smtmType;
//	}

	@Column(name = "COUPON_RATE", precision=4)
	@AnnoMethodTree(order=41, init=true)
	public BigDecimal getCouponRate() {
		return couponRate;
	}


	public void setCouponRate(BigDecimal couponRate) {
		this.couponRate = couponRate;
	}
	
	@Transient
	public  static List<String> getColumnList(){
		List<String> columnList = new ArrayList<String>();
		
		columnList.add("getCouponEvalDate");
		columnList.add("getBarrierRate");
		columnList.add("getObserveType");
		columnList.add("getSmtmType");
		columnList.add("getCouponRate");
		return columnList;
	}

	@Override
	@Transient
	public int compareTo(HifiveMonthCoupon o) {
		return this.getId().getCouponPayDate().compareTo(o.getId().getCouponPayDate());
	}	

}
