package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * HifiveStrikeId generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class HifiveStrikeId implements java.io.Serializable {

	private String prodId;
	private long strikeSerial;

	public HifiveStrikeId() {
	}

	public HifiveStrikeId(String prodId, long strikeSerial) {
		this.prodId = prodId;
		this.strikeSerial = strikeSerial;
	}

	@Column(name = "PROD_ID", nullable = false, length = 20)
	@AnnoMethodTree(order =10, init=true)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	@Column(name = "STRIKE_SERIAL", nullable = false, precision = 10, scale = 0)
	@AnnoMethodTree(order =20, init=true)
	public long getStrikeSerial() {
		return this.strikeSerial;
	}

	public void setStrikeSerial(long strikeSerial) {
		this.strikeSerial = strikeSerial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HifiveStrikeId))
			return false;
		HifiveStrikeId castOther = (HifiveStrikeId) other;

		return ((this.getProdId() == castOther.getProdId()) || (this.getProdId() != null
				&& castOther.getProdId() != null && this.getProdId().equals(castOther.getProdId())))
				&& (this.getStrikeSerial() == castOther.getStrikeSerial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProdId() == null ? 0 : this.getProdId().hashCode());
		result = 37 * result + (int) this.getStrikeSerial();
		return result;
	}

}
