package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.eugenefe.enums.EMaturity;
import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * HifiveSwapIr generated by hbm2java
 */
@Entity
@Table(name = "HIFIVE_SWAP_IR")
@AnnoNavigationFilter
public class HifiveSwapIr implements java.io.Serializable {

	private String prodId;
	private IrCurve irCurve;
	private Hifive hifive;
	private EMaturity paymentTerm;
	private BigDecimal spread;
	private BigDecimal fixedRate;

	public HifiveSwapIr() {
	}

	public HifiveSwapIr(IrCurve irCurve, Hifive hifive, EMaturity paymentTerm) {
		this.irCurve = irCurve;
		this.hifive = hifive;
		this.paymentTerm = paymentTerm;
	}

	public HifiveSwapIr(IrCurve irCurve, Hifive hifive, EMaturity paymentTerm, BigDecimal spread, BigDecimal fixedRate) {
		this.irCurve = irCurve;
		this.hifive = hifive;
		this.paymentTerm = paymentTerm;
		this.spread = spread;
		this.fixedRate = fixedRate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "hifive"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PROD_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@AnnoMethodTree(order=11, init=true)
	public Hifive getHifive() {
		return this.hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_IRC_ID", nullable = false)
	@AnnoMethodTree(order=20, init=true)
	public IrCurve getIrCurve() {
		return this.irCurve;
	}

	public void setIrCurve(IrCurve irCurve) {
		this.irCurve = irCurve;
	}



////	@ManyToOne(fetch = FetchType.LAZY)
//	@Column(name = "PAYMENT_TERM", nullable = false, insertable = false, updatable = false)
//	@Enumerated
//	@AnnoMethodTree(order=30, init=true)
//	public EMaturity getPaymentTerm() {
//		return this.paymentTerm;
//	}
//
//	public void setPaymentTerm(EMaturity paymentTerm) {
//		this.paymentTerm = paymentTerm;
//	}

	@Column(name = "SPREAD", precision = 10, scale = 4)
	@AnnoMethodTree(order=40, init=true, align="right")
	public BigDecimal getSpread() {
		return this.spread;
	}

	public void setSpread(BigDecimal spread) {
		this.spread = spread;
	}

	@Column(name = "FIXED_RATE", precision = 10, scale = 4)
	@AnnoMethodTree(order=50, init=true, align="right")
	public BigDecimal getFixedRate() {
		return this.fixedRate;
	}

	public void setFixedRate(BigDecimal fixedRate) {
		this.fixedRate = fixedRate;
	}

}
