package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

//import org.hibernate.annotations.Entity;
import org.hibernate.annotations.FilterJoinTable;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.MarketVariableType;

/**
 * InterateRateHis generated by hbm2java
 */
@Entity
@Table(name = "INT_RATE_HIS")
@AnnoNavigationFilter
public class IntRateHis implements java.io.Serializable, IMarketVariableHis {

	private IntRateHisId id;
	private Basedate basedate;
	private IntRate interestRate;
	private BigDecimal intRate;

	public IntRateHis() {
	}

	public IntRateHis(IntRateHisId id, Basedate basedate, IntRate interestRate) {
		this.id = id;
		this.basedate = basedate;
		this.interestRate = interestRate;
	}

	public IntRateHis(IntRateHisId id, Basedate basedate, IntRate interestRate, BigDecimal intRate) {
		this.id = id;
		this.basedate = basedate;
		this.interestRate = interestRate;
		this.intRate = intRate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "irId", column = @Column(name = "IR_ID", nullable = false, length = 20)) })
	@NotNull
	@AnnoMethodTree(order=10, init=true)
	public IntRateHisId getId() {
		return this.id;
	}

	public void setId(IntRateHisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BSSD", nullable = false, insertable = false, updatable = false)
	@NotNull
//	@FilterJoinTable(name="filterBtwnDate" , condition = "id.bssd between :stBssd and : endBssd")
	@AnnoMethodTree(order=10, init=false)
	public Basedate getBasedate() {
		return this.basedate;
	}

	public void setBasedate(Basedate basedate) {
		this.basedate = basedate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IR_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	@AnnoMethodTree(order=10, init=false)
	public IntRate getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(IntRate interestRate) {
		this.interestRate = interestRate;
	}

	@Column(name = "INT_RATE", precision = 10, scale = 4)
	@AnnoMethodTree(order=10, init=true)
	public BigDecimal getIntRate() {
		return this.intRate;
	}

	public void setIntRate(BigDecimal intRate) {
		this.intRate = intRate;
	}
	
//	******************Override Method**********************
	@Override
	@Transient
	public String getBssd() {
		return getBasedate().getBssd();
	}

	@Override
	@Transient
	public String getMvId() {
		return getInterestRate().getMvId();
	}

	@Override
	@Transient
	public String getMvName() {
		return getInterestRate().getMvName();
	}
	@Override
	@Transient
	public String getMvType() {
		return MarketVariableType.INT_RATE.getType();
	}
//	public ProductType getMvType() {
//		return ProductType.BOND;
//	}
	@Override
	@Transient
	public double getCurrentPrice() {
		return getIntRate().doubleValue();
	}

	@Override
	@Transient
	public double getBeforePrice() {
		return getIntRate().doubleValue();
	}
	
	@Override
	@Transient
	public BigDecimal getStockBeta() {
		return null;
	}
	@Transient
	@Override
	public BigDecimal getAdjDuration() {
		// TODO Auto-generated method stub
		return null;
	}
	@Transient
	@Override
	public BigDecimal getMdDuration() {
		// TODO Auto-generated method stub
		return null;
	}
	@Transient
	@Override
	public BigDecimal getEffectDuration() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Transient
	@Override
	public BigDecimal getAdjConvexity() {
		// TODO Auto-generated method stub
		return null;
	}

	@Transient
	@Override
	public BigDecimal getEffectConvexity() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Transient
	@Override
	public BigDecimal getVolume() {
		// TODO Auto-generated method stub
		return null;
	}

	@Transient
	@Override
	public BigDecimal getVolumeAmt() {
		// TODO Auto-generated method stub
		return null;
	}	
	
	
}
