package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.eugenefe.enums.EMaturity;

/**
 * IrCurveHis generated by hbm2java
 */
@Entity
@Table(name = "IR_CURVE_HIS")
public class IrCurveHis implements java.io.Serializable {

	private IrCurveHisId id;
	private Basedate basedate;
	private IrCurve irCurve;
	private EMaturity maturity;
	private BigDecimal intRate;

	public IrCurveHis() {
	}

	public IrCurveHis(IrCurveHisId id, Basedate basedate, EMaturity maturity, IrCurve irCurve) {
		this.id = id;
		this.basedate = basedate;
		this.maturity = maturity;
		this.irCurve = irCurve;
	}

	public IrCurveHis(IrCurveHisId id, Basedate basedate, EMaturity maturity, IrCurve irCurve, BigDecimal intRate) {
		this.id = id;
		this.basedate = basedate;
		this.maturity = maturity;
		this.irCurve = irCurve;
		this.intRate = intRate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "maturityId", column = @Column(name = "MATURITY_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "ircId", column = @Column(name = "IRC_ID", nullable = false, length = 20)) })
	@NotNull
	public IrCurveHisId getId() {
		return this.id;
	}

	public void setId(IrCurveHisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BSSD", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Basedate getBasedate() {
		return this.basedate;
	}

	public void setBasedate(Basedate basedate) {
		this.basedate = basedate;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "MATURITY_ID", nullable = false, insertable = false, updatable = false)
	@Column(name = "MATURITY_ID", nullable = false, insertable = false, updatable = false)
	@Enumerated
	@NotNull
	public EMaturity getMaturity() {
		return this.maturity;
	}

	public void setMaturity(EMaturity maturity) {
		this.maturity = maturity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IRC_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public IrCurve getIrCurve() {
		return this.irCurve;
	}

	public void setIrCurve(IrCurve irCurve) {
		this.irCurve = irCurve;
	}

	@Column(name = "INT_RATE", precision = 10, scale = 4)
	public BigDecimal getIntRate() {
		return this.intRate;
	}

	public void setIntRate(BigDecimal intRate) {
		this.intRate = intRate;
	}

}
