package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * IrCurveHisId generated by hbm2java
 */
@Embeddable
public class IrCurveHisId implements java.io.Serializable {

	private String bssd;
	private String ircId;
	private String maturityId;

	public IrCurveHisId() {
	}

	public IrCurveHisId(String bssd, String maturityId, String ircId) {
		this.bssd = bssd;
		this.maturityId = maturityId;
		this.ircId = ircId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "MATURITY_ID", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getMaturityId() {
		return this.maturityId;
	}

	public void setMaturityId(String maturityId) {
		this.maturityId = maturityId;
	}

	@Column(name = "IRC_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getIrcId() {
		return this.ircId;
	}

	public void setIrcId(String ircId) {
		this.ircId = ircId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IrCurveHisId))
			return false;
		IrCurveHisId castOther = (IrCurveHisId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getMaturityId() == castOther.getMaturityId()) || (this.getMaturityId() != null
						&& castOther.getMaturityId() != null && this.getMaturityId().equals(castOther.getMaturityId())))
				&& ((this.getIrcId() == castOther.getIrcId()) || (this.getIrcId() != null
						&& castOther.getIrcId() != null && this.getIrcId().equals(castOther.getIrcId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getMaturityId() == null ? 0 : this.getMaturityId().hashCode());
		result = 37 * result + (getIrcId() == null ? 0 : this.getIrcId().hashCode());
		return result;
	}

}
