package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OptionHisId generated by hbm2java
 */
@Embeddable
public class OptionHisId implements java.io.Serializable {

	private String bssd;
	private String optionId;

	public OptionHisId() {
	}

	public OptionHisId(String bssd, String optionId) {
		this.bssd = bssd;
		this.optionId = optionId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "OPTION_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getOptionId() {
		return this.optionId;
	}

	public void setOptionId(String optionId) {
		this.optionId = optionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OptionHisId))
			return false;
		OptionHisId castOther = (OptionHisId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getOptionId() == castOther.getOptionId()) || (this.getOptionId() != null
						&& castOther.getOptionId() != null && this.getOptionId().equals(castOther.getOptionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getOptionId() == null ? 0 : this.getOptionId().hashCode());
		return result;
	}

}
