package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "OPTIONS")
@PrimaryKeyJoinColumn(name="OPTION_ID")
public class Options extends MarketVariableJoin implements java.io.Serializable {

//	private String optionId;
	private MarketVariable underlying;
//	private MarketVariable marketVariableByMvId;
	private String optionName;
	private String optionType;
	private String exoticType;
	private String issueDate;
	private String maturityDate;
	private BigDecimal strikePrice;
	private Long multiplier;
	private BigDecimal conversionRatio;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;
	private String issuerId;
	private String exchangeId;
	private Set<OptionHis> optionHises = new HashSet<OptionHis>(0);

	public Options() {
	}

	public Options(MarketVariable marketVariableByUnderlyingId, String optionName,
			String optionType, String exoticType, String issueDate, String maturityDate, BigDecimal strikePrice,
			Long multiplier, BigDecimal conversionRatio, String sourceTable, String userName, String lastUpdated,
			BigDecimal versionNo, String issuerId, String exchangeId, Set<OptionHis> optionHises) {
		this.underlying = marketVariableByUnderlyingId;
		this.optionName = optionName;
		this.optionType = optionType;
		this.exoticType = exoticType;
		this.issueDate = issueDate;
		this.maturityDate = maturityDate;
		this.strikePrice = strikePrice;
		this.multiplier = multiplier;
		this.conversionRatio = conversionRatio;
		this.sourceTable = sourceTable;
		this.userName = userName;
		this.lastUpdated = lastUpdated;
		this.versionNo = versionNo;
		this.issuerId = issuerId;
		this.exchangeId = exchangeId;
		this.optionHises = optionHises;
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "marketVariableByMvId"))
//	@Id
//	@GeneratedValue(generator = "generator")
//	@Column(name = "OPTION_ID", unique = true, nullable = false, length = 20)
//	@Size(max = 20)
//	public String getOptionId() {
//		return this.optionId;
//	}
//
//	public void setOptionId(String optionId) {
//		this.optionId = optionId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNDERLYING_ID")
	public MarketVariable getUnderlying() {
		return this.underlying;
	}

	public void setUnderlying(MarketVariable underlying) {
		this.underlying = underlying;
	}

//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	@NotNull
//	@Size(max = 20)
//	public MarketVariable getMarketVariableByMvId() {
//		return this.marketVariableByMvId;
//	}
//
//	public void setMarketVariableByMvId(MarketVariable marketVariableByMvId) {
//		this.marketVariableByMvId = marketVariableByMvId;
//	}

	@Column(name = "OPTION_NAME", length = 50)
	@Size(max = 50)
	public String getOptionName() {
		return this.optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	@Column(name = "OPTION_TYPE", length = 10)
	@Size(max = 10)
	public String getOptionType() {
		return this.optionType;
	}

	public void setOptionType(String optionType) {
		this.optionType = optionType;
	}

	@Column(name = "EXOTIC_TYPE", length = 10)
	@Size(max = 10)
	public String getExoticType() {
		return this.exoticType;
	}

	public void setExoticType(String exoticType) {
		this.exoticType = exoticType;
	}

	@Column(name = "ISSUE_DATE", length = 8)
	@Size(max = 8)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "MATURITY_DATE", length = 8)
	@Size(max = 8)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;
	}

	@Column(name = "STRIKE_PRICE", precision = 10, scale = 4)
	public BigDecimal getStrikePrice() {
		return this.strikePrice;
	}

	public void setStrikePrice(BigDecimal strikePrice) {
		this.strikePrice = strikePrice;
	}

	@Column(name = "MULTIPLIER", precision = 10, scale = 0)
	public Long getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(Long multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "CONVERSION_RATIO", precision = 10, scale = 4)
	public BigDecimal getConversionRatio() {
		return this.conversionRatio;
	}

	public void setConversionRatio(BigDecimal conversionRatio) {
		this.conversionRatio = conversionRatio;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	@Size(max = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	@Size(max = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	@Size(max = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	@Column(name = "ISSUER_ID", length = 20)
	@Size(max = 20)
	public String getIssuerId() {
		return this.issuerId;
	}

	public void setIssuerId(String issuerId) {
		this.issuerId = issuerId;
	}

	@Column(name = "EXCHANGE_ID", length = 20)
	@Size(max = 20)
	public String getExchangeId() {
		return this.exchangeId;
	}

	public void setExchangeId(String exchangeId) {
		this.exchangeId = exchangeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "options")
	public Set<OptionHis> getOptionHises() {
		return this.optionHises;
	}

	public void setOptionHises(Set<OptionHis> optionHises) {
		this.optionHises = optionHises;
	}

}
