package com.eugenefe.entity;

// Generated 2014. 2. 10 ¿ÀÈÄ 5:51:10 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PortfolioCompo generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class PortfolioCompoId implements java.io.Serializable {

	private String portfolioId;
	private String childPortId;

	public PortfolioCompoId() {
	}

	public PortfolioCompoId(String portfolioId, String childPortId) {
		this.portfolioId = portfolioId;
		this.childPortId = childPortId;
	}



	@Column(name = "PORTFOLIO_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order =10, init=true)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "CHILD_PORTFOLIO_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order =20, init=true)
	public String getChildPortId() {
		return childPortId;
	}

	public void setChildPortId(String childPortId) {
		this.childPortId = childPortId;
	}
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortfolioCompoId))
			return false;
		PortfolioCompoId castOther = (PortfolioCompoId) other;

		return ((this.getPortfolioId() == castOther.getPortfolioId()) || (this.getPortfolioId() != null
				&& castOther.getPortfolioId() != null && this.getPortfolioId().equals(castOther.getPortfolioId())))
				&& ((this.getChildPortId()) == castOther.getChildPortId() || (this.getChildPortId() != null
						&& castOther.getChildPortId() != null && this.getChildPortId().equals(castOther.getChildPortId())));
	}


	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPortfolioId() == null ? 0 : this.getPortfolioId().hashCode());
		result = 37 * result + (getChildPortId() == null ? 0 : this.getChildPortId().hashCode());
		return result;
	}


}
