package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PortfolioReturnId generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class PortfolioReturnId implements java.io.Serializable {

	private String bssd;
	private String portId;

	public PortfolioReturnId() {
	}

	public PortfolioReturnId(String bssd, String portId) {
		this.bssd = bssd;
		this.portId = portId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	@AnnoMethodTree(order = 10, init=true)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "PORT_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	@AnnoMethodTree(order = 20, init=true)
	public String getPortId() {
		return this.portId;
	}

	public void setPortId(String portId) {
		this.portId = portId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortfolioReturnId))
			return false;
		PortfolioReturnId castOther = (PortfolioReturnId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getPortId() == castOther.getPortId()) || (this.getPortId() != null
						&& castOther.getPortId() != null && this.getPortId().equals(castOther.getPortId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getPortId() == null ? 0 : this.getPortId().hashCode());
		return result;
	}

}
