package com.eugenefe.entity;

// Generated Apr 16, 2013 7:33:55 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.log.Log;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

import sun.util.logging.resources.logging;

/**
 * Portfolio generated by hbm2java
 */
@Entity
@Table(name = "PORTFOLIO")
@AnnoNavigationFilter
public class Portfolio implements IPortfolio, Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String portId;
	private Portfolio parentPortfolio;
	private Portfolio replicatePortfolio;
	private String portName;
	private String groupId;
	private String level1;
	private String level2;
	private String level3;
	private String level4;
	private String level5;
	private BigDecimal weight;
	// private Set<Portfolio> childPortfolios = new HashSet<Portfolio>(0);
	// private Set<IPortfolio> childPortfolios = new HashSet<IPortfolio>(0);
	private List<Portfolio> childPortfolios = new ArrayList<Portfolio>();
	private List<Portfolio> copiedPortfolioList = new ArrayList<Portfolio>();
	
	private Map<Portfolio, Double> subPortfolioMap = new HashMap<Portfolio, Double>();
	private List<PortfolioCompo> portfolioCompoList = new ArrayList<PortfolioCompo>();
	private List<PortfolioDefineNew> portDefineList = new ArrayList<PortfolioDefineNew>();

	
	private List<PortfolioReturn> portfolioReturns = new ArrayList<PortfolioReturn>();

	// private List<PositionReturn> positions = new ArrayList<PositionReturn>();

	public Portfolio() {
	}
	
	public Portfolio(String portId) {
		this.portId = portId;
	}

	public Portfolio(String portId, String portName) {
		this.portId = portId;
		this.portName = portName;
	}

	@Id
	@Column(name = "PORT_ID", nullable = false, length = 50)
	@AnnoMethodTree(order=10, init=true)
	public String getPortId() {
		return this.portId;
	}

	public void setPortId(String portId) {
		this.portId = portId;
	}
	@Column(name = "PORT_NAME", length = 50)
	@AnnoMethodTree(order=20, init=true)
	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_PORT_ID")
	@AnnoMethodTree(order=30, init=false)
	public Portfolio getParentPortfolio() {
		return this.parentPortfolio;
	}

	public void setParentPortfolio(Portfolio parentPortfolio) {
		this.parentPortfolio = parentPortfolio;
	}

//	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPLICATE_PORT")
	@AnnoMethodTree(order=31, init=false)
	public Portfolio getReplicatePortfolio() {
		return replicatePortfolio;
	}

	public void setReplicatePortfolio(Portfolio replicatePortfolio) {
		this.replicatePortfolio = replicatePortfolio;
	}

	@Column(name = "GROUP_ID", length = 20)
	@AnnoMethodTree(order=40, init=true)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "LEVEL1", length = 20)
	@AnnoMethodTree(order=50, init=true)
	public String getLevel1() {
		return this.level1;
	}

	public void setLevel1(String level1) {
		this.level1 = level1;
	}

	@Column(name = "LEVEL2", length = 20)
	@AnnoMethodTree(order=51, init=true)
	public String getLevel2() {
		return this.level2;
	}

	public void setLevel2(String level2) {
		this.level2 = level2;
	}

	@Column(name = "LEVEL3", length = 20)
	@AnnoMethodTree(order=52, init=true)
	public String getLevel3() {
		return this.level3;
	}

	public void setLevel3(String level3) {
		this.level3 = level3;
	}

	@Column(name = "LEVEL4", length = 20)
	@AnnoMethodTree(order=53, init=true)
	public String getLevel4() {
		return this.level4;
	}

	public void setLevel4(String level4) {
		this.level4 = level4;
	}

	@Column(name = "LEVEL5", length = 20)
	@AnnoMethodTree(order=54, init=true)
	public String getLevel5() {
		return this.level5;
	}

	public void setLevel5(String level5) {
		this.level5 = level5;
	}

	
	@Column(name = "WEIGHT")
	@AnnoMethodTree(order=55, init=true)
	public BigDecimal getWeight() {
		return weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentPortfolio",
	// targetEntity=Portfolio.class)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentPortfolio")
//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "parentPortfolio")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE, CascadeType.DELETE_ORPHAN})
	@AnnoMethodTree(order=60, init=false, type=EColumnType.List)
	public List<Portfolio> getChildPortfolios() {
//		System.out.println("Call DB");
		return this.childPortfolios;
	}

	public void setChildPortfolios(List<Portfolio> childPortfolios) {
		this.childPortfolios = childPortfolios;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentPortfolio",
	// targetEntity=Portfolio.class)
	// public Set<IPortfolio> getChildPortfolios() {
	// return this.childPortfolios;
	// }
	//
	// public void setChildPortfolios(Set<IPortfolio> childPortfolios) {
	// this.childPortfolios = childPortfolios;
	// }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "replicatePortfolio")
	@Cascade(CascadeType.DELETE)
	public List<Portfolio> getCopiedPortfolioList() {
		return copiedPortfolioList;
	}

	public void setCopiedPortfolioList(List<Portfolio> copiedPortfolioList) {
		this.copiedPortfolioList = copiedPortfolioList;
	}

	@Transient
//	@ElementCollection
//	@MapKeyJoinColumn(name="CHILD_PORTFOLIO_ID")
//	@JoinTable(name="PORTFOLIO_COMPO"
//				, joinColumns=@JoinColumn(name="PORTFOLIO_ID")
//	)
//	@Column(name="PORT_WEIGHT")
	public Map<Portfolio, Double> getSubPortfolioMap() {
		return subPortfolioMap;
	}

	public void setSubPortfolioMap(Map<Portfolio, Double> subPortfolioMap) {
		this.subPortfolioMap = subPortfolioMap;
	}
	
//	@Transient
//	public List<Map.Entry<Portfolio, Double>> getSubPortfolioList(){
//		return new ArrayList<Map.Entry<Portfolio, Double>>(subPortfolioMap.entrySet());
//	}

	
	@OneToMany(mappedBy="portfolio")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE, CascadeType.DELETE_ORPHAN})
	public List<PortfolioCompo> getPortfolioCompoList() {
		return portfolioCompoList;
	}

	public void setPortfolioCompoList(List<PortfolioCompo> portfolioCompoList) {
		this.portfolioCompoList = portfolioCompoList;
	}

	@OneToMany(mappedBy="portfolio")	
	public List<PortfolioDefineNew> getPortDefineList() {
		return portDefineList;
	}



	public void setPortDefineList(List<PortfolioDefineNew> portDefineList) {
		this.portDefineList = portDefineList;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portfolio")
	@AnnoMethodTree(order=70, init=false, type= EColumnType.List)
	public List<PortfolioReturn> getPortfolioReturns() {
		return portfolioReturns;
	}

	public void setPortfolioReturns(List<PortfolioReturn> portfolioReturns) {
		this.portfolioReturns = portfolioReturns;
	}

	// @ManyToMany(fetch = FetchType.LAZY)
	// @FilterJoinTable(name= "filterCurrentDatePortfolioDetail", condition
	// ="BSSD = :currentDate")
	// @JoinTable( name="PORTFOLIO_DETAIL"
	// ,joinColumns={@JoinColumn(name="PORT_ID")}
	// ,inverseJoinColumns={@JoinColumn(name="BSSD",
	// referencedColumnName="BSSD"),
	// @JoinColumn(name="POS_ID", referencedColumnName="POS_ID")
	// })
	// public Set<PositionReturn> getPositions() {
	// return positions;
	// }
	//
	// public void setPositions(Set<PositionReturn> positions) {
	// this.positions = positions;
	// }

	@Override
	@Transient
	public void add(IPortfolio port) {
		// TODO Auto-generated method stub

	}

	@Override
	@Transient
	public void remove(IPortfolio port) {
		// TODO Auto-generated method stub

	}

	@Override
	@Transient
	public List<IPortfolio> getChildren() {
		List<IPortfolio> rst = new ArrayList<IPortfolio>();
		// temp = getChildren();
		// temp.addAll(this.getpo
		return rst;
	}

	@Override
	@Transient
	public IPortfolio getChildren(String portId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	@Transient
	public double getPresValue() {
		return 0;
	}

	@Override
	@Transient
	public double getCalcuatedPv() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	@Transient
	public String getStringId() {
		return getPortId();
	}

	@Override
	@Transient
	public String getName() {
		return getPortName() + "AAA";
	}

	// @Override
	// @Transient
	// public Set<IPortfolio> getReturnInfo() {
	// return getPortfolioReturns();
	// }
	
	
	@Override
	@Transient
	public double getDailyReturn() {
		if (getPortfolioReturns().size() != 0) {
			return getPortfolioReturns().get(0).getDailyReturn().doubleValue();
		}
		return 0;
	}

	@Override
	@Transient
	public boolean equals(Object obj) {
		if(obj == null){
			return false;
		}
		if (obj == this) {
			return true;
		}
		if(obj.getClass().toString().endsWith("String")){
			System.out.println("Check 1: " + obj);
			return this.getPortId().equals(obj);
		}
		System.out.println("Check : " + obj.getClass().toString() + obj.getClass());
		Portfolio guest = (Portfolio) obj;
		return this.getPortId().equals(guest.getPortId());
	}

	@Override
	@Transient
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((portId == null) ? 0 : portId.hashCode());
		result = prime * result + ((portName == null) ? 0 : portName.hashCode());
		return result;
	}

}
