package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.eugenefe.entity.PositionReturnId;


/**
 * PositionReturn generated by hbm2java
 */
@Entity
@Table(name = "POSITION_HIS" , schema="TAKION99")
public class PositionHis implements java.io.Serializable {

	private PositionReturnId id;
	private Position position;
	private BigDecimal presValue;
	private BigDecimal holdingQty;
	private BigDecimal parAmt;
	private BigDecimal bookAmt;
	private BigDecimal refParAmt;
	private BigDecimal refBookAmt;
	private BigDecimal weekBookAmt;
	private BigDecimal monthBookAmt;
	private BigDecimal quartBookAmt;
	private BigDecimal annuBookAmt;
	private BigDecimal fiscalBookAmt;
	private BigDecimal dailyReturn;
	private BigDecimal weeklyReturn;
	private BigDecimal monthlyReturn;
	private BigDecimal quartlyReturn;
	private BigDecimal annualReturn;
	private BigDecimal fiscalReturn;
	private BigDecimal unitPrice1;
	private BigDecimal unitPrice2;
	
	public PositionHis() {
	}

	public PositionHis(PositionReturnId id) {
		this.id= id;
	}
	public PositionHis(String bssd, String posId) {
		this.id= new PositionReturnId(bssd, posId);
	}
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "posId", column = @Column(name = "POS_ID", nullable = false, length = 50)) })
	@NotNull
	public PositionReturnId getId() {
		return this.id;
	}

	public void setId(PositionReturnId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name ="POS_ID", insertable=false, updatable=false )
	public Position getPosition() {
		return position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@Column(name = "PV", scale = 4)
	public BigDecimal getPresValue() {
		return this.presValue;
	}
	public void setPresValue(BigDecimal pv) {
		this.presValue = pv;
	}
	
	@Column(name = "HOLDING_QTY")
	public BigDecimal getHoldingQty() {
		return holdingQty;
	}

	public void setHoldingQty(BigDecimal holdingQty) {
		this.holdingQty = holdingQty;
	}

	@Column(name = "BOOK_AMT", scale = 4)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}
	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;
	}
	
	
	@Column(name = "PAR_AMT", scale = 4)
	public BigDecimal getParAmt() {
		return parAmt;
	}

	public void setParAmt(BigDecimal parAmt) {
		this.parAmt = parAmt;
	}
	@Column(name = "REF_PAR_AMT", scale = 4)
	public BigDecimal getRefParAmt() {
		return refParAmt;
	}

	public void setRefParAmt(BigDecimal refParAmt) {
		this.refParAmt = refParAmt;
	}
	@Column(name = "REF_BOOK_AMT", scale = 4)
	public BigDecimal getRefBookAmt() {
		return refBookAmt;
	}

	public void setRefBookAmt(BigDecimal refBookAmt) {
		this.refBookAmt = refBookAmt;
	}

	@Column(name = "WEEK_BOOK_AMT", scale = 4)
	public BigDecimal getWeekBookAmt() {
		return weekBookAmt;
	}

	public void setWeekBookAmt(BigDecimal weekBookAmt) {
		this.weekBookAmt = weekBookAmt;
	}
	@Column(name = "MONTH_BOOK_AMT", scale = 4)
	public BigDecimal getMonthBookAmt() {
		return monthBookAmt;
	}

	public void setMonthBookAmt(BigDecimal monthBookAmt) {
		this.monthBookAmt = monthBookAmt;
	}

	@Column(name = "QUART_BOOK_AMT", scale = 4)
	public BigDecimal getQuartBookAmt() {
		return quartBookAmt;
	}

	public void setQuartBookAmt(BigDecimal quartBookAmt) {
		this.quartBookAmt = quartBookAmt;
	}
	@Column(name = "ANNU_BOOK_AMT", scale = 4)
	public BigDecimal getAnnuBookAmt() {
		return annuBookAmt;
	}

	public void setAnnuBookAmt(BigDecimal annuBookAmt) {
		this.annuBookAmt = annuBookAmt;
	}
	@Column(name = "FISCAL_BOOK_AMT", scale = 4)
	public BigDecimal getFiscalBookAmt() {
		return fiscalBookAmt;
	}

	public void setFiscalBookAmt(BigDecimal fiscalBookAmt) {
		this.fiscalBookAmt = fiscalBookAmt;
	}

	@Column(name = "DAILY_RETURN", scale = 4)
	public BigDecimal getDailyReturn() {
		return this.dailyReturn;
	}

	public void setDailyReturn(BigDecimal dailyReturn) {
		this.dailyReturn = dailyReturn;
	}
	
	@Column(name = "WEEKLY_RETURN", scale = 4)
	public BigDecimal getWeeklyReturn() {
		return weeklyReturn;
	}

	public void setWeeklyReturn(BigDecimal weeklyReturn) {
		this.weeklyReturn = weeklyReturn;
	}

	@Column(name = "MONTHLY_RETURN", scale = 4)
	public BigDecimal getMonthlyReturn() {
		return this.monthlyReturn;
	}

	public void setMonthlyReturn(BigDecimal monthlyReturn) {
		this.monthlyReturn = monthlyReturn;
	}

	@Column(name = "QUARTLY_RETURN", scale = 4)
	public BigDecimal getQuartlyReturn() {
		return this.quartlyReturn;
	}

	public void setQuartlyReturn(BigDecimal quartlyReturn) {
		this.quartlyReturn = quartlyReturn;
	}

	@Column(name = "ANNUAL_RETURN", scale = 4)
	public BigDecimal getAnnualReturn() {
		return this.annualReturn;
	}

	public void setAnnualReturn(BigDecimal annualReturn) {
		this.annualReturn = annualReturn;
	}

	@Column(name = "FISCAL_RETURN", scale = 4)
	public BigDecimal getFiscalReturn() {
		return this.fiscalReturn;
	}

	public void setFiscalReturn(BigDecimal fiscalReturn) {
		this.fiscalReturn = fiscalReturn;
	}
	@Column(name = "UNIT_PRICE1", scale = 4)
	public BigDecimal getUnitPrice1() {
		return unitPrice1;
	}

	public void setUnitPrice1(BigDecimal unitPrice1) {
		this.unitPrice1 = unitPrice1;
	}
	
	@Column(name = "UNIT_PRICE2", scale = 4)
	public BigDecimal getUnitPrice2() {
		return unitPrice2;
	}

	public void setUnitPrice2(BigDecimal unitPrice2) {
		this.unitPrice2 = unitPrice2;
	}	
}
