package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PositionReturnId generated by hbm2java
 */
@Embeddable
public class PositionPropertyId implements java.io.Serializable {

	private String posId;
	private String propId;

	public PositionPropertyId() {
	}

	public PositionPropertyId(String propId, String posId) {
		this.posId = posId;
		this.propId = propId;
	}

	@Column(name = "PROP_iD", nullable = false)
	@NotNull
	public String getPropId() {
		return propId;
	}

	public void setPropId(String propId) {
		this.propId = propId;
	}	

	@Column(name = "POS_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPosId() {
		return this.posId;
	}



	public void setPosId(String posId) {
		this.posId = posId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PositionPropertyId))
			return false;
		PositionPropertyId castOther = (PositionPropertyId) other;

		return ((this.getPropId() == castOther.getPropId()) || (this.getPropId() != null && castOther.getPropId() != null && this
				.getPropId().equals(castOther.getPropId())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null
						&& castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPropId() == null ? 0 : this.getPropId().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		return result;
	}

}
