package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PositionRiskId generated by hbm2java
 */
@Embeddable
public class PositionRiskId implements java.io.Serializable {

	private String bssd;
	private String posId;
	private String varGenId;

	public PositionRiskId() {
	}

	public PositionRiskId(String bssd, String posId, String varGenId) {
		this.bssd = bssd;
		this.posId = posId;
		this.varGenId = varGenId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "POS_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	@Column(name = "VAR_GEN_ID", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getVarGenId() {
		return this.varGenId;
	}

	public void setVarGenId(String varGenId) {
		this.varGenId = varGenId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PositionRiskId))
			return false;
		PositionRiskId castOther = (PositionRiskId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null
						&& castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())))
				&& ((this.getVarGenId() == castOther.getVarGenId()) || (this.getVarGenId() != null
						&& castOther.getVarGenId() != null && this.getVarGenId().equals(castOther.getVarGenId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		result = 37 * result + (getVarGenId() == null ? 0 : this.getVarGenId().hashCode());
		return result;
	}

}
