package com.eugenefe.entity;

// Generated Apr 16, 2013 7:33:55 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION")
@AnnoNavigationFilter
public class Position implements IPortfolio, Serializable {

	private String posId;
	private String posName;
	private String posSide;
	private MarketVariable product;
	private Counterparty counterparty;
	private Bizunit fund;
	private String txType;
	private String currency;
	private String initTxDate;
	private String lastTxDate;
	private BigDecimal initTxPrice;
	private BigDecimal initFeeAmt;
	private BigDecimal initTxAmt;
	private BigDecimal holdingQty;
	private BigDecimal posAmt;
	
//	private Map<String, List<PositionProperty>> propertyMap = new HashMap<String, List<PositionProperty>>();
	private List<PositionProperty> propertyList = new ArrayList<PositionProperty>();
	private Map<HierarchyProperty, String> propMap = new HashMap<HierarchyProperty, String>();
	public Position() {
	}

	public Position(String posId) {
		this.posId = posId;
	}

	public Position(String posId, String posName, String initTxDate, String lastTxDate, BigDecimal initTxPrice,
			BigDecimal initFeeAmt, BigDecimal initTxAmt, BigDecimal holdingQty) {
		this.posId = posId;
		this.posName = posName;
		this.initTxDate = initTxDate;
		this.lastTxDate = lastTxDate;
		this.initTxPrice = initTxPrice;
		this.initFeeAmt = initFeeAmt;
		this.initTxAmt = initTxAmt;
		this.holdingQty = holdingQty;
	}

	@Id
	@Column(name = "POS_ID", nullable = false, length = 50)
	@AnnoMethodTree(order=10, init=true, aggregatable=true)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	@Column(name = "POS_NAME", length = 50)
	@AnnoMethodTree(order=11, init=true, aggregatable=true)
	public String getPosName() {
		return this.posName;
	}

	public void setPosName(String posName) {
		this.posName = posName;
	}
	
	@Column(name = "POS_SIDE", length = 20)
	@AnnoMethodTree(order=12, init=true, aggregatable=true)
	public String getPosSide() {
		return posSide;
	}

	public void setPosSide(String posSide) {
		this.posSide = posSide;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID")
	@AnnoMethodTree(order=20, init=false, aggregatable=true)
	public MarketVariable getProduct() {
//		System.out.println("In the GetProduct");
		return product;
	}

	public void setProduct(MarketVariable product) {
		this.product = product;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "COUNTERTPARTY_ID")
	@JoinColumn(name = "COUNTERPARTY_ID")
	@AnnoMethodTree(order=30, init=false, aggregatable=true)
	public Counterparty getCounterparty() {
		return counterparty;
	}

	public void setCounterparty(Counterparty counterparty) {
		this.counterparty = counterparty;
	}


	

	//	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUND_ID")
	@AnnoMethodTree(order=40, init=false, aggregatable=true)
	public Bizunit getFund() {
		return fund;
	}

	public void setFund(Bizunit fund) {
		this.fund = fund;
	}


	@Column(name = "TX_TYPE", length = 20)
	@AnnoMethodTree(order=45, init=true, aggregatable=true)
	public String getTxType() {
		return txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;
	}
	
	@Column(name = "CURR_CD", length = 20)
	@AnnoMethodTree(order=46, init=true, aggregatable=true)
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}
	
	@Column(name = "INIT_TX_DATE", length = 8)
	@AnnoMethodTree(order=50, init=true, aggregatable=true)
	public String getInitTxDate() {
		return this.initTxDate;
	}

	public void setInitTxDate(String initTxDate) {
		this.initTxDate = initTxDate;
	}

	
	
	@Column(name = "LAST_TX_DATE", length = 8)
	@AnnoMethodTree(order=51, init=true, aggregatable=true)
	public String getLastTxDate() {
		return this.lastTxDate;
	}

	public void setLastTxDate(String lastTxDate) {
		this.lastTxDate = lastTxDate;
	}

	@Column(name = "INIT_TX_PRICE", scale = 4)
	@AnnoMethodTree(order=52, init=true)
	public BigDecimal getInitTxPrice() {
		return this.initTxPrice;
	}

	public void setInitTxPrice(BigDecimal initTxPrice) {
		this.initTxPrice = initTxPrice;
	}

	@Column(name = "INIT_FEE_AMT", scale = 4)
	@AnnoMethodTree(order=53, init=true)
	public BigDecimal getInitFeeAmt() {
		return this.initFeeAmt;
	}

	public void setInitFeeAmt(BigDecimal initFeeAmt) {
		this.initFeeAmt = initFeeAmt;
	}

	@Column(name = "INIT_TX_AMT", scale = 4)
	@AnnoMethodTree(order=54, init=true)
	public BigDecimal getInitTxAmt() {
		return this.initTxAmt;
	}

	public void setInitTxAmt(BigDecimal initTxAmt) {
		this.initTxAmt = initTxAmt;
	}

	@Column(name = "HOLDING_QTY", scale = 4)
	@AnnoMethodTree(order=60, init=true)
	public BigDecimal getHoldingQty() {
		return this.holdingQty;
	}

	public void setHoldingQty(BigDecimal holdingQty) {
		this.holdingQty = holdingQty;
	}
	
	@Column(name = "POS_AMT", scale = 4)
	@AnnoMethodTree(order=61, init=true, aggregatable=true)	
//	@Transient
	public BigDecimal getPosAmt() {
		return posAmt;
	}

	public void setPosAmt(BigDecimal posAmt) {
		this.posAmt = posAmt;
	}


	@OneToMany(mappedBy="position")
	public List<PositionProperty> getPropertyList() {
		return propertyList;
	}

	public void setPropertyList(List<PositionProperty> propertyList) {
		this.propertyList = propertyList;
	}

	
//	@ElementCollection
//	@CollectionTable(name="ETF_HIS", joinColumns= @JoinColumn(name="ETF_ID"))
//	@MapKeyColumn(name="BSSD")
	

	@ElementCollection
	@MapKeyJoinColumn(name="PROP_ID")
	@JoinTable(name="POSITION_PROP"
				, joinColumns=@JoinColumn(name="POS_ID")
//				, inverseJoinColumns=@JoinColumn(name="PORT_WEIGHT")
	)
	@Column(name="PROP_VALUE")
	public Map<HierarchyProperty, String> getPropMap() {
		return propMap;
	}

	public void setPropMap(Map<HierarchyProperty, String> propMap) {
		this.propMap = propMap;
	}

	//**************************************	
	@Override
	@Transient
	public String getStringId() {
		return getPosId();
	}

	@Override
	@Transient
	public String getName() {
		return getPosName();
	}

	@Override
	@Transient
	public void add(IPortfolio port) {
		
	}

	@Override
	@Transient
	public void remove(IPortfolio port) {
		
	}

	@Override
	@Transient
	public List<IPortfolio> getChildren() {
		return new ArrayList<IPortfolio>();
	}

	@Override
	@Transient
	public IPortfolio getChildren(String portId) {
		return null;
	}

	@Override
	@Transient
	public double getPresValue() {
		return 0;
	}

	@Override
	@Transient
	public double getCalcuatedPv() {
		return 0;
	}

	@Override
	@Transient
	public double getDailyReturn() {
		return 0;
	}


}
