package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * PositionRisk generated by hbm2java
 */
@Entity
@Table(name = "POSITION_RISK")
public class PositionRisk implements java.io.Serializable {

	private PositionRiskId id;
	private Basedate basedate;
	private VarGenMcd varGenMcd;
	private Position position;
	private BigDecimal var;
	private BigDecimal expectedShortfall;
	private BigDecimal eqVar;
	private BigDecimal fxVar;
	private BigDecimal irVar;
	private BigDecimal coVar;
	private BigDecimal marginalVar;
	private BigDecimal contributionVar;
	
//	private Set<PositionRiskDetail> positionRiskDetails = new HashSet<PositionRiskDetail>(0);

	public PositionRisk() {
	}

	public PositionRisk(PositionRiskId id, Basedate basedate, VarGenMcd varGenMcd, Position position) {
		this.id = id;
		this.basedate = basedate;
		this.varGenMcd = varGenMcd;
		this.position = position;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "posId", column = @Column(name = "POS_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "varGenId", column = @Column(name = "VAR_GEN_ID", nullable = false, length = 10)) })
	@NotNull
	public PositionRiskId getId() {
		return this.id;
	}

	public void setId(PositionRiskId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BSSD", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Basedate getBasedate() {
		return this.basedate;
	}

	public void setBasedate(Basedate basedate) {
		this.basedate = basedate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VAR_GEN_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public VarGenMcd getVarGenMcd() {
		return this.varGenMcd;
	}

	public void setVarGenMcd(VarGenMcd varGenMcd) {
		this.varGenMcd = varGenMcd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POS_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@Column(name = "VAR", scale = 4)
	public BigDecimal getVar() {
		return this.var;
	}

	public void setVar(BigDecimal var) {
		this.var = var;
	}

	@Column(name = "EXPECTED_SHORTFALL", scale = 4)
	public BigDecimal getExpectedShortfall() {
		return this.expectedShortfall;
	}

	public void setExpectedShortfall(BigDecimal expectedShortfall) {
		this.expectedShortfall = expectedShortfall;
	}

	@Column(name = "EQ_VAR", scale = 4)
	public BigDecimal getEqVar() {
		return this.eqVar;
	}

	public void setEqVar(BigDecimal eqVar) {
		this.eqVar = eqVar;
	}

	@Column(name = "FX_VAR", scale = 4)
	public BigDecimal getFxVar() {
		return this.fxVar;
	}

	public void setFxVar(BigDecimal fxVar) {
		this.fxVar = fxVar;
	}

	@Column(name = "IR_VAR", scale = 4)
	public BigDecimal getIrVar() {
		return this.irVar;
	}

	public void setIrVar(BigDecimal irVar) {
		this.irVar = irVar;
	}

	@Column(name = "CO_VAR", scale = 4)
	public BigDecimal getCoVar() {
		return this.coVar;
	}

	public void setCoVar(BigDecimal coVar) {
		this.coVar = coVar;
	}

	@Column(name = "MARGINAL_VAR", scale = 4)
	public BigDecimal getMarginalVar() {
		return this.marginalVar;
	}

	public void setMarginalVar(BigDecimal marginalVar) {
		this.marginalVar = marginalVar;
	}

	@Column(name = "CONTRIBUTION_VAR", scale = 4)
	public BigDecimal getContributionVar() {
		return this.contributionVar;
	}

	public void setContributionVar(BigDecimal contributionVar) {
		this.contributionVar = contributionVar;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "positionRisk")
//	public Set<PositionRiskDetail> getPositionRiskDetails() {
//		return this.positionRiskDetails;
//	}
//
//	public void setPositionRiskDetails(Set<PositionRiskDetail> positionRiskDetails) {
//		this.positionRiskDetails = positionRiskDetails;
//	}

}
