package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PositionReturnId generated by hbm2java
 */
@Embeddable
public class PositionReturnId implements java.io.Serializable {

	private String bssd;
	private String posId;

	public PositionReturnId() {
	}

	public PositionReturnId(String bssd, String posId) {
		this.bssd = bssd;
		this.posId = posId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "POS_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PositionReturnId))
			return false;
		PositionReturnId castOther = (PositionReturnId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getPosId() == castOther.getPosId()) || (this.getPosId() != null
						&& castOther.getPosId() != null && this.getPosId().equals(castOther.getPosId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getPosId() == null ? 0 : this.getPosId().hashCode());
		return result;
	}

}
