package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingUnderlyingId generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class PricingUnderlyingId implements java.io.Serializable {

	private String pricingObject;
	private String prodId;
	private String underlyingId;

	public PricingUnderlyingId() {
	}

	public PricingUnderlyingId(String pricingObject, String prodId, String underlyingId) {
		this.pricingObject = pricingObject;
		this.prodId = prodId;
		this.underlyingId = underlyingId;
	}

	@Column(name = "PRICING_OBJECT", nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getPricingObject() {
		return this.pricingObject;
	}

	public void setPricingObject(String pricingObject) {
		this.pricingObject = pricingObject;
	}

	@Column(name = "PROD_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=20, init=true)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	@Column(name = "STOCK_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=30, init=true)
	public String getUnderlyingId() {
		return this.underlyingId;
	}

	public void setUnderlyingId(String underlyingId) {
		this.underlyingId = underlyingId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PricingUnderlyingId))
			return false;
		PricingUnderlyingId castOther = (PricingUnderlyingId) other;

		return ((this.getPricingObject() == castOther.getPricingObject()) || (this.getPricingObject() != null
				&& castOther.getPricingObject() != null && this.getPricingObject().equals(castOther.getPricingObject())))
				&& ((this.getProdId() == castOther.getProdId()) || (this.getProdId() != null
						&& castOther.getProdId() != null && this.getProdId().equals(castOther.getProdId())))
				&& ((this.getUnderlyingId() == castOther.getUnderlyingId()) || (this.getUnderlyingId() != null
						&& castOther.getUnderlyingId() != null && this.getUnderlyingId().equals(castOther.getUnderlyingId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPricingObject() == null ? 0 : this.getPricingObject().hashCode());
		result = 37 * result + (getProdId() == null ? 0 : this.getProdId().hashCode());
		result = 37 * result + (getUnderlyingId() == null ? 0 : this.getUnderlyingId().hashCode());
		return result;
	}

}
