package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingObject generated by hbm2java
 */
@Entity
@Table(name = "PRICING_OBJECT")
@AnnoNavigationFilter
public class PricingObject implements java.io.Serializable {

	private String pricingObjId;
	private String pricngObjName;
	private String parentPricingObjId;

	public PricingObject() {
	}

	public PricingObject(String pricingObjId, String parentPricingObjId) {
		this.pricingObjId = pricingObjId;
		this.parentPricingObjId = parentPricingObjId;
	}

	public PricingObject(String pricingObjId, String pricngObjName, String parentPricingObjId) {
		this.pricingObjId = pricingObjId;
		this.pricngObjName = pricngObjName;
		this.parentPricingObjId = parentPricingObjId;
	}

	@Id
	@Column(name = "PRICING_OBJ_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getPricingObjId() {
		return this.pricingObjId;
	}

	public void setPricingObjId(String pricingObjId) {
		this.pricingObjId = pricingObjId;
	}

	@Column(name = "PRICNG_OBJ_NAME", length = 50)
	@AnnoMethodTree(order=11, init=true)
	public String getPricngObjName() {
		return this.pricngObjName;
	}

	public void setPricngObjName(String pricngObjName) {
		this.pricngObjName = pricngObjName;
	}

	@Column(name = "PARENT_PRICING_OBJ_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=20, init=true)
	public String getParentPricingObjId() {
		return this.parentPricingObjId;
	}

	public void setParentPricingObjId(String parentPricingObjId) {
		this.parentPricingObjId = parentPricingObjId;
	}

}
