package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingDll generated by hbm2java
 */
@Entity
@Table(name = "PRICING_DLL")
@AnnoNavigationFilter
public class PricingDll implements java.io.Serializable {
	private String dllId;
	private String dllName;
	private String dllType;
	private String dllVendor;
	private MvType coveredMvType;
	private String description;

	public PricingDll() {
	}

	public PricingDll(String dllId) {
		this.dllId = dllId;
	}
//
//	public PricingDll(String dllId, String dllName, String dllType, String dllVendor, String coveredMvType,
//			String description) {
//		this.dllId = dllId;
//		this.dllName = dllName;
//		this.dllType = dllType;
//		this.dllVendor = dllVendor;
//		this.coveredMvType = coveredMvType;
//		this.description = description;
//	}

	@Id
	@Column(name = "DLL_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getDllId() {
		return this.dllId;
	}

	public void setDllId(String dllId) {
		this.dllId = dllId;
	}

	@Column(name = "DLL_NAME", length = 50)
	@AnnoMethodTree(order=11, init=true)
	public String getDllName() {
		return this.dllName;
	}

	public void setDllName(String dllName) {
		this.dllName = dllName;
	}

	@Column(name = "DLL_TYPE", length = 20)
	@AnnoMethodTree(order=20, init=true)
	public String getDllType() {
		return this.dllType;
	}

	public void setDllType(String dllType) {
		this.dllType = dllType;
	}

	@Column(name = "DLL_VENDOR", length = 20)
	@AnnoMethodTree(order=30, init=true)
	public String getDllVendor() {
		return this.dllVendor;
	}

	public void setDllVendor(String dllVendor) {
		this.dllVendor = dllVendor;
	}

//	@Column(name = "COVERED_MV_TYPE", nullable = false, length = 20)
//	@AnnoMethodTree(order=40, init=true)
//	public String getCoveredMvType() {
//		return this.coveredMvType;
//	}
//	public void setCoveredMvType(String coveredMvType) {
//		this.coveredMvType = coveredMvType;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COVERED_MV_TYPE", nullable = true)
	@AnnoMethodTree(order=40, init=true)
	public MvType getCoveredMvType() {
		return coveredMvType;
	}

	public void setCoveredMvType(MvType coveredMvType) {
		this.coveredMvType = coveredMvType;
	}	
	
	
	
	@Column(name = "DESCRIPTION")
	@AnnoMethodTree(order=50, init=true)
	public String getDescription() {
		return this.description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

}
