package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingMapping generated by hbm2java
 */
@Entity
@Table(name = "PRICING_MAPPING")
@AnnoNavigationFilter
public class PricingMapping implements java.io.Serializable {

	private PricingMappingId id;
//	private String dllId;
	private PricingDll pricingDll;
	private String discountSetting;
	private String volType;
	private String volSetting;
	private Long simulationNum;
	private Long latticeNum;

	public PricingMapping() {
	}

//	public PricingMapping(PricingMappingId id, String dllId) {
//		this.id = id;
//		this.dllId = dllId;
//	}
//	public PricingMapping(PricingMappingId id, String dllId, String discountSetting, String volType, String volSetting,
//			Long simulationNum, Long latticeNum) {
//		this.id = id;
//		this.dllId = dllId;
//		this.discountSetting = discountSetting;
//		this.volType = volType;
//		this.volSetting = volSetting;
//		this.simulationNum = simulationNum;
//		this.latticeNum = latticeNum;
//	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pricingObjId", column = @Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "mvType", column = @Column(name = "MV_TYPE", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public PricingMappingId getId() {
		return this.id;
	}

	public void setId(PricingMappingId id) {
		this.id = id;
	}

//	@Column(name = "DLL_ID", nullable = false, length = 20)
//	@AnnoMethodTree(order=20, init=true)
//	public String getDllId() {
//		return this.dllId;
//	}
//	public void setDllId(String dllId) {
//		this.dllId = dllId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DLL_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=20, init=true)
	public PricingDll getPricingDll() {
		return pricingDll;
	}
	public void setPricingDll(PricingDll pricingDll) {
		this.pricingDll = pricingDll;
	}

	@Column(name = "DISCOUNT_SETTING", length = 20)
	@AnnoMethodTree(order=30, init=true)
	public String getDiscountSetting() {
		return this.discountSetting;
	}


	public void setDiscountSetting(String discountSetting) {
		this.discountSetting = discountSetting;
	}

	@Column(name = "VOL_TYPE", length = 20)
	@AnnoMethodTree(order=40, init=true)
	public String getVolType() {
		return this.volType;
	}

	public void setVolType(String volType) {
		this.volType = volType;
	}

	@Column(name = "VOL_SETTING", length = 20)
	@AnnoMethodTree(order=45, init=true)
	public String getVolSetting() {
		return this.volSetting;
	}

	public void setVolSetting(String volSetting) {
		this.volSetting = volSetting;
	}

	@Column(name = "SIMULATION_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=50, init=true)
	public Long getSimulationNum() {
		return this.simulationNum;
	}

	public void setSimulationNum(Long simulationNum) {
		this.simulationNum = simulationNum;
	}

	@Column(name = "LATTICE_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=51, init=true)
	public Long getLatticeNum() {
		return this.latticeNum;
	}

	public void setLatticeNum(Long latticeNum) {
		this.latticeNum = latticeNum;
	}

}
