package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingUnderlyings generated by hbm2java
 */
@Entity
@Table(name = "PRICING_UNDERLYINGS")
@AnnoNavigationFilter
public class PricingUnderlyings implements java.io.Serializable, Cloneable {

	private PricingUnderlyingsId id;
//	private String refIrcId;
//	private String volCurveId;
	private IrCurve refIrc;
	private VolCurve volCurve;
	
	private Hifive hifive;
	private PricingMaster prMaster;
	

	public PricingUnderlyings() {
	}

//	public PricingUnderlyings(PricingUnderlyingsId id, String refIrcId, String volCurveId) {
//		this.id = id;
//		this.refIrcId = refIrcId;
//		this.volCurveId = volCurveId;
//	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pricingObjId", column = @Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "underlyingId", column = @Column(name = "UNDERLYING_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public PricingUnderlyingsId getId() {
		return this.id;
	}

	public void setId(PricingUnderlyingsId id) {
		this.id = id;
	}

//	@Column(name = "REF_IRC_ID", nullable = false, length = 20)
//	@AnnoMethodTree(order=20, init=true)
//	public String getRefIrcId() {
//		return this.refIrcId;
//	}
//
//	public void setRefIrcId(String refIrcId) {
//		this.refIrcId = refIrcId;
//	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_IRC_ID", nullable = true)
	@AnnoMethodTree(order=20, init=true)
	public IrCurve getRefIrc() {
		return refIrc;
	}
	public void setRefIrc(IrCurve refIrc) {
		this.refIrc = refIrc;
	}
	
//	@Column(name = "VOL_CURVE_ID", nullable = false, length = 20)
//	@AnnoMethodTree(order=30, init=true)
//	public String getVolCurveId() {
//		return this.volCurveId;
//	}
//	public void setVolCurveId(String volCurveId) {
//		this.volCurveId = volCurveId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOL_CURVE_ID", nullable = true)
	@AnnoMethodTree(order=30, init=true)
	public VolCurve getVolCurve() {
		return volCurve;
	}

	public void setVolCurve(VolCurve volCurve) {
		this.volCurve = volCurve;
	}

//	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name="PRICING_OBJ_ID", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name ="PROD_ID", nullable = false, insertable = false, updatable = false)
	})
	@AnnoMethodTree(order=15, init=true)
	public PricingMaster getPrMaster() {
		return prMaster;
	}

	public void setPrMaster(PricingMaster prMaster) {
		this.prMaster = prMaster;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=14, init=true)
	public Hifive getHifive() {
		return hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}

	@Transient
	@Override
	public Object clone(){
		try{
			return super.clone();
		}catch(Exception e){
			
		}
		return null;
	}	
	
}
