package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.eugenefe.enums.EPricingObject;
import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * PricingMappingId generated by hbm2java
 */
@Embeddable
@AnnoNavigationFilter
public class PricingMappingIdNew implements java.io.Serializable {

	private EPricingObject prObject;
	private MvType mvType;

	public PricingMappingIdNew() {
	}

	

	public PricingMappingIdNew(EPricingObject prObject, MvType mvType) {
		this.prObject = prObject;
		this.mvType = mvType;
	}



	@Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	@Enumerated(EnumType.STRING)
	public EPricingObject getPrObject() {
		return prObject;
	}
	public void setPrObject(EPricingObject prObject) {
		this.prObject = prObject;
	}

	public void setMvType(MvType mvType) {
		this.mvType = mvType;
	}


	@ManyToOne
	@JoinColumn(name = "MV_TYPE", nullable = false)
//	@Column(name = "MV_TYPE", nullable = false, length = 20)
	@AnnoMethodTree(order=20, init=true)
	public MvType getMvType() {
		return this.mvType;
	}



	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PricingMappingIdNew))
			return false;
		PricingMappingIdNew castOther = (PricingMappingIdNew) other;

		return ((this.getPrObject() == castOther.getPrObject()) || (this.getPrObject() != null
				&& castOther.getPrObject() != null && this.getPrObject().equals(castOther.getPrObject())))
				&& ((this.getMvType() == castOther.getMvType()) || (this.getMvType() != null
						&& castOther.getMvType() != null && this.getMvType().equals(castOther.getMvType())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPrObject() == null ? 0 : this.getPrObject().hashCode());
		result = 37 * result + (getMvType() == null ? 0 : this.getMvType().hashCode());
		return result;
	}

}
