package com.eugenefe.entity;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;
import com.sun.org.apache.bcel.internal.generic.ARRAYLENGTH;

/**
 * PricingMaster generated by hbm2java
 */
@Entity
@Table(name = "PRICING_MASTER")
@AnnoNavigationFilter
public class PricingMaster implements java.io.Serializable, Cloneable{

	private PricingMasterId id;
	
	private Hifive hifive;
//	private String mvType;
//	private String dllId;
//	private String discountIrcId;
	
	private MvType mvType;
	private PricingDll pricingDll;
	private IrCurve discountIrc;
	
	private Long simulationNum;
	private Long latticeNum;
	
	private List<PricingUnderlyings> prUnderlyingList = new ArrayList<PricingUnderlyings>();

	public PricingMaster() {
	}

//	public PricingMaster(PricingMasterId id, String mvType, String dllId, String discountIrcId) {
//		this.id = id;
//		this.mvType = mvType;
//		this.dllId = dllId;
//		this.discountIrcId = discountIrcId;
//	}
//
//	public PricingMaster(PricingMasterId id, String mvType, String dllId, String discountIrcId, Long simulationNum,
//			Long latticeNum) {
//		this.id = id;
//		this.mvType = mvType;
//		this.dllId = dllId;
//		this.discountIrcId = discountIrcId;
//		this.simulationNum = simulationNum;
//		this.latticeNum = latticeNum;
//	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pricingObjId", column = @Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public PricingMasterId getId() {
		return this.id;
	}
	public void setId(PricingMasterId id) {
		this.id = id;
	}

	
	
//	@Column(name = "MV_TYPE", nullable = false, length = 20)
//	@AnnoMethodTree(order=20, init=true)
//	public String getMvType() {
//		return this.mvType;
//	}
//
//	public void setMvType(String mvType) {
//		this.mvType = mvType;
//	}
//	@Transient
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=15, init=true)
	public Hifive getHifive() {
		return hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MV_TYPE", nullable = false)
	@AnnoMethodTree(order=20, init=true)
	public MvType getMvType() {
		return mvType;
	}
	public void setMvType(MvType mvType) {
		this.mvType = mvType;
	}
	
//	@Column(name = "DLL_ID", nullable = false, length = 20)
//	@AnnoMethodTree(order=30, init=true)
//	public String getDllId() {
//		return this.dllId;
//	}
//	public void setDllId(String dllId) {
//		this.dllId = dllId;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DLL_ID", nullable = false)
	@AnnoMethodTree(order=30, init=true)
	public PricingDll getPricingDll() {
		return pricingDll;
	}
	public void setPricingDll(PricingDll pricingDll) {
		this.pricingDll = pricingDll;
	}
	
	
//	@Column(name = "DISCOUNT_IRC_ID", nullable = false, length = 20)
//	@AnnoMethodTree(order=40, init=true)
//	public String getDiscountIrcId() {
//		return this.discountIrcId;
//	}
//	public void setDiscountIrcId(String discountIrcId) {
//		this.discountIrcId = discountIrcId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISCOUNT_IRC_ID", nullable = true)
	@AnnoMethodTree(order=40, init=true)
	public IrCurve getDiscountIrc() {
		return discountIrc;
	}
	public void setDiscountIrc(IrCurve discountIrc) {
		this.discountIrc = discountIrc;
	}
	
	@Column(name = "SIMULATION_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=50, init=true)
	public Long getSimulationNum() {
		return this.simulationNum;
	}

	public void setSimulationNum(Long simulationNum) {
		this.simulationNum = simulationNum;
	}

	@Column(name = "LATTICE_NUM", precision = 10, scale = 0)
	@AnnoMethodTree(order=51, init=true)
	public Long getLatticeNum() {
		return this.latticeNum;
	}
	public void setLatticeNum(Long latticeNum) {
		this.latticeNum = latticeNum;
	}

//	@Transient
	@OneToMany(mappedBy="prMaster")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	@AnnoMethodTree(order=60, init=false, type=EColumnType.List)
	public List<PricingUnderlyings> getPrUnderlyingList() {
		return prUnderlyingList;
	}

	public void setPrUnderlyingList(List<PricingUnderlyings> prUnderlyingList) {
		this.prUnderlyingList = prUnderlyingList;
	}

	
	@Transient
	@Override
	public Object clone(){
		try{
			return super.clone();
		}catch(Exception e){
			
		}
		return null;
	}	
}
