package com.eugenefe.entity;

// Generated 2014. 1. 22 ¿ÀÈÄ 2:10:36 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * ProductReturn generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_RETURN")
@AnnoNavigationFilter
public class ProductReturn implements java.io.Serializable {

	private ProductReturnId id;
	private Hifive hifive;
	private PricingMaster priceSetting;
	private BigDecimal bookAmt;
	private BigDecimal presValue;
	private BigDecimal dailyReturn;
	private BigDecimal monthlyReturn;
	private BigDecimal quartlyReturn;
	private BigDecimal annualReturn;
	private BigDecimal fiscalReturn;
	private BigDecimal deltaReturn;
	private BigDecimal gammaReturn;
	private BigDecimal vegaReturn;
	private BigDecimal thetaReturn;
	private BigDecimal rhoReturn;
	private BigDecimal theta;
	private BigDecimal rho;
	private BigDecimal crossGamma;

	public ProductReturn() {
	}

	public ProductReturn(ProductReturnId id) {
		this.id = id;
	}

	public ProductReturn(ProductReturnId id, BigDecimal bookAmt, BigDecimal presValue, BigDecimal dailyReturn,
			BigDecimal monthlyReturn, BigDecimal quartlyReturn, BigDecimal annualReturn, BigDecimal fiscalReturn,
			BigDecimal deltaReturn, BigDecimal gammaReturn, BigDecimal vegaReturn, BigDecimal thetaReturn,
			BigDecimal rhoReturn, BigDecimal theta, BigDecimal rho, BigDecimal crossGamma) {
		this.id = id;
		this.bookAmt = bookAmt;
		this.presValue = presValue;
		this.dailyReturn = dailyReturn;
		this.monthlyReturn = monthlyReturn;
		this.quartlyReturn = quartlyReturn;
		this.annualReturn = annualReturn;
		this.fiscalReturn = fiscalReturn;
		this.deltaReturn = deltaReturn;
		this.gammaReturn = gammaReturn;
		this.vegaReturn = vegaReturn;
		this.thetaReturn = thetaReturn;
		this.rhoReturn = rhoReturn;
		this.theta = theta;
		this.rho = rho;
		this.crossGamma = crossGamma;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "pricingObjId", column = @Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public ProductReturnId getId() {
		return this.id;
	}

	public void setId(ProductReturnId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=11, init=false)
	public Hifive getHifive() {
		return hifive;
	}

	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "PRICING_OBJ_ID", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	})
	@AnnoMethodTree(order=12, init=true)
	public PricingMaster getPriceSetting() {
		return priceSetting;
	}
	
	public void setPriceSetting(PricingMaster priceSetting) {
		this.priceSetting = priceSetting;
	}

	@Column(name = "BOOK_AMT", scale = 4)
	@AnnoMethodTree(order=20, init=true)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;
	}

	@Column(name = "PRES_VALUE", scale = 4)
	@AnnoMethodTree(order=30, init=true)
	public BigDecimal getPresValue() {
		return this.presValue;
	}

	public void setPresValue(BigDecimal presValue) {
		this.presValue = presValue;
	}

	@Column(name = "DAILY_RETURN", scale = 4)
	@AnnoMethodTree(order=40, init=true)
	public BigDecimal getDailyReturn() {
		return this.dailyReturn;
	}

	public void setDailyReturn(BigDecimal dailyReturn) {
		this.dailyReturn = dailyReturn;
	}

	@Column(name = "MONTHLY_RETURN", scale = 4)
	@AnnoMethodTree(order=41, init=true)
	public BigDecimal getMonthlyReturn() {
		return this.monthlyReturn;
	}

	public void setMonthlyReturn(BigDecimal monthlyReturn) {
		this.monthlyReturn = monthlyReturn;
	}

	@Column(name = "QUARTLY_RETURN", scale = 4)
	@AnnoMethodTree(order=42, init=true)
	public BigDecimal getQuartlyReturn() {
		return this.quartlyReturn;
	}

	public void setQuartlyReturn(BigDecimal quartlyReturn) {
		this.quartlyReturn = quartlyReturn;
	}

	@Column(name = "ANNUAL_RETURN", scale = 4)
	@AnnoMethodTree(order=43, init=true)
	public BigDecimal getAnnualReturn() {
		return this.annualReturn;
	}

	public void setAnnualReturn(BigDecimal annualReturn) {
		this.annualReturn = annualReturn;
	}

	@Column(name = "FISCAL_RETURN", scale = 4)
	@AnnoMethodTree(order=44, init=true)
	public BigDecimal getFiscalReturn() {
		return this.fiscalReturn;
	}

	public void setFiscalReturn(BigDecimal fiscalReturn) {
		this.fiscalReturn = fiscalReturn;
	}

	@Column(name = "DELTA_RETURN", scale = 4)
	@AnnoMethodTree(order=51, init=true)
	public BigDecimal getDeltaReturn() {
		return this.deltaReturn;
	}

	public void setDeltaReturn(BigDecimal deltaReturn) {
		this.deltaReturn = deltaReturn;
	}

	@Column(name = "GAMMA_RETURN", scale = 4)
	@AnnoMethodTree(order=52, init=true)
	public BigDecimal getGammaReturn() {
		return this.gammaReturn;
	}

	public void setGammaReturn(BigDecimal gammaReturn) {
		this.gammaReturn = gammaReturn;
	}

	@Column(name = "VEGA_RETURN", scale = 4)
	@AnnoMethodTree(order=53, init=true)
	public BigDecimal getVegaReturn() {
		return this.vegaReturn;
	}

	public void setVegaReturn(BigDecimal vegaReturn) {
		this.vegaReturn = vegaReturn;
	}

	@Column(name = "THETA_RETURN", scale = 4)
	@AnnoMethodTree(order=54, init=true)
	public BigDecimal getThetaReturn() {
		return this.thetaReturn;
	}

	public void setThetaReturn(BigDecimal thetaReturn) {
		this.thetaReturn = thetaReturn;
	}

	@Column(name = "RHO_RETURN", scale = 4)
	@AnnoMethodTree(order=55, init=true)
	public BigDecimal getRhoReturn() {
		return this.rhoReturn;
	}

	public void setRhoReturn(BigDecimal rhoReturn) {
		this.rhoReturn = rhoReturn;
	}

	@Transient
//	@Column(name = "THETA", scale = 4)
//	@AnnoMethodTree(order=60, init=true)
	public BigDecimal getTheta() {
		return this.theta;
	}

	public void setTheta(BigDecimal theta) {
		this.theta = theta;
	}
	@Transient
//	@Column(name = "RHO", scale = 4)
//	@AnnoMethodTree(order=61, init=true)
	public BigDecimal getRho() {
		return this.rho;
	}

	public void setRho(BigDecimal rho) {
		this.rho = rho;
	}

	@Transient
//	@Column(name = "CROSS_GAMMA", scale = 4)
//	@AnnoMethodTree(order=62, init=true)
	public BigDecimal getCrossGamma() {
		return this.crossGamma;
	}

	public void setCrossGamma(BigDecimal crossGamma) {
		this.crossGamma = crossGamma;
	}

}
