package com.eugenefe.entity;

// Generated 2014. 1. 22 ¿ÀÈÄ 2:10:36 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * ProductGreeks generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_GREEKS")
@AnnoNavigationFilter
public class ProductGreeks implements java.io.Serializable {

	private ProductGreeksId id;
	private Hifive hifive;
	private PricingUnderlyings prUnderSetting;
	
	private BigDecimal delta;
	private BigDecimal gamma;
	private BigDecimal vega;

	public ProductGreeks() {
	}

	public ProductGreeks(ProductGreeksId id) {
		this.id = id;
	}

	public ProductGreeks(ProductGreeksId id, BigDecimal delta, BigDecimal gamma, BigDecimal vega) {
		this.id = id;
		this.delta = delta;
		this.gamma = gamma;
		this.vega = vega;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "pricingObjId", column = @Column(name = "PRICING_OBJ_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "prodId", column = @Column(name = "PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "underlyingId", column = @Column(name = "UNDERLYING_ID", nullable = false, length = 20)) })
	@AnnoMethodTree(order=10, init=true)
	public ProductGreeksId getId() {
		return this.id;
	}

	public void setId(ProductGreeksId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false)
	@AnnoMethodTree(order=11, init=false)	
	public Hifive getHifive() {
		return hifive;
	}


	public void setHifive(Hifive hifive) {
		this.hifive = hifive;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "PRICING_OBJ_ID", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name = "PROD_ID", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name = "UNDERLYING_ID", nullable = false, insertable = false, updatable = false)
	})
	@AnnoMethodTree(order=12, init=false)
	public PricingUnderlyings getPrUnderSetting() {
		return prUnderSetting;
	}

	public void setPrUnderSetting(PricingUnderlyings prUnderSetting) {
		this.prUnderSetting = prUnderSetting;
	}

	@Column(name = "DELTA", precision = 10, scale = 4)
	@AnnoMethodTree(order=20, init=true)
	public BigDecimal getDelta() {
		return this.delta;
	}

	public void setDelta(BigDecimal delta) {
		this.delta = delta;
	}

	@Column(name = "GAMMA", precision = 10, scale = 4)
	@AnnoMethodTree(order=30, init=true)
	public BigDecimal getGamma() {
		return this.gamma;
	}

	public void setGamma(BigDecimal gamma) {
		this.gamma = gamma;
	}

	@Column(name = "VEGA", precision = 10, scale = 4)
	@AnnoMethodTree(order=40, init=true)
	public BigDecimal getVega() {
		return this.vega;
	}

	public void setVega(BigDecimal vega) {
		this.vega = vega;
	}

}
