package com.eugenefe.entity;

// Generated 2014. 1. 28 ¿ÀÀü 9:38:27 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapKey;
import javax.persistence.MapKeyClass;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.eugenefe.entity.component.ShockData;
import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

/**
 * Scenario generated by hbm2java
 */
@Entity
@Table(name = "SCENARIO")
@AnnoNavigationFilter
public class Scenario implements java.io.Serializable {

	private String scenarioId;
	private String scenarioName;
	private String scenarioType;
	private String scenarioSet;
	
	private List<ScenarioDetail> sceDetailList = new ArrayList<ScenarioDetail>();

	public Scenario() {
	}

	public Scenario(String scenarioId) {
		this.scenarioId = scenarioId;
	}

	public Scenario(String scenarioId, String scenarioName, String scenarioType, String scenarioSet) {
		this.scenarioId = scenarioId;
		this.scenarioName = scenarioName;
		this.scenarioType = scenarioType;
		this.scenarioSet = scenarioSet;
	}

	@Id
	@Column(name = "SCENARIO_ID", unique = true, nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getScenarioId() {
		return this.scenarioId;
	}

	public void setScenarioId(String scenarioId) {
		this.scenarioId = scenarioId;
	}

	@Column(name = "SCENARIO_NAME", length = 50)
	@AnnoMethodTree(order=11, init=true)
	public String getScenarioName() {
		return this.scenarioName;
	}

	public void setScenarioName(String scenarioName) {
		this.scenarioName = scenarioName;
	}

	@Column(name = "SCENARIO_TYPE", length = 10)
	@AnnoMethodTree(order=20, init=true)
	public String getScenarioType() {
		return this.scenarioType;
	}

	public void setScenarioType(String scenarioType) {
		this.scenarioType = scenarioType;
	}

	@Column(name = "SCENARIO_SET", length = 20)
	@AnnoMethodTree(order=30, init=true)
	public String getScenarioSet() {
		return this.scenarioSet;
	}

	public void setScenarioSet(String scenarioSet) {
		this.scenarioSet = scenarioSet;
	}

	@OneToMany(mappedBy="scenario")
//	@OneToMany
//	@JoinColumn(name="SCENARIO_ID")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	@AnnoMethodTree(order=40, init=true, type=EColumnType.List)
	public List<ScenarioDetail> getSceDetailList() {
		return sceDetailList;
	}

	public void setSceDetailList(List<ScenarioDetail> sceDetailList) {
		this.sceDetailList = sceDetailList;
	}
	
	private Map<MarketVariableJoin, ShockData> sceMap = new HashMap<MarketVariableJoin, ShockData>();

	@Transient
//	@ElementCollection
//	@CollectionTable(name="SCENARIO_DETAIL", joinColumns= @JoinColumn(name="SCENARIO_ID"))
//	@MapKeyJoinColumn(name="MV_ID")
	public Map<MarketVariableJoin, ShockData> getSceMap() {
		return sceMap;
	}

	public void setSceMap(Map<MarketVariableJoin, ShockData> sceMap) {
		this.sceMap = sceMap;
	}
	
	
}
