package com.eugenefe.entity;

// Generated 2014. 1. 28 ¿ÀÀü 9:38:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.eugenefe.util.AnnoMethodTree;

/**
 * ScenarioDetailId generated by hbm2java
 */
@Embeddable
public class ScenarioDetailId implements java.io.Serializable {

	private String scenarioId;
	private String mvId;

	public ScenarioDetailId() {
	}

	public ScenarioDetailId(String scenarioId, String mvId) {
		this.scenarioId = scenarioId;
		this.mvId = mvId;
	}

	@Column(name = "SCENARIO_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=10, init=true)
	public String getScenarioId() {
		return this.scenarioId;
	}

	public void setScenarioId(String scenarioId) {
		this.scenarioId = scenarioId;
	}

	@Column(name = "MV_ID", nullable = false, length = 20)
	@AnnoMethodTree(order=20, init=true)
	public String getMvId() {
		return this.mvId;
	}

	public void setMvId(String mvId) {
		this.mvId = mvId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScenarioDetailId))
			return false;
		ScenarioDetailId castOther = (ScenarioDetailId) other;

		return ((this.getScenarioId() == castOther.getScenarioId()) || (this.getScenarioId() != null
				&& castOther.getScenarioId() != null && this.getScenarioId().equals(castOther.getScenarioId())))
				&& ((this.getMvId() == castOther.getMvId()) || (this.getMvId() != null && castOther.getMvId() != null && this
						.getMvId().equals(castOther.getMvId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getScenarioId() == null ? 0 : this.getScenarioId().hashCode());
		result = 37 * result + (getMvId() == null ? 0 : this.getMvId().hashCode());
		return result;
	}

}
