package com.eugenefe.entity;

// Generated 2014. 1. 28 ¿ÀÀü 9:38:27 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ScenarioHis generated by hbm2java
 */
@Entity
@Table(name = "SCENARIO_HIS")
public class ScenarioHis implements java.io.Serializable {

	private ScenarioHisId id;
	private BigDecimal baseValue;
	private BigDecimal scenarioValue;

	public ScenarioHis() {
	}

	public ScenarioHis(ScenarioHisId id) {
		this.id = id;
	}

	public ScenarioHis(ScenarioHisId id, BigDecimal baseValue, BigDecimal scenarioValue) {
		this.id = id;
		this.baseValue = baseValue;
		this.scenarioValue = scenarioValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "scenarioId", column = @Column(name = "SCENARIO_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "mvId", column = @Column(name = "MV_ID", nullable = false, length = 20)) })
	public ScenarioHisId getId() {
		return this.id;
	}

	public void setId(ScenarioHisId id) {
		this.id = id;
	}

	@Column(name = "BASE_VALUE", scale = 4)
	public BigDecimal getBaseValue() {
		return this.baseValue;
	}

	public void setBaseValue(BigDecimal baseValue) {
		this.baseValue = baseValue;
	}

	@Column(name = "SCENARIO_VALUE", scale = 4)
	public BigDecimal getScenarioValue() {
		return this.scenarioValue;
	}

	public void setScenarioValue(BigDecimal scenarioValue) {
		this.scenarioValue = scenarioValue;
	}

}
