package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StockIndex generated by hbm2java
 */
@Entity
@Table(name = "STOCK_INDEX")
@PrimaryKeyJoinColumn(name="ST_INDEX_ID")
public class StockIndex extends MarketVariableJoin implements java.io.Serializable {

//	private String stIndexId;
//	private MarketVariable marketVariable;
	private String stIndexName;
	private String indexType;
	/*private Set<StockIndexHis> stockIndexHises = new HashSet<StockIndexHis>(0);
	private Set<Etf> etfs = new HashSet<Etf>(0);
	private Set<StockIndexDetail> stockIndexDetails = new HashSet<StockIndexDetail>(0);*/

	public StockIndex() {
	}

//	public StockIndex(MarketVariable marketVariable) {
//		this.marketVariable = marketVariable;
//	}
//	public StockIndex(MarketVariable marketVariable, String stIndexName, String indexType,
//			Set<StockIndexHis> stockIndexHises, Set<Etf> etfs, Set<StockIndexDetail> stockIndexDetails) {
//		this.marketVariable = marketVariable;
//		this.stIndexName = stIndexName;
//		this.indexType = indexType;
//		this.stockIndexHises = stockIndexHises;
//		this.etfs = etfs;
//		this.stockIndexDetails = stockIndexDetails;
//	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "marketVariable"))
//	@Id
//	@GeneratedValue(generator = "generator")
//	@Column(name = "ST_INDEX_ID", unique = true, nullable = false, length = 20)
//	@Size(max = 20)
//	public String getStIndexId() {
//		return this.stIndexId;
//	}
//
//	public void setStIndexId(String stIndexId) {
//		this.stIndexId = stIndexId;
//	}
//
//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	@NotNull
//	@Size(max = 20)
//	public MarketVariable getMarketVariable() {
//		return this.marketVariable;
//	}
//
//	public void setMarketVariable(MarketVariable marketVariable) {
//		this.marketVariable = marketVariable;
//	}

	@Column(name = "ST_INDEX_NAME", length = 50)
	@Size(max = 50)
	public String getStIndexName() {
		return this.stIndexName;
	}

	public void setStIndexName(String stIndexName) {
		this.stIndexName = stIndexName;
	}

	@Column(name = "INDEX_TYPE", length = 10)
	@Size(max = 10)
	public String getIndexType() {
		return this.indexType;
	}

	public void setIndexType(String indexType) {
		this.indexType = indexType;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockIndex")
//	public Set<StockIndexHis> getStockIndexHises() {
//		return this.stockIndexHises;
//	}
//
//	public void setStockIndexHises(Set<StockIndexHis> stockIndexHises) {
//		this.stockIndexHises = stockIndexHises;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockIndex")
//	public Set<Etf> getEtfs() {
//		return this.etfs;
//	}
//
//	public void setEtfs(Set<Etf> etfs) {
//		this.etfs = etfs;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockIndex")
//	public Set<StockIndexDetail> getStockIndexDetails() {
//		return this.stockIndexDetails;
//	}
//
//	public void setStockIndexDetails(Set<StockIndexDetail> stockIndexDetails) {
//		this.stockIndexDetails = stockIndexDetails;
//	}

}
