package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * StockIndexDetailId generated by hbm2java
 */
@Embeddable
public class StockIndexDetailId implements java.io.Serializable {

	private String stIndexId;
	private String stockId;

	public StockIndexDetailId() {
	}

	public StockIndexDetailId(String stIndexId, String stockId) {
		this.stIndexId = stIndexId;
		this.stockId = stockId;
	}

	@Column(name = "ST_INDEX_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getStIndexId() {
		return this.stIndexId;
	}

	public void setStIndexId(String stIndexId) {
		this.stIndexId = stIndexId;
	}

	@Column(name = "STOCK_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockIndexDetailId))
			return false;
		StockIndexDetailId castOther = (StockIndexDetailId) other;

		return ((this.getStIndexId() == castOther.getStIndexId()) || (this.getStIndexId() != null
				&& castOther.getStIndexId() != null && this.getStIndexId().equals(castOther.getStIndexId())))
				&& ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
						&& castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStIndexId() == null ? 0 : this.getStIndexId().hashCode());
		result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
		return result;
	}

}
