package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * StockIndexHisId generated by hbm2java
 */
@Embeddable
public class StockIndexHisId implements java.io.Serializable {

	private String bssd;
	private String stIndexId;

	public StockIndexHisId() {
	}

	public StockIndexHisId(String bssd, String stIndexId) {
		this.bssd = bssd;
		this.stIndexId = stIndexId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "ST_INDEX_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getStIndexId() {
		return this.stIndexId;
	}

	public void setStIndexId(String stIndexId) {
		this.stIndexId = stIndexId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockIndexHisId))
			return false;
		StockIndexHisId castOther = (StockIndexHisId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getStIndexId() == castOther.getStIndexId()) || (this.getStIndexId() != null
						&& castOther.getStIndexId() != null && this.getStIndexId().equals(castOther.getStIndexId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getStIndexId() == null ? 0 : this.getStIndexId().hashCode());
		return result;
	}

}
