package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * StockIndexDetail generated by hbm2java
 */
@Entity
@Table(name = "STOCK_INDEX_DETAIL")
public class StockIndexDetail implements java.io.Serializable {

	private StockIndexDetailId id;
	private StockIndex stockIndex;
	private Stock stock;
	private BigDecimal initWeight;
	private BigDecimal initAmt;
	private Character isActive;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;

	public StockIndexDetail() {
	}

	public StockIndexDetail(StockIndexDetailId id, StockIndex stockIndex, Stock stock) {
		this.id = id;
		this.stockIndex = stockIndex;
		this.stock = stock;
	}

	public StockIndexDetail(StockIndexDetailId id, StockIndex stockIndex, Stock stock, BigDecimal initWeight,
			BigDecimal initAmt, Character isActive, String sourceTable, String userName, String lastUpdated,
			BigDecimal versionNo) {
		this.id = id;
		this.stockIndex = stockIndex;
		this.stock = stock;
		this.initWeight = initWeight;
		this.initAmt = initAmt;
		this.isActive = isActive;
		this.sourceTable = sourceTable;
		this.userName = userName;
		this.lastUpdated = lastUpdated;
		this.versionNo = versionNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stIndexId", column = @Column(name = "ST_INDEX_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "stockId", column = @Column(name = "STOCK_ID", nullable = false, length = 20)) })
	@NotNull
	public StockIndexDetailId getId() {
		return this.id;
	}

	public void setId(StockIndexDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ST_INDEX_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public StockIndex getStockIndex() {
		return this.stockIndex;
	}

	public void setStockIndex(StockIndex stockIndex) {
		this.stockIndex = stockIndex;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Column(name = "INIT_WEIGHT", precision = 10, scale = 4)
	public BigDecimal getInitWeight() {
		return this.initWeight;
	}

	public void setInitWeight(BigDecimal initWeight) {
		this.initWeight = initWeight;
	}

	@Column(name = "INIT_AMT", scale = 0)
	public BigDecimal getInitAmt() {
		return this.initAmt;
	}

	public void setInitAmt(BigDecimal initAmt) {
		this.initAmt = initAmt;
	}

	@Column(name = "IS_ACTIVE", length = 1)
	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	@Size(max = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	@Size(max = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	@Size(max = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

}
