package com.eugenefe.entity;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SyntheticDetail generated by hbm2java
 */
@Entity
@Table(name = "SYNTHETIC_DETAIL", schema="TAKION99")
public class SyntheticDetail implements java.io.Serializable {

	private SyntheticDetailId id;
	private Synthetics synProd;
	private MarketVariable subProd;
	private String subProdName;
	private BigDecimal weight;
	private BigDecimal firstUnitPrice;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;

	public SyntheticDetail() {
	}

	public SyntheticDetail(SyntheticDetailId id) {
		this.id = id;
	}

	public SyntheticDetail(String  synId, String subId) {
		this.id = new SyntheticDetailId(synId, subId);
	}
	public SyntheticDetail(SyntheticDetailId id, String subProdName, BigDecimal weight, String sourceTable,
			String userName, String lastUpdated, BigDecimal versionNo) {
		this.id = id;
		this.subProdName = subProdName;
		this.weight = weight;
		this.sourceTable = sourceTable;
		this.userName = userName;
		this.lastUpdated = lastUpdated;
		this.versionNo = versionNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "synProdId", column = @Column(name = "SYN_PROD_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "subProdId", column = @Column(name = "SUB_PROD_ID", nullable = false, length = 20)) })
	public SyntheticDetailId getId() {
		return this.id;
	}

	public void setId(SyntheticDetailId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name="SYN_PROD_ID" , insertable=false, updatable=false)
	public Synthetics getSynProd() {
		return synProd;
	}

	public void setSynProd(Synthetics synProd) {
		this.synProd = synProd;
	}

	@Transient
//	@ManyToOne
//	@JoinColumn(name="SUB_PROD_ID" , insertable=false, updatable=false)
	public MarketVariable getSubProd() {
		return subProd;
	}

	public void setSubProd(MarketVariable subProd) {
		this.subProd = subProd;
	}

	@Column(name = "SUB_PROD_NAME", length = 50)
	public String getSubProdName() {
		return this.subProdName;
	}

	public void setSubProdName(String subProdName) {
		this.subProdName = subProdName;
	}

	@Column(name = "WEIGHT", scale = 4)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}
	@Column(name ="FIRST_UNIT_PRICE", precision=8)
	public BigDecimal getFirstUnitPrice() {
		return firstUnitPrice;
	}

	public void setFirstUnitPrice(BigDecimal firstUnitPrice) {
		this.firstUnitPrice = firstUnitPrice;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

}
