package com.eugenefe.entity;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Synthetics generated by hbm2java
 */
@Entity
@Table(name = "SYNTHETICS")
public class Synthetics implements java.io.Serializable {

	private String synProdId;
	private String syntheticType;
	private String synProdName;
	private String sourceTable;
	private String userName;
	private String lastUpdated;
	private BigDecimal versionNo;
	private List<SyntheticDetail> subProdList = new ArrayList<SyntheticDetail>();

	public Synthetics() {
	}

	public Synthetics(String synProdId) {
		this.synProdId = synProdId;
	}

	public Synthetics(String synProdId, String synProdName,String syntheticType ) {
		this.synProdId = synProdId;
		this.synProdName = synProdName;
		this.syntheticType = syntheticType;
	}

	public Synthetics(String synProdId, String syntheticType, String synProdName, String sourceTable, String userName,
			String lastUpdated, BigDecimal versionNo) {
		this.synProdId = synProdId;
		this.syntheticType = syntheticType;
		this.synProdName = synProdName;
		this.sourceTable = sourceTable;
		this.userName = userName;
		this.lastUpdated = lastUpdated;
		this.versionNo = versionNo;
	}

	@Id
	@Column(name = "SYN_PROD_ID", unique = true, nullable = false, length = 20)
	public String getSynProdId() {
		return this.synProdId;
	}

	public void setSynProdId(String synProdId) {
		this.synProdId = synProdId;
	}

	@Column(name = "SYNTHETIC_TYPE", length = 20)
	public String getSyntheticType() {
		return this.syntheticType;
	}

	public void setSyntheticType(String syntheticType) {
		this.syntheticType = syntheticType;
	}

	@Column(name = "SYN_PROD_NAME", length = 50)
	public String getSynProdName() {
		return this.synProdName;
	}

	public void setSynProdName(String synProdName) {
		this.synProdName = synProdName;
	}

	@Column(name = "SOURCE_TABLE", length = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LAST_UPDATED", length = 8)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "VERSION_NO", precision = 22, scale = 0)
	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	@OneToMany
	@JoinColumn(name ="SYN_PROD_ID", insertable=false, updatable=false)
//	@JoinColumn(name ="SYN_PROD_ID")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	@Fetch(FetchMode.SUBSELECT)
	public List<SyntheticDetail> getSubProdList() {
		return subProdList;
	}

	public void setSubProdList(List<SyntheticDetail> subProdList) {
		this.subProdList = subProdList;
	}
}
