package com.eugenefe.entity;

// Generated 2014. 4. 7 ¿ÀÈÄ 8:01:40 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SyntheticDetailId generated by hbm2java
 */
@Embeddable
public class SyntheticDetailId implements java.io.Serializable {

	private String synProdId;
	private String subProdId;

	public SyntheticDetailId() {
	}

	public SyntheticDetailId(String synProdId, String subProdId) {
		this.synProdId = synProdId;
		this.subProdId = subProdId;
	}

	@Column(name = "SYN_PROD_ID", nullable = false, length = 20)
	public String getSynProdId() {
		return this.synProdId;
	}

	public void setSynProdId(String synProdId) {
		this.synProdId = synProdId;
	}

	@Column(name = "SUB_PROD_ID", nullable = false, length = 20)
	public String getSubProdId() {
		return this.subProdId;
	}

	public void setSubProdId(String subProdId) {
		this.subProdId = subProdId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SyntheticDetailId))
			return false;
		SyntheticDetailId castOther = (SyntheticDetailId) other;

		return ((this.getSynProdId() == castOther.getSynProdId()) || (this.getSynProdId() != null
				&& castOther.getSynProdId() != null && this.getSynProdId().equals(castOther.getSynProdId())))
				&& ((this.getSubProdId() == castOther.getSubProdId()) || (this.getSubProdId() != null
						&& castOther.getSubProdId() != null && this.getSubProdId().equals(castOther.getSubProdId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSynProdId() == null ? 0 : this.getSynProdId().hashCode());
		result = 37 * result + (getSubProdId() == null ? 0 : this.getSubProdId().hashCode());
		return result;
	}

}
