package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * VarGenMcd generated by hbm2java
 */
@Entity
@Table(name = "VAR_GEN_MCD")
public class VarGenMcd implements java.io.Serializable {

	private String varGenId;
	private String varType;
	private BigDecimal timeHorizon;

	public VarGenMcd() {
	}

	public VarGenMcd(String varGenId) {
		this.varGenId = varGenId;
	}


	@Id
	@Column(name = "VAR_GEN_ID", unique = true, nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getVarGenId() {
		return this.varGenId;
	}

	public void setVarGenId(String varGenId) {
		this.varGenId = varGenId;
	}

	@Column(name = "VAR_TYPE", length = 10)
	@Size(max = 10)
	public String getVarType() {
		return this.varType;
	}

	public void setVarType(String varType) {
		this.varType = varType;
	}

	@Column(name = "TIME_HORIZON", precision = 10, scale = 0)
	public BigDecimal getTimeHorizon() {
		return this.timeHorizon;
	}

	public void setTimeHorizon(BigDecimal timeHorizon) {
		this.timeHorizon = timeHorizon;
	}


}
