package com.eugenefe.entity;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * VcvMatrixHis generated by hbm2java
 */
@Entity
@Table(name = "VCV_MATRIX_HIS")
public class VcvMatrixHis implements java.io.Serializable {

	private VcvMatrixHisId id;
	private Basedate basedate;
	private MarketVariable riskFactor;
	private MarketVariable refRiskFactor;
	private VcvMatrix vcvMatrix;
	private BigDecimal covariance;
	private BigDecimal correl;

	public VcvMatrixHis() {
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "vcvId", column = @Column(name = "VCV_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "rfId", column = @Column(name = "RF_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "refRfId", column = @Column(name = "REF_RF_ID", nullable = false, length = 20)) })
	@NotNull
	public VcvMatrixHisId getId() {
		return this.id;
	}

	public void setId(VcvMatrixHisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BSSD", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Basedate getBasedate() {
		return this.basedate;
	}

	public void setBasedate(Basedate basedate) {
		this.basedate = basedate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RF_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public MarketVariable getRiskFactor() {
		return this.riskFactor;
	}

	public void setRiskFactor(MarketVariable riskFactor) {
		this.riskFactor = riskFactor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_RF_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public MarketVariable getRefRiskFactor() {
		return this.refRiskFactor;
	}

	public void setRefRiskFactor(MarketVariable refRiskFactor) {
		this.refRiskFactor = refRiskFactor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VCV_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public VcvMatrix getVcvMatrix() {
		return this.vcvMatrix;
	}

	public void setVcvMatrix(VcvMatrix vcvMatrix) {
		this.vcvMatrix = vcvMatrix;
	}

	@Column(name = "COVARIANCE", scale = 4)
	public BigDecimal getCovariance() {
		return this.covariance;
	}

	public void setCovariance(BigDecimal covariance) {
		this.covariance = covariance;
	}

	@Column(name = "CORREL", precision = 10, scale = 4)
	public BigDecimal getCorrel() {
		return this.correl;
	}

	public void setCorrel(BigDecimal correl) {
		this.correl = correl;
	}

}
