package com.eugenefe.entity;

// Generated Nov 25, 2013 6:47:59 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VolCurve generated by hbm2java
 */
@Entity
@Table(name = "VOL_CURVE")
public class VolCurve implements java.io.Serializable {

	private String volCurveId;
	private String volCurveName;
	private String underlyingId;
	private Set<PricingUnderlyings> pricingUnderlyings = new HashSet<PricingUnderlyings>(0);
//	private Set<Pricing> pricings = new HashSet<Pricing>(0);

	public VolCurve() {
	}

	public VolCurve(String volCurveId) {
		this.volCurveId = volCurveId;
	}

//	public VolCurve(String volCurveId, String volCurveName, String underlyingId,
//			Set<PricingUnderlying> pricingUnderlyings, Set<Pricing> pricings) {
//		this.volCurveId = volCurveId;
//		this.volCurveName = volCurveName;
//		this.underlyingId = underlyingId;
//		this.pricingUnderlyings = pricingUnderlyings;
//		this.pricings = pricings;
//	}

	@Id
	@Column(name = "VOL_CURVE_ID", unique = true, nullable = false, length = 20)
	public String getVolCurveId() {
		return this.volCurveId;
	}

	public void setVolCurveId(String volCurveId) {
		this.volCurveId = volCurveId;
	}

	@Column(name = "VOL_CURVE_NAME", length = 50)
	public String getVolCurveName() {
		return this.volCurveName;
	}

	public void setVolCurveName(String volCurveName) {
		this.volCurveName = volCurveName;
	}

	@Column(name = "UNDERLYING_ID", length = 20)
	public String getUnderlyingId() {
		return this.underlyingId;
	}

	public void setUnderlyingId(String underlyingId) {
		this.underlyingId = underlyingId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volCurve")
	public Set<PricingUnderlyings> getPricingUnderlyings() {
		return this.pricingUnderlyings;
	}

	public void setPricingUnderlyings(Set<PricingUnderlyings> pricingUnderlyings) {
		this.pricingUnderlyings = pricingUnderlyings;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volCurve")
//	public Set<Pricing> getPricings() {
//		return this.pricings;
//	}
//
//	public void setPricings(Set<Pricing> pricings) {
//		this.pricings = pricings;
//	}

}
