package com.eugenefe.entity.component;

// Generated 2014. 1. 17 ¿ÀÈÄ 5:07:56 by Hibernate Tools 4.0.0

import javax.persistence.Embeddable;
import com.eugenefe.entity.IrCurve;
import com.eugenefe.entity.VolCurve;

/**
 * PricingUnderlyings generated by hbm2java
 */

@Embeddable
public class PricingUnderlyings implements java.io.Serializable {

	private String underlyingId;
//	private String refIrcId;
//	private String volCurveId;
	private IrCurve refIrc;
	private VolCurve volCurve;

	public PricingUnderlyings() {
	}
	public PricingUnderlyings(String underlyingId, IrCurve refIrc, VolCurve volCurve) {
		this.underlyingId = underlyingId;
		this.refIrc = refIrc;
		this.volCurve = volCurve;
	}

	public String getUnderlyingId() {
		return underlyingId;
	}
	public void setUnderlyingId(String underlyingId) {
		this.underlyingId = underlyingId;
	}

	public IrCurve getRefIrc() {
		return refIrc;
	}
	public void setRefIrc(IrCurve refIrc) {
		this.refIrc = refIrc;
	}
	
	public VolCurve getVolCurve() {
		return volCurve;
	}

	public void setVolCurve(VolCurve volCurve) {
		this.volCurve = volCurve;
	}
	
}
