package com.eugenefe.entity.crud;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.eugenefe.enums.EBondCfType;
import com.eugenefe.enums.EBoolean;
import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;
import com.eugenefe.util.EColumnType;

/**
 * Bond generated by hbm2java
 */
@Entity
@Table(name = "INTRINSIC_BOND")
public class IntrinsicBond implements java.io.Serializable {
	private String bondId;
	private String bondName;
	private String issuerId;
	private BigDecimal faceAmt;
	private EBoolean fundedYn;
	private BigDecimal totalAmt;
	private String currCd;
	private EBondCfType bondCfType;
	private String issueDate;
	private String maturityDate;
	private String refRate;
	private BigDecimal couponRate;
	private String intTerm;
	private String creditRatingCd;
	
	public IntrinsicBond() {
	}

	@Id
	@Column(name = "BOND_ID", unique = true, nullable = false, length = 20)
	public String getBondId() {
		return this.bondId;
	}
	public void setBondId(String bondId) {
		this.bondId = bondId;
	}

	@Column(name = "BOND_NAME")
	public String getBondName() {
		return bondName;
	}

	public void setBondName(String bondName) {
		this.bondName = bondName;
	}

	@Column(name = "ISSUER_ID", length = 30)
	@Size(max = 30)
	@AnnoMethodTree(order=40, init=true)
	public String getIssuerId() {
		return this.issuerId;
	}

	public void setIssuerId(String issuerId) {
		this.issuerId = issuerId;
	}

	@Column(name = "FACE_AMT")
	@AnnoMethodTree(order=50, init=true, align="right")
	public BigDecimal getFaceAmt() {
		return this.faceAmt;
	}

	public void setFaceAmt(BigDecimal faceAmt) {
		this.faceAmt = faceAmt;
	}
	@Column(name = "FUNDED_YN")
	@Enumerated(EnumType.STRING)
	public EBoolean getFundedYn() {
		return fundedYn;
	}

	public void setFundedYn(EBoolean fundedYn) {
		this.fundedYn = fundedYn;
	}

	@Column(name = "TOTAL_AMT", scale = 0)
	@AnnoMethodTree(order=51, init=true, align="right")
	public BigDecimal getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(BigDecimal totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "ISSUE_DATE", length = 8)
	@Size(max = 8)
	@AnnoMethodTree(order=52, init=true)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "MATURITY_DATE", length = 8)
	@Size(max = 8)
	@AnnoMethodTree(order=53, init=true)
	public String getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(String maturityDate) {
		this.maturityDate = maturityDate;
	}

	@Column(name = "REF_RATE")
	public String getRefRate() {
		return refRate;
	}

	public void setRefRate(String refRate) {
		this.refRate = refRate;
	}

	@Column(name = "COUPON_RATE", precision = 10, scale = 8)
	@AnnoMethodTree(order=54, init=true, align ="right")
	public BigDecimal getCouponRate() {
		return this.couponRate;
	}

	public void setCouponRate(BigDecimal couponRate) {
		this.couponRate = couponRate;
	}

	@Column(name = "INT_TERM", length = 10)
	@Size(max = 10)
	@AnnoMethodTree(order=55, init=true, align ="right")
	public String getIntTerm() {
		return this.intTerm;
	}

	public void setIntTerm(String intTerm) {
		this.intTerm = intTerm;
	}



	@Column(name = "BOND_CF_TYPE", length = 10)
	@Enumerated(EnumType.STRING)
	@AnnoMethodTree(order=58, init=true)
	public EBondCfType getBondCfType() {
		return this.bondCfType;
	}

	public void setBondCfType(EBondCfType bondCfType) {
		this.bondCfType = bondCfType;
	}


	@Column(name = "CREDIT_RATING_CD", length = 10)
	@Size(max = 10)
	@AnnoMethodTree(order=61, init=true)
	public String getCreditRatingCd() {
		return this.creditRatingCd;
	}

	public void setCreditRatingCd(String creditRatingCd) {
		this.creditRatingCd = creditRatingCd;
	}

	@Column(name = "CURR_CD", length = 3)
	@Size(max = 3)
	@AnnoMethodTree(order=20, init=true)
	public String getCurrCd() {
		return this.currCd;
	}

	public void setCurrCd(String currCd) {
		this.currCd = currCd;
	}
}
