package com.eugenefe.entity.crud;

// Generated Apr 16, 2013 7:33:55 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKeyColumn;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugenefe.util.AnnoMethodTree;
import com.eugenefe.util.AnnoNavigationFilter;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION", schema="TAKION99")
@AnnoNavigationFilter
public class PositionCrud implements Serializable {

	private String posId;
	private String posName;
	private String posSide;
	private String prodId;
	private String cpartyId;
	private String fundId;
	private String txType;
	private String elsOptType;
	private String currency;
	private String settleCurrency;
	private String initTxDate;
	private String lastTxDate;
	private BigDecimal initTxPrice;
	private BigDecimal initFeeAmt;
	private BigDecimal initTxAmt;
	private BigDecimal initTxPar;
	private BigDecimal initHoldingQty;

	
	public PositionCrud() {
	}

	public PositionCrud(String posId) {
		this.posId = posId;
	}

	public PositionCrud(String posId, String posName, String initTxDate, String lastTxDate, BigDecimal initTxPrice,
			BigDecimal initFeeAmt, BigDecimal initTxAmt, BigDecimal holdingQty) {
		this.posId = posId;
		this.posName = posName;
		this.initTxDate = initTxDate;
		this.lastTxDate = lastTxDate;
		this.initTxPrice = initTxPrice;
		this.initFeeAmt = initFeeAmt;
		this.initTxAmt = initTxAmt;
		this.initHoldingQty = holdingQty;
	}

	@Id
	@Column(name = "POS_ID", nullable = false, length = 50)
	@AnnoMethodTree(order=10, init=true, aggregatable=true)
	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	@Column(name = "POS_NAME", length = 50)
	public String getPosName() {
		return this.posName;
	}

	public void setPosName(String posName) {
		this.posName = posName;
	}
	
	@Column(name = "POS_SIDE")
	public String getPosSide() {
		return posSide;
	}

	public void setPosSide(String posSide) {
		this.posSide = posSide;
	}

	
	@Column(name = "PROD_ID")
	public String getProdId() {
		return prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	@Column(name = "COUNTERPARTY_ID")
	public String getCpartyId() {
		return cpartyId;
	}
	public void setCpartyId(String cpartyId) {
		this.cpartyId = cpartyId;
	}

	


	@Column(name = "FUND_ID")
	public String getFundId() {
		return fundId;
	}

	public void setFundId(String fundId) {
		this.fundId = fundId;
	}

//	@Transient
	@Column(name = "TX_TYPE", length = 20)
	public String getTxType() {
		return txType;
	}

	public void setTxType(String txType) {
		this.txType = txType;
	}
	@Column(name = "ELS_OPT_TYPE", length = 20)
	public String getElsOptType() {
		return elsOptType;
	}

	public void setElsOptType(String elsOptType) {
		this.elsOptType = elsOptType;
	}
	@Column(name = "CURR_CD", length = 3)
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}
	@Column(name = "STL_CURR_CD", length = 3)
	public String getSettleCurrency() {
		return settleCurrency;
	}

	public void setSettleCurrency(String settleCurrency) {
		this.settleCurrency = settleCurrency;
	}

	@Column(name = "INIT_TX_DATE", length = 8)
	public String getInitTxDate() {
		return this.initTxDate;
	}

	public void setInitTxDate(String initTxDate) {
		this.initTxDate = initTxDate;
	}

	
//	@Transient
	@Column(name = "LAST_TX_DATE", length = 8)
	public String getLastTxDate() {
		return this.lastTxDate;
	}

	public void setLastTxDate(String lastTxDate) {
		this.lastTxDate = lastTxDate;
	}
//	@Transient
	@Column(name = "INIT_TX_PRICE", scale = 4)
	public BigDecimal getInitTxPrice() {
		return this.initTxPrice;
	}

	public void setInitTxPrice(BigDecimal initTxPrice) {
		this.initTxPrice = initTxPrice;
	}
	
//	@Transient
	@Column(name = "INIT_FEE_AMT", scale = 4)
	public BigDecimal getInitFeeAmt() {
		return this.initFeeAmt;
	}

	public void setInitFeeAmt(BigDecimal initFeeAmt) {
		this.initFeeAmt = initFeeAmt;
	}
	
//	@Transient
	@Column(name = "INIT_TX_AMT", scale = 4)
	public BigDecimal getInitTxAmt() {
		return this.initTxAmt;
	}

	public void setInitTxAmt(BigDecimal initTxAmt) {
		this.initTxAmt = initTxAmt;
	}

	@Column(name = "INIT_TX_PAR", scale = 4)
	public BigDecimal getInitTxPar() {
		return initTxPar;
	}

	public void setInitTxPar(BigDecimal initTxPar) {
		this.initTxPar = initTxPar;
	}

	@Column(name = "INIT_HOLDING_QTY" , scale = 8)
	public BigDecimal getInitHoldingQty() {
		return initHoldingQty;
	}

	public void setInitHoldingQty(BigDecimal initHoldingQty) {
		this.initHoldingQty = initHoldingQty;
	}
}
