package com.eugenefe.entity.crud;

// Generated Apr 10, 2013 4:09:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.eugenefe.entity.PositionReturnId;


/**
 * PositionReturn generated by hbm2java
 */
@Entity
@Table(name = "POSITION_RETURN", schema="TAKION99")
public class PositionReturnCrud implements java.io.Serializable {

	private PositionReturnId id;
	private BigDecimal bookAmt;
	private BigDecimal presValue;
	private BigDecimal holdingQty;
	private BigDecimal dailyReturn;
	private BigDecimal monthlyReturn;
	private BigDecimal quartlyReturn;
	private BigDecimal annualReturn;
	private BigDecimal fiscalReturn;
	private BigDecimal deltaReturn;
	private BigDecimal gammaReturn;
	private BigDecimal vegaReturn;
	private BigDecimal thetaReturn;
	private BigDecimal rhoReturn;
	
	public PositionReturnCrud() {
	}

	public PositionReturnCrud(PositionReturnId id) {
		this.id= id;
	}
	public PositionReturnCrud(String bssd, String posId) {
		this.id= new PositionReturnId(bssd, posId);
	}
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "posId", column = @Column(name = "POS_ID", nullable = false, length = 50)) })
	@NotNull
	public PositionReturnId getId() {
		return this.id;
	}

	public void setId(PositionReturnId id) {
		this.id = id;
	}

	@Column(name = "BOOK_AMT", scale = 4)
	public BigDecimal getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(BigDecimal bookAmt) {
		this.bookAmt = bookAmt;
	}

	@Column(name = "PV", scale = 4)
	public BigDecimal getPresValue() {
		return this.presValue;
	}
	public void setPresValue(BigDecimal pv) {
		this.presValue = pv;
	}
	
	@Column(name = "HOLDING_QTY", precision=8)
	public BigDecimal getHoldingQty() {
		return holdingQty;
	}

	public void setHoldingQty(BigDecimal holdingQty) {
		this.holdingQty = holdingQty;
	}

	@Column(name = "DAILY_RETURN", scale = 4)
	public BigDecimal getDailyReturn() {
		return this.dailyReturn;
	}

	public void setDailyReturn(BigDecimal dailyReturn) {
		this.dailyReturn = dailyReturn;
	}

	@Column(name = "MONTHLY_RETURN", scale = 4)
	public BigDecimal getMonthlyReturn() {
		return this.monthlyReturn;
	}

	public void setMonthlyReturn(BigDecimal monthlyReturn) {
		this.monthlyReturn = monthlyReturn;
	}

	@Column(name = "QUARTLY_RETURN", scale = 4)
	public BigDecimal getQuartlyReturn() {
		return this.quartlyReturn;
	}

	public void setQuartlyReturn(BigDecimal quartlyReturn) {
		this.quartlyReturn = quartlyReturn;
	}

	@Column(name = "ANNUAL_RETURN", scale = 4)
	public BigDecimal getAnnualReturn() {
		return this.annualReturn;
	}

	public void setAnnualReturn(BigDecimal annualReturn) {
		this.annualReturn = annualReturn;
	}

	@Column(name = "FISCAL_RETURN", scale = 4)
	public BigDecimal getFiscalReturn() {
		return this.fiscalReturn;
	}

	public void setFiscalReturn(BigDecimal fiscalReturn) {
		this.fiscalReturn = fiscalReturn;
	}

	@Column(name = "DELTA_RETURN", scale = 4)
	public BigDecimal getDeltaReturn() {
		return this.deltaReturn;
	}

	public void setDeltaReturn(BigDecimal deltaReturn) {
		this.deltaReturn = deltaReturn;
	}

	@Column(name = "GAMMA_RETURN", scale = 4)
	public BigDecimal getGammaReturn() {
		return this.gammaReturn;
	}

	public void setGammaReturn(BigDecimal gammaReturn) {
		this.gammaReturn = gammaReturn;
	}

	@Column(name = "VEGA_RETURN", scale = 4)
	public BigDecimal getVegaReturn() {
		return this.vegaReturn;
	}

	public void setVegaReturn(BigDecimal vegaReturn) {
		this.vegaReturn = vegaReturn;
	}

	@Column(name = "THETA_RETURN", scale = 4)
	public BigDecimal getThetaReturn() {
		return this.thetaReturn;
	}

	public void setThetaReturn(BigDecimal thetaReturn) {
		this.thetaReturn = thetaReturn;
	}

	@Column(name = "RHO_RETURN", scale = 4)
	public BigDecimal getRhoReturn() {
		return this.rhoReturn;
	}

	public void setRhoReturn(BigDecimal rhoReturn) {
		this.rhoReturn = rhoReturn;
	}

	
}
